### ISSUE TITLE
Issue, Commit, or Pull request tag for potential DSpace contributions?

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#100]
I propose using a tag(s) for issues or commits or pull requests that we might want to contribute to the DSpace project. For instance, "Separate publishers in list view," #92 is a candidate, since it clearly fixes a shortcoming in the Mirage 2 theme. Possible tags are  "possible contribution to DSpace," "contribute to DSpace," and "contributed to DSpace." 

Possible advantages of the tags are that we'd be able to track our contributions to the DSpace project, and that it would aid us in following through on contributions.

**Comment by amandafrench** [comment]
Good idea, @alawvt! I think you can create labels: feel free to create one and apply it here to any appropriate issue. That word-wrap issue I fixed is another candidate: I've got on my to do list to set up a separate repo so I can contribute that back to Mirage2.

**Comment by alawvt** [comment]
@amandafrench, would you add labels since it wouldn't let me?

**Comment by amandafrench** [comment]
I created an issue Label called "dspacecore" for this category of issue, and I'll go back and apply it to #92 and other relevant issues (esp with the Mirage theme). Git tags is another topic altogether: I hadn't heard about that at all. Pretty good overview at https://git-scm.com/book/en/v2/Git-Basics-Tagging. 

I think if we can remember to tag do this (and train one another, and write it in the wiki) it's a good idea, though issue labels might suffice. I'll add a little text now to the wiki about it.

**Comment by alawvt** [comment]
@amandafrench, thank you for the dspacecore tag. Labeling Pull Requests and Issues works for me.
