### ISSUE TITLE
Create a custom submission form for the OMALS collection /51287

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#102]
Same process as #101. Fields for submission process: 

dc.contributor.author
dc.date.issued
dc.title
dc.description.abstract
dc.subject
dc.publisher
dc.rights
dc.type
dc.contributor.department
dc.description.degree
thesis.degree.name
thesis.degree.level
thesis.degree.grantor
thesis.degree.discipline

dc.contributor.committeechair
dc.contributor.committeemember

According to @alawvt: 

> dc.publisher
dc.rights
dc.description.degree
thesis.degree.name
thesis.degree.level
thesis.degree.grantor

>could be added in a non-interactive step, https://wiki.duraspace.org/display/DSDOC5x/Submission+User+Interface#SubmissionUserInterface-CreatingaNon-InteractiveStep.

>thesis.degree.discipline would ideally be a drop down list

Options for thesis.degree.discipline: 

* Food Safety and Biosecurity
* Education and Leadership Studies
* Plant Science and Pest Management
* Food Safety
* Biosecurity, Bio-regulations, and Public Health
* Environmental Science
* Agricultural and Life Sciences

**Comment by alawvt** [comment]
I realized later there were a few other options for thesis.degree.discipline so we might have to leave it free text.

**Comment by alawvt** [comment]
I'd suggest doing this form before the NDLTD one.

**Comment by alawvt** [comment]
Note to @alaw to review submission form with OMALS members.
