### ISSUE TITLE
Remove BioMed Central Collection duplicates (95 out of 375 items)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#109]
Hi @amandafrench , I've been reviewing the metadata in the BioMed Central Collection (http://vtechworks.lib.vt.edu/handle/10919/18629) and have noticed that there are possibly around 95 duplicate items (I checked this using Google Refine). I haven't gotten the chance to go through all of these duplicates in depth (should I try to do this before the sprint retrospective?), but it may take quite a while to root all of these out since I need to inspect each item one by one. Thanks so much!

**Comment by mello99** [comment]
Okay, I just went through the metadata for all of the possible duplicates and found a total of 95 out of 375 total items. I looked at 12 of these 95 items and found that each one contained the same bitstreams, so it looks like these are indeed full-blown duplicates. I have the duplicates list, but I won't remove anything until next week (in case someone needs to poke around to see what went wrong). Thanks!

**Comment by alawvt** [comment]
@keithgee knows much more of the history of the SWORD import for BioMed Central since he set it up. I recall it beening off for period(s). It is possible that it accepted the same articles. The accession dates might suggest a pattern.

**Comment by amandafrench** [comment]
Hi @mello99 -- sorry have let this slip. I say for this issue we just remove the duplicates from the Biomed Central collection and hope they don't reappear. If you want to do this manually, you can, but I'm also looking into whether we can buy the Metadata Quality module from @bram-atmire - see https://atmire.com/website/?q=modules/mqm 

I'll assign you to it, @mello99, but no need to do it until January.

**Comment by keithgee** [comment]
What, @amandafrench ? I was just about to fix this!
Okay, not really. I hadn't figured out how this happened. I'll cross my fingers as well and work on other things.
