### ISSUE TITLE
BioMed Central Collection - DOI appearing in URI field (around 45 items)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#110]
Hi @keithgee , the metadata for around 45 out of the 375 BioMed Central items (not accounting for the 95 duplicates, which may significantly reduce this number) contain DOIs in the URI field (dc.identifier.uri); this field should be reserved for the DSpace-generated handle. I just wanted to bring this issue to your attention; thanks so much!

**Comment by keithgee** [comment]
@mello99, I've done a database query and moved metadata with http://dx.doi.org* values from the identifier.uri field to identifier.doi.  
Is this what you needed?
If so, had you already done most of this manually? 
If not, which items still show the problem and what specifically should be done with DOIs in the URI field?

```

# First I moved them to identifier.url
update metadatavalue set metadata_field_id=86 where metadata_field_id=25 and text_value  like '%dx.doi.org%';
UPDATE 8

# Then I noticed they should be in identifier.doi - 11 updated instead of 8
 update metadatavalue set metadata_field_id=96 where metadata_field_id=86 and text_value  like '%dx.doi.org%';
```

**Comment by keithgee** [comment]
Verified with @mello99 that identifier.doi is the correct field. There may be another issue opened soon about how to fix this permanently.
Closing this issue.

**Comment by keithgee** [comment]
The xslt code/configuration that maps DOIs from SWORD to dc.identifier.doi hasn't been deployed yet, so I ran some SQL again this morning to update 10 new items.

```
update metadatavalue set metadata_field_id=96 where metadata_field_id=25 and text_value like '%dx.doi.org%';
UPDATE 10
```
