### ISSUE TITLE
VTechWorks handles not resolving

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#111]
When entering a handle url, such as http://hdl.handle.net/10919/63916 into the browser, the following message appears instead of the expected page.

Error - Cannot Connect to Server

The handle you requested --

10919/63916

-- cannot be found.

**Comment by alawvt** [comment]
Thanks, @keithgee, I have reported it to CNRI.

**Comment by keithgee** [comment]
Thanks, @alawvt . I also opened TeamDynamix issue 1137438, as the problem is more likely with VTechWorks.

**Comment by keithgee** [comment]
or, something on our end, at least

**Comment by alawvt** [comment]
It's resolving now.

**Comment by keithgee** [comment]
Aaron restarted the handle server.
