### ISSUE TITLE
Item not indexed

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#113]
Report from a user that item https://vtechworks.lib.vt.edu/handle/10919/51133 does not show up in search results and is not listed in its assigned collection at https://vtechworks.lib.vt.edu/handle/10919/50956. It is public, and the same item is properly indexed on dev. Some bug in indexing? All item, bundle, and bitstream authorizations seem to be correct. (READ: ANONYMOUS)

Thread at http://dspace.2283337.n4.nabble.com/items-not-indexed-td4679638.html suggests that there might be a flag in the database set to 'false' preventing this item from being indexed.

**Comment by alawvt** [comment]
This item was deposited 12/13/14, which I believe, was soon after we moved to DSpace 4 and Discovery became the default, so I don't think that discovery=false bug reported in dspace.nabble is the issue. In my local copy of the repository, the CS4984 collection does include this item. That makes me think this is an indexing issue. @keithgee or @kayiwa, can you think of a reason only selected item(s) would not be indexed? Is it possible to check the logs to see if the indexing cron job is finishing completely?

**Comment by alawvt** [comment]
On VTechWorks server, in /dspace/log/, there is 
```
-rwxrwxr-x  1 vtechworks vtechworks 606M Sep  6 23:59 solr.log.2015-09-06
-rw-r--r--  1 vtechworks vtechworks 646M Oct  7 23:59 solr.log.2015-10-07
-rw-r--r--  1 vtechworks vtechworks 652M Oct 11 23:59 solr.log.2015-10-11
-rw-r--r--  1 vtechworks vtechworks 654M Oct 15 23:59 solr.log.2015-10-15
-rw-r--r--  1 vtechworks vtechworks 721M Oct 30 23:59 solr.log.2015-10-30
-rw-r--r--  1 root       root          0 Nov 17 00:00 solr.log.2015-11-17
```
I thought the cron job was to run index-discovery nightly but it doesn't look like it has run successfully since 2015-10-30.

**Comment by alawvt** [comment]
solr.log.2015-10-30 contains item https://vtechworks.lib.vt.edu/handle/10919/51133 and it appears to have indexed it properly. But if today's indexing job didn't finish (file size=0) and it hasn't been indexed since 10/30, it seems like another indexing would be a good place to start.

**Comment by amandafrench** [comment]
Recently added items are indexed, though, @alaw which you'd think they wouldn't be if indexing weren't finishing. See for instance http://vtechworks.lib.vt.edu/handle/10919/63991 -- search for "geoblacklight" produces expected results.

**Comment by keithgee** [comment]
The item is now indexed. I took these actions.

- Add "ZIP" to mime-type registry
- Delete *.zip.txt file built by media registry
- Change file type of zip file from TXT to ZIP
- Edit a name in the metadata field
- Change the name back to what it was previously

Also noting that this item is versioned and has a strange message at the top of the page, but I'm not sure if it's related.

Closing.

**Comment by alawvt** [comment]
@keithgee, thank you for fixing this item.  

I could see why indexing would choke on a zip file. Why wouldn't indexing of the metadata for the item still be ok?

I checked for other items that have (only) zip files. http://vtechworks.lib.vt.edu/handle/10919/18720 has only a zip file and is findable now in vtechworks. I searched for the same item on vtechworks.dev., where zip has not been added to the format-registry. It is findable there, too. Perhaps all that was needed was to change something in the metadata for this item, as you did, then change it back. No doubt, we will have occasion to test this further.

**Comment by keithgee** [comment]
Good morning, @alawvt!
Editing the metadata for an item does indeed often cause the item to be added or updated in the solr index. I tried this first, but it didn't work.

Then, I noticed that there was a file with a .zip.txt extension in the bitstreams, which meant that DSpace had tried to full-text index the ZIP file. There was, um, garbage inside of the .zip.txt file, so I deleted it. I also noticed that the type of the ZIP file was set to TXT (or TEXT, I can't remember). In the item that you've sent, it is marked as type "Unknown" instead. I tried to change the type of the ZIP bitstream to Unknown in the un-indexed item as well, but DSpace didn't save the changes. So I added ZIP as a type in the format registry, set the file to that type, and then the changes were saved.
Then I edited the metadata in the item again, and the item was now added to the solr index.

I don't know precisely why this item was not indexed initially, but the fulltext for an item and the indexed metadata for an item are both stored in the same solr document. Before performing this procedure, there was no solr document for this item,  and after performing this procedure the item had a document in the index and is now discoverable.

**Comment by alawvt** [comment]
@keithgee, thank you for the explanation. 

The same item on vtechworks.dev. also has a outbreaksum_code.zip.txt associated with it. I wonder why that one was indexed.

I checked other items from the CS4984: Computational Linguistics collection on the development server. They are discoverable. Even though zip is listed as "Undefined" on vtechworks.dev, zip.txt files were not created for these items. It is curious why DSpace created zip.txt for this problem item but similar items in the same collection.

**Comment by alawvt** [comment]
After discussion with @keithgee, I will add two follow up tasks to the Technology backlog:

check database for other possible zip.txt files

after version 5.4 is installed, check that logging of solr indexing occurs. ([5.4](https://wiki.duraspace.org/display/DSPACE/DSpace+Release+5.4+Status) has a fix for this.)
