### ISSUE TITLE
Make sure HTML entities display correctly

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#114]
Related to #84 -- it seems to be the case that HTML entities such as `&amp;` and `&szlig` are not displaying correctly. Sample items: http://vtechworks.lib.vt.edu/handle/10919/59451 and http://vtechworks.lib.vt.edu/handle/10919/46509?show=full. These were hard-coded in before UTF-8. 

More on HTML entities at http://www.w3schools.com/html/html_entities.asp

**Comment by amandafrench** [comment]
See perhaps https://jira.duraspace.org/browse/DS-1092?jql=text%20~%20%22entities%22 for a solution?

**Comment by alawvt** [comment]
`&amp;` is an HTML entity but `&szlig` is missing the ending semicolon, so I don't expect it to every be handled well.

**Comment by AmberPoo1** [comment]
@amandafrench, @alawvt , Dspace can decode html entities correctly by default. The problem with http://vtechworks.lib.vt.edu/handle/10919/46509?show=full is that it contained illegal html entities. for example: "&amp;szlig". 
![screen shot 2015-12-14 at 3 00 13 pm](https://cloud.githubusercontent.com/assets/13734326/11792481/4e1095e0-a274-11e5-9d0e-0be85720a125.png)

The legal html entities should be "&amp;" and "&szlig;".
