### ISSUE TITLE
etd ingest "logrotate"

### ISSUE THREAD

**Issue by kayiwa** [VTUL/vtechworks#117]
The import script seems unable to forget files it already processed. My understanding of the port is all we would need to do is a name change. Can you give it a looksie and see why it keeps trying to process already deleted directories?

**Comment by alawvt** [comment]
I'm not sure that is a problem. upload_Myers_PE_T_2015.zip was uploaded twice this morning to /space/etd/etd_incoming/2015113009:36:13093613-0500 and to /space/etd/etd_incoming/2015113009:38:34093834-0500. I received two messages, one that it was processed correctly and another that it had already been uploaded to VTechWorks. This is the expected behavior. I will check the others.

**Comment by kayiwa** [comment]
I was not refererring to any specific one @alawvt any script that spits out this many errors should be source for concern. But if this is expected behavior. Please close the ticket.

**Comment by kayiwa** [comment]
Specifically. My question amounts to. This is a cron job that will fail given this.

```
vtechworks@vtechworks:/dspace/assetstore/ingest/etd-gradschool/bin$ ./etd_ingest.sh
rm: cannot remove ‘/space/etd/etd_incoming/2015111915_04_18150418-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110909_23_13092313-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110416_21_15162115-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111310_18_47101847-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110416_20_24162024-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110510_55_15105515-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111713_39_19133919-0500’: No such file or directory
^Crm: cannot remove ‘/space/etd/etd_incoming/2015110615_29_38152938-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111309_41_05094105-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110912_22_32122232-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110416_27_03162703-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111315_25_39152539-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111315_50_31155031-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110509_49_54094954-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110911_39_17113917-0500’: No such file or directory
^Crm: cannot remove ‘/space/etd/etd_incoming/2015111315_47_22154722-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111614_22_07142207-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111811_07_54110754-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111310_51_28105128-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110611_06_50110650-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110508_46_11084611-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111315_56_19155619-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111915_58_14155814-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110615_13_19151319-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110509_17_30091730-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110510_56_32105632-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015102312_25_42122542-0400’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015111815_32_04153204-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015102312_51_20125120-0400’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110510_53_16105316-0500’: No such file or directory
rm: cannot remove ‘/space/etd/etd_incoming/2015110510_57_53105753-0500’: No such file or directory
mv: try to overwrite ‘/dspace/assetstore/ingest/etd-gradschool/error/2015102312_25_42122542-0400/potatoe.txt’, overriding mode 0644 (rw-r--r--)?
```

The error at the bottom will require human action.

**Comment by alawvt** [comment]
The script does remove the file from the FTP server once it runs, so that is why there were all the "no such file" messages. Most of the error messages seem to be from items you loaded as tests, which are previously loaded items.  So the errors are mostly, "this item already exists." The script is acting normally. I will delete them from the error folder. If you want to delete the potato files from the FTP server, that's fine. Things seem ok (or at least to be expected). Thanks

**Comment by alawvt** [comment]
For most of these test ETDs that were uploaded previously, there were two error messages sent on 11/24 and another this morning, 11/30. If the files are being moved off etdingest after the script runs, then they shouldn't reappear tomorrow. I'm sorting through the error folder. Let's leave this issue open and see how things go the next few days. It should be easier to see what's going on without the huge backlog.

**Comment by alawvt** [comment]
@kayiwa, 40 test files ran again this morning. Let's figure out why this is happening.

**Comment by alawvt** [comment]
@kayiwa, I notice that the script is looking for 
```
rm: cannot remove ‘/space/etd/etd_incoming/2015111915_04_18150418-0500’
```
but the email has colons in the path, e.g.
```
File has been deposited at /space/etd/etd_incoming/2015113009:49:06094906-0500
```

**Comment by alawvt** [comment]
In the latest log file for the etd-ingest script, `/dspace/assetstore/ingest/etd-gradschool/log/cron-2015-12-09.log`, there are a two errors each of:

```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /dspace/log/checker.log.2015-12-01 (Permission denied)
```
and

```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /dspace/log/solr.log.2015-12-01 (Permission denied)
```

**Comment by alawvt** [comment]
I deleted a few duplicate folders in /dspace/assetstore/ingest/etd-gradschool/incoming/ and ran the script again. It processed 3 ETDs and sent the 3 corresponding messages. There were no error messages sent. There also was no /dspace/assetstore/ingest/etd-gradschool/incoming/ folder afterward, which I believe is good. We'll check tomorrow morning's run before closing the issue.
