### ISSUE TITLE
Add .svg format to registry

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#118]
So that svg files can be uploaded

**Comment by alawvt** [comment]
I added svg to the file format registry. However this does not enable support in the theme.

"Themes

A Theme is a collection of XSL stylesheets and supporting files like images, CSS styles, translations, and help documents. The XSL stylesheets are applied to the DRI Document to covert it into a readable format and give it structure and basic visual formatting in that format. The supporting files are used to provide the page with a specific look and feel, insert images and other media, translate the content, and perform other tasks. The currently used output format is XHTML and the supporting files are generally limited to CSS, images, and JavaScript. More output formats, like PDF or SVG, may be added in the future."

-- https://wiki.duraspace.org/display/DSDOC5x/DRI+Schema+Reference#DRISchemaReference-Themes

**Comment by amandafrench** [comment]
I kind of figured that, but good to have confirmation. Thx @alawvt. Will close.
