### ISSUE TITLE
VTechWorks is choking on CSV uploads (anywhere from 400 to 990 items per CSV)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#119]
Hi @kayiwa, @amandafrench, @keithgee, and @alawvt , I made a few corrections to the "dc.type", "dc.contributor.author", and "dc.subject" fields in the "College of Science" and "College of Engineering" communities, but I wounded DSpace in the process.

To elaborate, when I uploaded the edited CSV files for the aforementioned collections, DSpace choked on them, even if the CSVs contained less than 1000 rows. The last CSV I uploaded only had 500 rows. I received the message listed below after I attempted to apply the metadata changes from the most recent CSV:

![screen shot 2015-12-03 at 1 05 43 am]
(https://cloud.githubusercontent.com/assets/5408616/11553242/cdf2c558-995a-11e5-8200-4c82b01f9c76.png)

I also received this error message:
![screen shot 2015-12-03 at 1 11 50 am](https://cloud.githubusercontent.com/assets/5408616/11553257/e522c868-995a-11e5-8992-fa55cf1cc51a.png)

On other occasions when I've uploaded corrected CSVs to DSpace, even if I received an "Import Failed" message, the changes still went through; I just couldn't confirm this unless 1) I re-uploaded the CSV file and found that no changes needed to be made, or 2) looked through the selected collections' metadata to see if anything had changed. 

What was different this time, though, is that I encountered the "The request URL/admin/metadataimport was not found on this server" message. DSpace also went down briefly for a few moments after I tried uploading one of the CSVs. 

So yes, I tried to batch-correct some collection metadata and broke DSpace in the process (it has since recovered). Thanks, all, and I apologize for any typos and/or grammatical errors (it's getting late).

**Comment by alawvt** [comment]
@mello99, I'm sorry the web metadata upload is so problematic. The command line version, "Item Update tool, https://wiki.duraspace.org/display/DSDOC5x/Updating+Items+via+Simple+Archive+Format, is better in that it gives more communication and a better trail. If you want me to load the larger batches that way, that would be fine. If there is bitstreams to add for the item, they would be listed in the first column of the csv. The next column, dc.identifier, uri, would contain the handle in the form, http://hdl.handle.net/10919/63898.

**Comment by amandafrench** [comment]
I think the "Not found" error was likely due to something happening on the server at the time you were working, @mello99 -- either @kayiwa making changes or a cron job happening. I did also try to replicate this with the College of Science collection, and the CSV of 991 rows did upload just fine, though I only made 69 changes. We'll make sure to get us trained in the command line tools soon. If this issue recurs, you can reopen it.
