### ISSUE TITLE
Test v. 5.4 and other changes on vtechworks.dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#124]
Please use the testing spreadsheet in Google Drive to record results. If there is a problem, please list an item where it can be observed.

**Comment by alawvt** [comment]
Changes to check
- fix HTML all fields
- add off campus sign in link
- separate publishers in display
- DSpace 5.4 release notes, https://wiki.duraspace.org/display/DSPACE/DSpace+Release+5.4+Status

**Comment by AmberPoo1** [comment]
Hi, @alawvt ,@kayiwa, when testing on vtechworks.dev, it seems the dev machine doesn't have available space for creating new items.
This is the error message:  "ERROR: could not extend file "base/29257/30954": No space left on device Hint: Check free disk space."

**Comment by alawvt** [comment]
I also attempted to upload an item with the web form and had the same problem, see screenshot below. I reported the error with TeamDynamix 12/14.


![vtechworksdevsubmissionerror20151214](https://cloud.githubusercontent.com/assets/13037168/11783447/6441e67c-a245-11e5-92f9-5145d3f9d1ff.png)

**Comment by alawvt** [comment]
@kayiwa, thank you for increasing the volume size. I was able to upload an item. @AmberPoo1, please continue testing.

**Comment by alawvt** [comment]
finished testing.
