### ISSUE TITLE
Improve git procedure and branches to track changes to dev, pprd, and production

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#125]

**Comment by keithgee** [comment]
There's a nice wiki page here that had a suggested workflow for tracking changes to production, especially, but now it may be out of date - we haven't been following it:
https://github.com/VTUL/vtechworks/wiki/Workflow-Summary

**Comment by alawvt** [comment]
I think we could follow our original plan. @kayiwa would have to be aware of the plan and where to pull from.

**Comment by amandafrench** [comment]
I think we've been doing pretty well with creating branches for features, at least: the main thing we haven't been doing is creating release branches and asking @kayiwa to deploy from there. I'll see if I can study up on this more.

**Comment by amandafrench** [comment]
Updated documentation at https://github.com/VTUL/vtechworks/wiki/0.-Workflow-Summary:-Development-and-Deployment - closed for now while we test.
