### ISSUE TITLE
Contribute pull #92 (separate publishers) to DSpace core project

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#127]
We think #92 should be contributed to the DSpace core -- assigning to @AmberPoo1. If you can, while you're doing it, please review and if necessary rewrite the [instructions on the wiki](https://github.com/VTUL/vtechworks/wiki/9.-Contributing-to-the-main-DSpace-project) about how to contribute to the core project. See also issue #68.

**Comment by alawvt** [comment]
@AmberPoo1, I added more instructions to https://github.com/VTUL/vtechworks/wiki/9.-Contributing-to-the-main-DSpace-project. Please test and improve them.

**Comment by alawvt** [comment]
@AmberPoo1, please add commit in Pull Request #148 to the contribution to DSpace core project.

**Comment by AmberPoo1** [comment]
This change has been submitted to DSpace core project.
The ticket on the DSpace Issue Tracker: https://jira.duraspace.org/browse/DS-3006
Pull request was created in the github/DSpace core project: https://github.com/DSpace/DSpace/pull/1250

Didn't find the relevant page on the DSpace wiki, so I didn't add new comments in the wiki.
