### ISSUE TITLE
Testing finished on vtechworks.dev; can be deployed to vtechworks.pprd 

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#133]
We have finished testing 5.4 and other changes on vtechworks.dev. The code can be deployed to vtechworks.pprd.

**Comment by amandafrench** [comment]
Have created the branch vt_5_x_pprd_deploy and asked @kayiwa to push to pprd. The tag structure I came up to track "release versions" feels too cumbersome to me, but for now we're sticking with [YYYY_MM_DD_sprintname]. We can always rename the tags alter if we like (I kind of like vtw_aardvark, vtw_bichon, vtw_chipmunk, vtw_dogue etc. without dates.) Will close the issue when the pprd server is updated.

**Comment by amandafrench** [comment]
Done
