### ISSUE TITLE
Test v. 5.4 and other changes on vtechworks.pprd

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#136]
@AmberPoo1, please do a cursory test of v. 5.4 and other changes on vtechworks.pprd.

**Comment by alawvt** [comment]
@AmberPoo1 has completed testing on pprd. 

@amandafrench, It may be deployed to production.

**Comment by amandafrench** [comment]
I have merged commits from vt_5_x_pprd_deploy into vt_5_x_prod_deploy and have asked @kayiwa to deploy them to production on Monday morning. That way he won't have to work late tonight if there are hiccups.

**Comment by alawvt** [comment]
We're live. Thanks, @amandafrench  and @kayiwa!
