### ISSUE TITLE
Display of long item file name needs wrapping

### ISSUE THREAD

**Issue by AmberPoo1** [VTUL/vtechworks#138]
On the simple item view, file name field will overlap the abstract part if the file name or file description is too long.  See: http://vtechworks.pprd.lib.vt.edu/handle/123456789/64324
![image](https://cloud.githubusercontent.com/assets/13734326/11882431/6323e384-a4da-11e5-9a12-98c71d2b882b.png)

**Comment by alawvt** [comment]
That's a mess. @AmberPoo1, please try this test on production.

**Comment by AmberPoo1** [comment]
@alawvt, production has the same problem.

**Comment by AmberPoo1** [comment]
![image](https://cloud.githubusercontent.com/assets/13734326/11882711/19ae4e54-a4dc-11e5-8643-7b2c272b3cf1.png)

**Comment by alawvt** [comment]
Need to fix on production, too.

**Comment by amandafrench** [comment]
Will close this issue, since it's fixed, although it's not yet deployed to production.

**Comment by alawvt** [comment]
@amandafrench and @AmberPoo1, long file names do wrap properly in dspace demo, http://demo.dspace.org/xmlui/handle/10673/614, so we don't need to submit our fix.
