### ISSUE TITLE
This item cannot be found via browsing and/or search

### ISSUE THREAD

**Issue by zhiwuxie** [VTUL/vtechworks#140]
War and Agriculture: Three Decades of Agricultural Land Use and Land Cover Change in Iraq

https://vtechworks.lib.vt.edu/handle/10919/46772

Its owning collection shows no item:

https://vtechworks.lib.vt.edu/handle/10919/46771

**Comment by mello99** [comment]
Hi @zhiwuxie , this is not the first time that DSpace has inaccurately counted the number of items in a collection (see issue #85 ). 

However, if you export the metadata from the "Research Data, Department of Geography" collection, you'll get a spreadsheet that lists the metadata for the dataset you referenced (https://vtechworks.lib.vt.edu/handle/10919/46772). 

I've attached the exported metadata spreadsheet to this comment. I'm not sure if this is significant or not, but the spreadsheet took at least 3 minutes to load in LibreOffice (it's 1.5 MB), and I also received a message that said, "The data could not be loaded completely because the maximum number of characters per cell was exceeded."

I'll ping @kayiwa , @keithgee , and @alawvt  to see what they think. 

[Geography_Research_Data_10919_46771.csv.zip](https://github.com/VTUL/vtechworks/files/66070/Geography_Research_Data_10919_46771.csv.zip)

**Comment by keithgee** [comment]
@mello99, it is definitely significant that it takes 3 minutes to load the spreadsheet.

The description.abstract field is using most of that 1.5 megabytes. There's a very long file listing there.

The VTechWorks search configuration is setup in such a way that abstracts larger than 32K will prevent the item from being indexed. Presumably this is the DSpace default; if so someone might want to check on mailing lists if this is a bug or on purpose.

I tested this by temporarily changing the abstract to "hi mom", and the item was indexed. I've changed it back and the item is no longer indexed. 
 
Here is a suggested strategy for this item:
   - Move the file listing out of the description.abstract and into a separate text file
   - Upload the text file as a bitstream in the item
   - Reference the text file near the beginning of the shortened (less than 32K) description.abstract field

I didn't do these things for you; these GitHub messages pop up in my home email, but I'm still sort of on vacation.

Typically the indexing will happen automatically after you edit the abstract. Let me know if this works!

**Comment by keithgee** [comment]
I'm noticing, too, that there are already text files in the item that contain file listings. So some of the work in the strategy I suggested above may have already been done. Just make sure the abstract field is not massively long.

**Comment by alawvt** [comment]
I attempted to view the full item record of this item and received an unresponsive script error,

```A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://vtechworks.lib.vt.edu/…mes/vtmirage2/scripts/theme.js:7
```
@keithgee, thank you for troubleshooting this.

I added an item to the Technology to consider an abstract length check in the submission process to prevent this for new items.

**Comment by keithgee** [comment]
Well, that's embarrassing. My mother didn't even get to see that.
I placed a shortened abstract back in now - everything but the file listings - and it's indexed.

I also have problems when I try to view the full item record on that page. I think it is a separate problem and merits a new GitHub ticket.

Also, some of the line endings are being stripped out of the abstract in the display in the short record. Looks like another separate problem, or perhaps we've done that on purpose.

**Comment by mello99** [comment]
Hi @keithgee , thanks so much for looking at that during your vacation and for creating that shortened abstract. I apologize for disturbing you. I'm sick today (sorry if I haven't read everything clearly), but when I'm better I will take the information in that abstract and place it into a ReadMe file; I think that would be a much better strategy. Thank you again for your help, and yours as well, @alawvt , for noting the unresponsive script and adding this to the technology backlog.

**Comment by alawvt** [comment]
@keithgee, DSpace by default, does not display line returns in metadata fields in simple item view or full item view. I agree that it would be good to have this functionality. That way we could eventually move from those pesky HTML <p> tags to hard coded line returns. I have added an item in the Technology backlog to consider this.

**Comment by zhiwuxie** [comment]
Thank you, guys. Now it makes sense. There may be other items buried due to
long descriptions? May be the field needs to have a length limit and have
the form truncate the input? Nothing urgent though.

**Comment by amandafrench** [comment]
Thanks for helping with this, @keithgee! I'm going to close this issue since this particular item is now functioning, but it's good that issues to overly long abstract length are in the product backlog.
