### ISSUE TITLE
Script error when loading full-item-view of large item

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#142]
I attempted to view the full item record of a large item, https://vtechworks.lib.vt.edu/handle/10919/27671?show=full, and received an unresponsive script error,

```
A script on this page may be busy, or it may have stopped responding. 
You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://vtechworks.lib.vt.edu/…mes/vtmirage2/scripts/theme.js:7
```
This was first reported in issue #140.

**Comment by amandafrench** [comment]
This is a Firefox-specific error (it doesn't happen in Safari or Chrome) and is low priority: users could fix it by changing their Firefox settings. It's also highly unlikely to affect many items in VTechWorks, so I'm going to close it.
