### ISSUE TITLE
Draft Moving Image Submission Form Mockup, Draft Moving Image Metadata Elements List

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#147]
Hi @amandafrench  and @alawvt , I have attached the draft versions of the moving image submission form mockup and the moving image metadata element list to this issue. 

The two documents are not completely consistent; to be specific, there are elements in the moving image metadata element list that are not included in the moving image submission form because 1) I wasn't sure whether certain elements should be included in the submission form, and 2) I didn't want to make it too onerous for users to submit moving images (which hopefully I haven't done with the elements I've added to the submission mockup). 

Thanks so much!

[Moving_Image_Metadata_PBCore_DCore.xlsx](https://github.com/VTUL/vtechworks/files/70050/Moving_Image_Metadata_PBCore_DCore.xlsx)

[Moving_Image_Submission_V1.pdf](https://github.com/VTUL/vtechworks/files/70052/Moving_Image_Submission_V1.pdf)

**Comment by alawvt** [comment]
Melissa,

Those are very nice documents. I like your instructions for each field on the submission form. I think that users will find them very helpful.

Thanks,

Anne

**Comment by amandafrench** [comment]
Assigning to @mello99 to create a custom submission template for the Event Capture collection.

**Comment by amandafrench** [comment]
The task to create the mockups and metadata definitions is done: now we just have to create the moving image item custom submission form! Will consider doing that next sprint.

**Comment by amandafrench** [comment]
We can use these documents for the moving image submission form, although @mello99 may have to specify which dc.terms elements the form fields in the mockup refer to.
