### ISSUE TITLE
Request to improve indexing of Computer Science Technical Reports

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#151]
Computer Science Technical Reports, http://vtechworks.lib.vt.edu/handle/10919/19372

Requester:  People reference TRs by number, and thus it is reasonable to expect that someone can find a CS TR by its assigned number.  On the VTechWorks site, the CS TR numbers are not indexed anywhere (yes, they're given in the full details, AFTER you've already found the TR!), so it is nigh impossible to find a TR by searching for its number.  Just as an example, try to find TR 92-56 (this TR number happens to be cited in numerous places).  Even worse, 1992 has 62 TRs, and 92-56 is somewhere in the middle of the long list for 1992, not even near the end! Can someone please fix this?  As currently constituted, the CS TR collection is not very usable.

Reply:  The quick answer is to put the TR number in double quotes, e.g. "TR-92-56". VTechWorks (DSpace) uses SOLR and it probably lists "-" as a word break. I will add this issue to our list of issues to deal with. Hopefully we can improve the list of word breaks, since this is a problem with other searches, too.

Requester:  Yes, using double quotes for searches works, thanks!  The problem is deeper, though, since what we need to see is the TR number listed in all the "summaries" of wild card searches.  Each "item" shows the title, authors, and year, but NOT the TR number.  It's also puzzling that, e.g, the CS TR listing for 1992 is not in any logical order (alphabetical by title, by author, numerical by TR, ?).  NCSTRL (our old TR system) listed everything sorted by TR number --- TR-92-56 precedes TR-93-01 --- which is what one would expect.

**Comment by alawvt** [comment]
A possible (temporary fix) would be add a temporary hint on the advanced search page to use double quotes. More permanently, we might remove other characters from the SOLR word stop list.

We added the TR number to the simple item view for this collection in Pull Request #76. 

The requester would like the TR number displayed in the browse and search results views. 

The search results view is a list with default Sort Order=Relevance. The requester is asking for a default Sort Order=Issue Date Asc. 

With a cursory search, https://wiki.duraspace.org/display/DSDOC5x/XMLUI+Configuration+and+Customization, it looks like these display changes would require overwriting dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/discovery/discovery.xsl and dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/artifactbrowser.item-list.xsl.

**Comment by alawvt** [comment]
The search results could be altered by overwriting dspace/solr/search/conf/schema.xml, line 240

```
<filter class="solr.WordDelimiterFilterFactory" generateWordParts="1" generateNumberParts="1" 
catenateWords="1" catenateNumbers="1" catenateAll="0" splitOnCaseChange="1"/>
```

with `generateNumberParts="0"`. We'd have to think about the implications of this.

Solr Filter Descriptions: Word Delimiter Filter, https://cwiki.apache.org/confluence/display/solr/Filter+Descriptions#FilterDescriptions-WordDelimiterFilter,

```
generateNumberParts: (integer, default 1) If non-zero, 
splits numeric strings at delimiters:"1947-32" ->"1947", "32"
```

**Comment by amandafrench** [comment]
Keeping this issue for indexing only -- assigned to @AmberPoo1

**Comment by amandafrench** [comment]
By the way, I decided not to assign the Browse by Technical Report issue yet: we've given @AmberPoo1 plenty to do. Ditto regarding Kb vs. KB issue! Those are in the backlog if she runs out of things to do.

**Comment by amandafrench** [comment]
This issue is on hold: we can revisit it later.
