### ISSUE TITLE
CSS Multiple browser, different display resolution support problem - e.g. Word-break in full item record view

### ISSUE THREAD

**Issue by AmberPoo1** [VTUL/vtechworks#156]
In the full item record view, word-break works fine in Firefox browser or big screen. But the context of metadata fields may be truncated in other browsers like chrome and Safari, or in smaller windows or PC like surface.
For example, http://vtechworks.lib.vt.edu/handle/10919/49255?show=full
This item has a field "dc.identifier.url", the value is long and without white space: "http://www.plospathogens.org/article/authors/info%3Adoi%2F10.1371%2Fjournal.ppat.1002470".
In firefox, "dc.identifier.url" show word breaks and other fields show correctly:
![screen shot 2016-01-06 at 2 01 05 pm](https://cloud.githubusercontent.com/assets/13734326/12151635/25eea6a8-b47e-11e5-8f53-438d211ca962.png)

However, in chrome, it caused the cut off of other fields and messy display, like this:
![screen shot 2016-01-06 at 1 51 26 pm](https://cloud.githubusercontent.com/assets/13734326/12151669/55c95e22-b47e-11e5-8c94-458310b53533.png)
Similar problem in Safari:
![screen shot 2016-01-06 at 12 59 02 pm](https://cloud.githubusercontent.com/assets/13734326/12151715/7f9a4720-b47e-11e5-9978-dd67b56d267e.png)

**Comment by alawvt** [comment]
I tried a few items in DSpace demo, for example, http://demo.dspace.org/xmlui/handle/10673/608?show=full, and they wrap correctly in a smaller window in Safari. This item in VTechWorks in Safari gets a horizontal scroll bar when the window is shrunk. So it may be something that we have done to the original theme.

**Comment by AmberPoo1** [comment]
Yes, the dspace demo also works fine in Chrome.

**Comment by amandafrench** [comment]
This probably is related to mozkit stuff in CSS: not sure all browsers support it.

**Comment by AmberPoo1** [comment]
I tested our "word-break" css style in "_style.scss", the full item view won't have content overflow problem if I get rid of this css class. So our word-break do support Firefox, but has problems in other browsers.maybe we still need to improve our workd-break class for multiple browsers support in the future.

**Comment by amandafrench** [comment]
Note too that this issue is related to #18, which alters the word-break class. It's not really very high priority, but you can work on it if you like, @AmberPoo1. It's definitely a good thing to contribute to Mirage2 if you can get it sorted.

**Comment by amandafrench** [comment]
Won't contribute to DSpace; involved issue.
