### ISSUE TITLE
Test latest changes on vtechworks.vt.edu since Dec. 1.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#157]
Please test the changes on vtechworks.dev.vt.edu, https://github.com/VTUL/vtechworks/commits/vt_5_x_dev_deploy, since Dec. 1 commit 9d2dc78. You can create a spreadsheet of appropriate tests that we'll repeat on dev, pprd, and production.

**Comment by AmberPoo1** [comment]
A new spreadsheet named "Dspace_5.4_Dec.1_Testing" is created in Google Driver/VTechWorks Team/Testing for this testing.

**Comment by AmberPoo1** [comment]
@alawvt , I have tested all of the changes except this case:  #126 Biomed central doi to identifier doi.
Thanks.

**Comment by alawvt** [comment]
@amandafrench, we have tested the changes on vtechworks.dev. You can request that it be deployed to vtechworks.pprd.

**Comment by amandafrench** [comment]
Will do!

**Comment by amandafrench** [comment]
Have merged changes from dev_deploy branch into branch vt_5_x_pprd_deploy and have asked @kayiwa to deploy to pre-production.

**Comment by kayiwa** [comment]
deployed this. Currently reindexing.

**Comment by alawvt** [comment]
@AmberPoo1, please review this on pprd.

**Comment by AmberPoo1** [comment]
@alawvt, I have finished the test on pprd. The test report is in Google Driver/VTechWorks Team/Testing/Dspace_5.4_Dec.1_Testing.

**Comment by alawvt** [comment]
@AmberPoo1, thank you for testing on pprd.

@amandafrench, you can request that it be deployed to production.

**Comment by amandafrench** [comment]
Will do!

**Comment by alawvt** [comment]
@AmberPoo1, please wait to test; there seems to be an issue.

**Comment by amandafrench** [comment]
Some of the changes seem not to have made it from pre-production to production, notably the Creative Commons license changes in the submission process and the text on the login page (and presumably other pages where messages.xml was changed). See for instance http://vtechworks.pprd.lib.vt.edu/password-login versus http://vtechworks.lib.vt.edu/password-login. Not sure why -- when I get back to my desktop I'll examine the log for the vt_5_x_prod_deploy branch to make sure it's right, but I thought it was.

**Comment by keithgee** [comment]
I'm wondering if the code for #120 was supposed to be deployed, too. I don't see it on production in /dspace/config/crosswalks/sword-swap-ingest.xsl.

The change is in a config directory, by the way, as are other changes you've mentioned. This may be a conversation with @kayiwa  to resolve as part of the production deployment process.

**Comment by keithgee** [comment]
Great release notes @amandafrench !

**Comment by amandafrench** [comment]
This was totes my fault -- I merged all the changes into the prod branch properly and then FORGOT TO PUSH. Ugh. Francis deployed the previously deployed prod_deploy branch!! Have updated the documentation, though, to remind me to push, and @kayiwa has deployed the updated prod_deploy branch to production. Ready for testing -- assigning to @AmberPoo1.

**Comment by AmberPoo1** [comment]
I have tested the latest changes on vtechworks.vt.edu since Dec. 1.

**Comment by amandafrench** [comment]
Great! @AmberPoo1, are you recording test results anywhere? Also, I'm not sure that the "request a copy" configuration is working as it should: I think it is allowing access to restricted material to logged-in users. 

When I test access to restricted items such as http://vtechworks.lib.vt.edu/handle/10919/53688 with hide.me, it does ask users to log in at the item record, but then if I do log in, I can access the bitstream.

**Comment by amandafrench** [comment]
Okay, @alawvt and @AmberPoo1, I've tested by logging in with my non-admin account on a proxy server, and when I do I'm still getting the request form for the above item.

**Comment by alawvt** [comment]
The test results are on Google Driver/VTechWorks Team/Testing/Dspace_5.4_Dec.1_Testing.
I have added a reminder to check the BioMed Central collection for new submissions. @amandafrench will ask @kayiwa to add the request-a-document config change manually.

**Comment by amandafrench** [comment]
Thanks for the testing doc -- I thought that spreadsheet was just the point upgrade test sheet! Closed; I'm holding off on asking @kayiwa to deploy dspace.cfg until we get the GitLab process set up.
