### ISSUE TITLE
Compare configuration files in versions 4 and 5

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#16]
Please compare configuration files (for example, .cfg, .xml) in versions 4 and 5 and list differences. The code for version 4 is in Google Drive Digital Research Services/VTechWorks Team/Technology/vtechworks_dspace4.tar.gz.(Keith: I added the "4" to the file name.)

**Comment by alawvt** [comment]
I am unable to assign Jing to this issue because she is not in the list.

**Comment by amandafrench** [comment]
@alawvt Jing's GitHub userid is @AmberPoo1 :)

**Comment by amandafrench** [comment]
Hi @AmberPoo1, be sure to list the differences on the wiki at https://github.com/VTUL/vtechworks/wiki/Configurations-and-Customizations -- plain text is fine for now; we want to evaluate these before we recreate them.

**Comment by amandafrench** [comment]
Closing -- documentation created on the wiki. Thanks, @AmberPoo1.
