### ISSUE TITLE
VTechWorks database connection error - slots reserved for superuser connections

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#162]
There's an intermittent database related error in VTechWorks that seems to have started happening today. It's hard to reproduce because it's intermittent. I will open a TeamDynamix issue, because it may mean that Tomcat or the database needs to be restarted, and possibly the Postgres configuration tuned. 

ERROR org.dspace.storage.rdbms.DatabaseManager @ SQL getDataSource Error -
java.sql.SQLException: org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
        at org.dspace.storage.rdbms.DataSourceInit.getDatasource(DataSourceInit.java:171)
        at org.dspace.storage.rdbms.DatabaseManager.initDataSource(DatabaseManager.java:1440)
        at org.dspace.storage.rdbms.DatabaseManager.initialize(DatabaseManager.java:1333)
        at org.dspace.storage.rdbms.DatabaseManager.getDataSource(DatabaseManager.java:650)
        at org.dspace.storage.rdbms.DatabaseManager.getConnection(DatabaseManager.java:629)

**Comment by keithgee** [comment]
I opened TeamDynamix request 1248760. I think I opened it in the "don't page anybody on Friday night just to fix this" queue.

**Comment by kayiwa** [comment]
restarted the postgres DB server. Let me know if this persists. Nagios had been reporting this for a while but I was ignoring it until I saw your report. I planned to kick it back on my AM checkups. 
<img width="864" alt="screen shot 2016-01-08 at 10 22 46 pm" src="https://cloud.githubusercontent.com/assets/685884/12214125/8a8214c2-b656-11e5-8642-aae3b103a466.png">

**Comment by mello99** [comment]
You're probably aware of this, but the Handle server is down. Apologies if this is redundant information; I just wasn't sure if this was part and parcel of the restart process. Thanks so much everyone.

**Comment by keithgee** [comment]
Thanks @kayiwa. This hasn't happened again after you restarted the database server on Friday. Closing.
