### ISSUE TITLE
Can we accept new VTW submissions? (not sure how much to avoid meddling with DSpace)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#163]
Hi @keithgee , I know we want to limit our activities with VTechWorks during this sensitive time, but is it permissible to accept items that faculty, staff, and students have submitted to VTechWorks? These items (well, just one item) are waiting in the submission queue for approval. I just wasn't sure if I should wait or not. 

Also, can we create individual uploads via the web form (NO spreadsheets)? I ask because a researcher just submitted a file to be uploaded to VTechWorks (she hasn't created metadata for it or submitted it to any collections). Thanks again, and no rush on this.

**Comment by keithgee** [comment]
Melissa, that's up to you. Last week Amanda was exploring, with Francis and Aaron, the option of reverting the database and file system to an earlier date, which as a side-effect would cause new work to be lost. 

I feel like we're cleaning everything up without needing to do that, so if you want to accept or add new items and can still keep track of everything, that's fine with me.
Closing.

**Comment by amandafrench** [comment]
Yes, @mello99 & @keithgee, we can accept new items -- they'll be fine. Agree that we're cleaning it up without needing to roll back the database, so new work will be fine.
