### ISSUE TITLE
Incorrect metadata element in the "dcterms" registry ("dcterms.comformsTo")

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#164]
Hi all, while I was updating the metadata documentation to include elements from the "dcterms" namespace, I noticed that one of the "dcterms" elements is incorrectly entered in the DSpace Registry. To be specific, element 122, "dcterms.comformsTo", should be "dcterms.conformsTo" (http://purl.org/dc/terms/conformsTo). I've added "dcterms.conformsTo" (173) to DSpace's "dcterms" registry, but I've yet to delete "dcterms.comformsTo" because I'm not sure how this deletion might affect crosswalks and harvesting. I just wanted to mention this; it's something I'll keep an eye on.

**Comment by alawvt** [comment]
@mello99, thank you for discovering and reporting this.

@AmberPoo1, please correct this in dspace/config/registries/dcterms-types.xml, ~line 95. Since it is incorrect in the main DSpace project, please submit a pull request there, as well.

**Comment by mello99** [comment]
Hi @alawvt , thanks for taking action on this!

**Comment by alawvt** [comment]
@AmberPoo1, please contribute this to DSpace.

**Comment by AmberPoo1** [comment]
Have contributed this change to Core DSpace.
1. Relevant ticket in the DSpace Issue Tracker:
https://jira.duraspace.org/browse/DS-2998?filter=-2&jql=ORDER%20BY%20createdDate%20DESC
1. Add comments in the "metadata registries" parts of  both DSpace 5.x and 6.x documentation:
   https://wiki.duraspace.org/display/DSDOC5x/Metadata+and+Bitstream+Format+Registries
   https://wiki.duraspace.org/display/DSDOC6x/Metadata+and+Bitstream+Format+Registries
2. Create a pull request in Core Dspace Master Branch.
   https://github.com/DSpace/DSpace/pull/1245

**Comment by amandafrench** [comment]
Thanks, @AmberPoo1! And @mello99!
