### ISSUE TITLE
DSpace can now upload large files (~ 5 GB)?

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#165]
When did this become possible? I remember a few weeks to a month ago that I couldn't upload anything larger than 2 GB, and I tried uploading files using more than one machine. @keithgee , do you know why this has happened? If you did something to make it happen, great work! Thanks, everyone.

**Comment by amandafrench** [comment]
Assigning @keithgee just to answer the question, really, not to do anything about it.

**Comment by amandafrench** [comment]
Maybe ask @keithgee this question on Wed at the standup, @mello99.
