### ISSUE TITLE
Issue with VTW Login Page ("The file is restricted")

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#167]
Hi all, I signed-in to VTechWorks today (the snow is starting to melt, yay!) and noticed that the login page has changed. In short, the VTW login page read "The file is restricted" at the top, and displayed the boxes for one's username and password at the bottom (see image below). I'd like to note that I wasn't looking at another item when I decided to log-in and that I also cleared my browser cache (cookies, passwords, and all). 

![screen shot 2016-01-24 at 3 58 48 pm](https://cloud.githubusercontent.com/assets/5408616/12538881/64671ac6-c2b3-11e5-9970-e206abb76196.png)

When I did log-in, I was directed to this item's thumbnail- http://vtechworks.lib.vt.edu/bitstream/handle/10919/64494/LD5655.V853_1944.R623.pdf.jpg?sequence=3&isAllowed=n

![screen shot 2016-01-24 at 4 00 34 pm](https://cloud.githubusercontent.com/assets/5408616/12538896/a030cbd8-c2b3-11e5-8199-f40160c2ba58.png)

I have no idea why this happened, so I thought I'd mention it. I hope that everyone has safely and successfully dug themselves out of the snow - take care.

**Comment by mello99** [comment]
Ok, I'm going to close this issue because I logged-in again and didn't encounter this problem. I still think that DSpace is playing games with me, but perhaps I'd looked at that item the last time I logged-in. If someone else encounters this, we can re-open the issue.

**Comment by amandafrench** [comment]
Hi @mello99 -- yes, weird. If the above screenshot had the URL in it we might be able to troubleshoot more: are you certain you were on the page https://vtechworks.lib.vt.edu/password-login ? So far on all three servers it seems to be okay. 

But I too have sometimes had weird issues with being redirected to the thumbnail after logging in or re-logging in on an item page -- not sure why I haven't reported it as an issue, actually, except that I'm used to redirect / session errors, and it's easy to just hit the Home button and navigate back to the item again. Will try to document it better next time it happens.

**Comment by alawvt** [comment]
I have experienced the thumbnail issue, too. I'll try to document it when it occurs next.

**Comment by keithgee** [comment]
I've also seen this, going way back to work at OhioLink from 2007-2009. It seems to be triggered by thumbnails with access restrictions (though it's still a bug).
