### ISSUE TITLE
Enable html in title in the search view

### ISSUE THREAD

**Issue by AmberPoo1** [VTUL/vtechworks#168]
Html has been enabled in the simple/full item view. In the search results, It is hard to enable html in the abstract field (The content of this filed may come from different sources, e.g., from the metadata filed "abstract", like item "Enable HTML in all fields, <i>e.g., abstract, title and subject</i> "; or from the content of attached files, like item "XML for ETDs"). But at least we can enable it in the titles of search result.

![screen shot 2016-01-25 at 3 18 44 pm](https://cloud.githubusercontent.com/assets/13734326/12563186/f8ec5f1c-c376-11e5-8882-1761ed8b45c5.png)

Relevant item links:
http://vtechworks.pprd.lib.vt.edu/handle/10919/20115
http://vtechworks.pprd.lib.vt.edu/handle/123456789/64469

**Comment by amandafrench** [comment]
This is finished and deployed, correct? Closing, but reopen, @AmberPoo1, if I'm wrong.

**Comment by AmberPoo1** [comment]
@amandafrench, title in the search view hasn't been enabled yet. Html is enabled in browser view and item view.
