### ISSUE TITLE
Add additional search filters

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#17]
Please create the search filters that were available in VTechWorks version 4. The patches used for version 4 are in Google Drive Digital Research Services/VTechWorks Team/Technology/vtechworks_dspace4_patches_search_filters, https://drive.google.com/a/vt.edu/folderview?id=0B0VhWgQOPYz8fnJPdFdqWTcwZURWd2NsVkxYcVpvLW9jMzVIOThoWFZ2QlVFM29UZFAteU0&usp=sharing.

**Comment by alawvt** [comment]
The list of filters should contain

Title
Author
Subject
Date Issued
Content Type
Abstract
Keyword
Series
Identifier
Mime-Type
Coverage
Sponsor
Language (ISO)
Technical Report No.
Department
ETD Advisor
ETD Level 

Please see https://redmine.lib.vt.edu/projects/vtechworks-projects/wiki/VTechWorks_search_configuration, for details of configuration in VTechWorks_dspace4.

**Comment by alawvt** [comment]
This list of search filters/facets has been added with pull request #47.

**Comment by keithgee** [comment]
Verified that pull request #50 includes the above list of filters, except for keyword, which was purposely removed by @alawvt.

Closing.
