### ISSUE TITLE
Item contains an invalid XML file

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#170]
ETD https://vtechworks.lib.vt.edu/handle/10919/25142 contains a supporting bitstream, https://vtechworks.lib.vt.edu/bitstream/handle/10919/25142/Deshpande_SG_D_2014_support_3.xml?sequence=2&isAllowed=y, that is a malformed XML file. When one clicks on it in Firefox, it yields the error,

![malformedxml](https://cloud.githubusercontent.com/assets/13037168/12595936/d6f7a71a-c44b-11e5-9133-1460647e0d64.png)

We don't check that content files are well formed XML. Therefore, I wonder if we can enable the user to download a file like this without getting the error message.

**Comment by amandafrench** [comment]
Noted in the backlog: closing for now.
