### ISSUE TITLE
Custom Submission Form - Audiovisual Resources

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#173]
Hi @AmberPoo1 , during our recent sprint planning meeting @amandafrench discussed giving you the task of creating a custom submission form for audiovisual materials (videos, for the most part). The mockup of the form is in the [custom submissions folder on Google Drive](https://drive.google.com/open?id=0B0VhWgQOPYz8U2dhYlctSHFNbkk) - it's entitled [Moving_Image_Sub_Mockup_V1.pdf](https://drive.google.com/open?id=0B7IH56M-y5-lWnNPLVUwa0hYMlU). I'm sure @alawvt and @amandafrench can give you more info on the task itself, but I'll be happy to answer any questions you have about the mockup. Thanks!

**Comment by alawvt** [comment]
This will be a modification of the default "traditional" submission form with a "type-bind" for moving image. The submitter will see all the default submission form questions on the first page. It they select type=moving image, then they will see questions specific to moving images on the next page(s).

**Comment by amandafrench** [comment]
See also #147

**Comment by mello99** [comment]
Hi @AmberPoo1 and @alawvt , I've created a mapping from the MovingImage Submission Form elements to the DSpace (Dublin Core) elements; [it can be found in Google Drive](https://drive.google.com/open?id=1WK4kKDcRLghNQihKFHfJSBWzzRUe0G9l839cef2F1mw) (in both the "Metadata" and "Custom Submission Forms" folders). Feel free to ask questions or make comments, and take care.

**Comment by alawvt** [comment]
@mello99, thank you for the mapping. 

@AmberPoo1, we will wait to implement this until after the default custom submission form issue and the Sherpa Romeo issue are resolved.. 

I have added the mapping to the MovingImageCustomSubmissionForm "form fields" sheet. I have separated out the fields that would be in the default section of the form with those that are moving image specific. I have added comments to highlight differences in the language between the existing form and @mello99's recommendations for moving images, as well as some questions. To implement the Rights Statement field, I have created the value-pairs list, common_rights, which is on the "value-pairs" sheet.

**Comment by amandafrench** [comment]
MovingImageCustomSubmission is at https://docs.google.com/spreadsheets/d/1hIx4Tfn-z0dXFwOHTM5uqcp2_FVwwrYVdkcVTAWc50U/edit#gid=523580844

**Comment by alawvt** [comment]
https://wiki.duraspace.org/display/DSDOC5x/Submission+User+Interface#SubmissionUserInterface-ItemtypeBasedMetadataCollection

**Comment by amandafrench** [comment]
Closing until next sprint or later ...

**Comment by alawvt** [comment]
resolved with PR #326.
