### ISSUE TITLE
Pilot deposit of VTechWorks content into DPN via DuraCloud

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#176]
More of a project than an issue, but will track here.

**Comment by keithgee** [comment]
It seems that DPN leadership is suggesting we use APTrust to do DPN deposits, so I will start by doing one test deposit of one file and then we'll go from there.

**Comment by amandafrench** [comment]
This is on hold: @keithgee will talk to Nathan about various issues.
