### ISSUE TITLE
In full record display, please fix abstract display so lines don't break mid-word (contribute to DSpace)

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#18]
In full record display, lines are breaking mid-word, for example dc.description.abstract for http://vtechworks.lib.vt.edu/handle/10919/48142?show=full. Please change so that lines break only between words.

**Comment by amandafrench** [comment]
Broken:

![screenshot 2015-10-30 19 02 23](https://cloud.githubusercontent.com/assets/227453/10860058/07edf3b2-7f3a-11e5-80a8-55b0397c8e4c.png)

Fixed: 

![screenshot 2015-10-30 19 01 56](https://cloud.githubusercontent.com/assets/227453/10860066/150e76a2-7f3a-11e5-8577-bb41e2851186.png)

**Comment by alawvt** [comment]
Thank you--much improved!

**Comment by AmberPoo1** [comment]
@amandafrench , @alawvt , this problem is caused by the long text without space of "dc.identifier.url" field in full item view, we should add auto line break if this kinod of text is too long. The style of abstract is correct.

**Comment by amandafrench** [comment]
@AmberPoo1 -- assigning you to contribute this to dspacecore! There might be conflicts with other changes to the CSS, though. See commits https://github.com/VTUL/vtechworks/commit/0b94ad48c9c8a22e6eaa033597b35fbbcb0feebf and https://github.com/VTUL/vtechworks/commit/4efb84202fc6aff9e6c16bbf6e108bfdd963806c for code changes.

**Comment by amandafrench** [comment]
FYI, @AmberPoo1 and @alawvt, the issue I created for this in DSpace Jira is https://jira.duraspace.org/browse/DS-2963

**Comment by amandafrench** [comment]
Please note that this issue is fixed; like all of the issues labeled "dspacecore," it's just open until we figure out a workflow for contributing it to DSpace core.
