### ISSUE TITLE
Implement Altmetrics badges

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#181]
For documentation, see the following pages: 
-  http://www.altmetric.com/products/free-tools/institutional-repository-badges/ 
- https://help.altmetric.com/support/solutions/articles/6000086842-getting-started-with-altmetric-on-your-journal-or-institutional-repository 
- http://api.altmetric.com/embeds.html 

I have already written altmetric to let them know to start tracking us once we add the embed code. I'd like the following options: 
- Badge type = medium badge (or small badge if that looks better) 
- Condensed style = false
- Popover = none
- Details = right 
- Hide no mentions? = false
- Hide if score less than = null 

Sample code: 

`<div data-badge-details="right" data-badge-type="2" data-doi="10.1038/nature.2014.14583" class="altmetric-embed"></div>`

I'd like the badge to show up on BOTH simple item view and full item view at the bottom of the page; not sure which file(s) the badge goes in or what options we might have for where to put it -- do what looks best. Doesn't need to show up in search results.

**Comment by alawvt** [comment]
Most(?) of our DOI are in the dc.identifier.doi field. Some start with "http://dx.doi.org" but some start with "doi" or "10.1" The [Wikipedia article about DOI's](https://en.wikipedia.org/wiki/Digital_object_identifier) give more details about the format of DOIs.

**Comment by alawvt** [comment]
There is some discussion of Altmetric badges on the [DSpace Tech Support listserv](http://dspace.2283337.n4.nabble.com/template/NamlServlet.jtp?macro=search_page&node=3276944&query=altmetric&n=3276944).

Specific threads
[Putting Altmetric code or enabling Altmetric on DSpace](http://dspace.2283337.n4.nabble.com/Putting-Altmetric-code-or-enabling-Altmetric-on-DSpace-td4680868.html)

[Altmetrics and DSpace how to add?](http://dspace.2283337.n4.nabble.com/Altmetrics-and-DSpace-how-to-add-tt4678559.html)

**Comment by AmberPoo1** [comment]
According to Altmetric API documents, we can try to use "data-handle" attribute to specify the url, the value is from "citation_abstract_html_url" head meta element, whose value is the handle url, e.g. "http://hdl.handle.net/10919/49255".
Add code like this:
`<div class="altmetric-embed" data-handle="10919/49255"></div>`

We can test if it will work.

**Comment by alawvt** [comment]
That sounds good, @AmberPoo1.

**Comment by alawvt** [comment]
According to http://wiki.lib.sun.ac.za/index.php/SUNScholar/Altmetrics, 
"The Altmetrics feature in DSpace needs to consult an external database when doing social metric lookups. Therefore you MUST ensure that your repository server has unrestricted access via ports 80 and 443 to the following web site:" `http://api.altmetric.com`

@amandafrench, are we ok for this?
