### ISSUE TITLE
Test emu sprint changes

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#182]
The emu sprint changes (from January) have been deployed to development by the intrepid @kayiwa. Please test. I drafted release notes at https://github.com/VTUL/vtechworks/releases, though since they're just a draft I'm not sure if you can see them. Let me know if it would be helpful to publish them, though I'm inclined not to until they go to production.

**Comment by alawvt** [comment]
I have tested these changes on vtechworks.dev. The testing spreadsheet is in Google Drive/VTechWorks Team/Testing/Dspace_5.4_Jan_7_Feb_1_Emu_Testing. 

@amandafrench, you can deploy it to pprd.

**Comment by alawvt** [comment]
@AmberPoo1, please test these changes on vtechworks.pprd.vt.edu.

**Comment by AmberPoo1** [comment]
@amandafrench , @alawvt , @mello99 , It still shows "dcterms.comformsTo" on vtechworks.pprd.vt.edu, while on vtechworks.dev.vt.edu this dcterm has been corrected. 
Other emu sprint changes has been tested and passed on our pprd. Test details can be found in the spreadsheet "Test on vtechworks.pprd" in  Google Drive/VTechWorks Team/Testing/Dspace_5.4_Jan_7_Feb_1_Emu_Testing.

**Comment by alawvt** [comment]
@AmberPoo1, thank you for testing. I have corrected the metadata registry, so testing on pprd is complete.
@amandafrench, theses changes are ready to deploy to production.

**Comment by amandafrench** [comment]
I've merged to the production branch and have emailed @kayiwa.

**Comment by alawvt** [comment]
@AmberPoo1, the emu changes have made it to production. Please test them on vtechworks.lib.vt.edu. Thanks.

**Comment by AmberPoo1** [comment]
Emu changes have been tested and passed on vtechworks.lib.vt.edu. Test results are in the spreadsheet "Test on vtechworks.lib.vt.edu" in Google Drive/VTechWorks Team/Testing/Dspace_5.4_Jan_7_Feb_1_Emu_Testing.

**Comment by alawvt** [comment]
@AmberPoo1, thank you.
