### ISSUE TITLE
Fix Sherpa/Romeo gray.submission error and contribute to DSpace

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#183]
When a journal's policies are unknown to SHERPA / RoMEO, the Mirage2 theme classifies it as "gray." However, there are no gray messages in messages.xml and no gray class defined in the Mirage2 CSS. Good candidate for contributing to DSpace core when fixed.

**Comment by AmberPoo1** [comment]
@amandafrench , I tested with an SHERPA/RoMEO unknow journal whose issn is "1674-1633".
gray message didn't show, the page only showed "To learn whether your journal or publisher allows you to deposit a version of your published work in this institutional repository, please consult the comprehensive SHERPA/RoMEO database of publisher copyright and self-archiving policies."
![screen shot 2016-02-07 at 5 30 28 pm](https://cloud.githubusercontent.com/assets/13734326/12875832/b40a6840-cdc0-11e5-9c90-70b4e286a961.png)

**Comment by alawvt** [comment]
When I searched directly in SHERPA/RoMEO for ISSN=1674-1633, the result was `No journals found when searched for: 1674-1633`
When I submitted an article with that ISSN, this was the file submission screen,
![sherparomeoissnsubmissionnotinsr](https://cloud.githubusercontent.com/assets/13037168/12891418/dff4e9fe-ce55-11e5-8a90-e14a5dc402fc.png)

When I submitted an article with an ISSN that is in SHERPA/RoMEO, this was the file submission screen,
![sherparomeoissnsubmissioninsr](https://cloud.githubusercontent.com/assets/13037168/12891339/78840322-ce55-11e5-961e-77a92660a3d8.png)

_Victorian Poetry_ (ISSN=0042-5206) is a RoMEO ungraded journal.
When I submitted an article with this ISSN that is ungraded
![sherparomeoissnsubmissionungradedinsr](https://cloud.githubusercontent.com/assets/13037168/12891777/128e9e40-ce57-11e5-936e-40a7ebd6e0ea.png)

We'll have to test the PR for an ungraded journal, such as _Victorian Poetry_.

**Comment by amandafrench** [comment]
Thanks for the screenshots, @alawvt -- was just going to put those here.

**Comment by alawvt** [comment]
@AmberPoo1, please submit this to DSpace core.

**Comment by AmberPoo1** [comment]
Have contributed this change to Core Dspace.
1. Relevant ticket in the DSpace Issue Tracker ():
   DSpace / DS-3085   "Sherpa/Romeo ungraded journal (gray) shows error" 
   
   https://jira.duraspace.org/browse/DS-3085
2. Create a pull request in Core Dspace Master Branch.
   DSpace/DSpace #1324 
   Correct Sherpa/Romeo ungraded journal (gray) error message 
   
   https://github.com/DSpace/DSpace/pull/1324

**Comment by alawvt** [comment]
Thanks, @AmberPoo1.
