### ISSUE TITLE
Metadata guidelines PDF

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#185]
Hi @alawvt and @amandafrench , attached is a new PDF of the metadata guidelines. If I publish the guidelines as a PDF via Google Drive, Google Drive automatically formats the PDF, so there's not much I can do. If I export the PDF, then add it to the web and link to it, I can make some changes. The thing is, I'm not sure which changes you'd like me to make; the chart is quite large, so it won't look aesthetically pleasing unless I get rid of some of the columns (maybe I can get rid of the "Element Definition Source" column and add the citations at the bottom?). Anyways, here's the chart; if you have any specific suggestions, that would be great. Thanks!

P.S. - I think we should come up with some sort of versioning policy for our metadata guidelines. Right now I added "Version 1.0", but I think we should consider something more systematic (I added metadata versioning to the backlog).

[2015_12_14_VTechWorks_Metadata_Guidelines_Magnified.pdf](https://github.com/VTUL/vtechworks/files/114598/2015_12_14_VTechWorks_Metadata_Guidelines_Magnified.pdf)

**Comment by alawvt** [comment]
@mello99, that's so much easier to read --thank you!

**Comment by amandafrench** [comment]
Thanks, @mello99! All done!
