### ISSUE TITLE
In the submission form, change the messages for the name and series input-types

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#188]
In the submission forms, change the messages for the name input-type.

name – Personal name, with separate fields for family name and first name. When saved they are appended in the format 'LastName, FirstName'

current messages are 

Left box: Last name, _e.g. Smith_ 
Right box: First name(s) + "Jr", _e.g. Donald Jr_

change messages to 

Left box: Last name, _e.g., Kennedy_ 
Right box: First name(s) and Middle Initial(s), _e.g., John F. Jr._  

Changes can be overlaid in dspace/modules/xmlui/src/main/webapp/i18n/messages.xml 

@amandafrench, please verify.

**Comment by amandafrench** [comment]
New one for the first name (right box) should be as follows: 

`First name(s) and Middle Initial(s), e.g., John F. Jr.` 

Italics are fine, but not essential -- either way. Otherwise looks good. I know it doesn't make sense, but it's approved practice. :)  Right, @mello99?

**Comment by mello99** [comment]
Yes, that's how we want things to look. Just to add, there's often a comma inserted between the middle initial and the name suffix. For example, if you look at William F. Buckley, Jr.'s entry in [VIAF](http://viaf.org/viaf/73943799), there's a comma. Same with [Cuba Gooding, Jr.](http://viaf.org/viaf/85825053), [Martin Luther King, Jr.](http://viaf.org/viaf/100170140), and [Robert Downey, Jr.](http://viaf.org/viaf/19879171) Be sure to look at the forms of the name with the US flag next to them; that's how the names are encoded in the National Authority File, which is what we follow.

**Comment by alawvt** [comment]
@amandafrench and @mello99, thank you for the review. I have updated the first post with jr.

**Comment by alawvt** [comment]
In the submission forms, change the messages for the series input-type.

series – Series/Report name and number. Separate fields are provided for series name and series number, but they are appended (with a semicolon between) when saved.

current messages are

Left box: Series Name
Right box: Report or paper No.

change messages to

Left box: Series name, _e.g., NSTSCE_
Right box: Report or paper number, _e.g., 16-UO-042_

Changes can be overlaid in dspace/modules/xmlui/src/main/webapp/i18n/messages.xml

@amandafrench, please verify

**Comment by alawvt** [comment]
To get the first name message on one line, I had to shorten it to,

First name(s) + initial(s), e.g., John F. Jr.
