### ISSUE TITLE
Request to remove "Select a community to browse its collections" from home page

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#19]

**Comment by keithgee** [comment]
Implemented with commit c5c2fad6fa9ebf2f4b2, which removes the text from the home page and the community list page.

**Comment by alawvt** [comment]
Please redo this change as an overlay, rather than a change to the original code. This will make migration of our customizations much easier. Please copy dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/CommunityBrowser.java
to dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/CommunityBrowser.java and
remove the customizations from dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/CommunityBrowser.java.
