### ISSUE TITLE
Delete old upstream branches?

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#191]
There seem to be some old branches hanging around, e.g., the one for adding the off-campus sign-in link. The instructions at https://github.com/VTUL/vtechworks/wiki/6.-Pushing-changes-to-Github do say to delete the _local_ branch after everything has been merged (and I suppose deployed), but should we do some cleanup of the upstream branches, i.e., the ones on GitHub? At some point there will be so many that we'll have to get rid of some of them, but should we wait longer until we reach that point? What does GitFlow say?

**Comment by alawvt** [comment]
@amandafrench, Thanks for pointing these out. I deleted some of these merged branches. I will leave aschweer_query_escaping_fix and mobile_video_fixes for @keithgee to handle. date-issued-desc was not merged, so I think we should keep it for future work. You merged configure-submission; is it something that you could decide on? The other branches are current.

**Comment by alawvt** [comment]
@amandafrench, I see in #105, that configure-submission is your current submission form branch.

**Comment by amandafrench** [comment]
Yes, please don't delete configure-submission -- if you @alawvt or @AmberPoo1 like, you can pull that branch and work from it. Will close this issue.
