### ISSUE TITLE
VT EZ-Proxy Users Cannot View Restricted Items

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#197]
Hi @kayiwa , @amandafrench , @keithgee , and @alawvt , I received an email from a VT user who was unable to access an ETD from off-campus using EZ-Proxy. I signed-in to EZ-Proxy using my personal VPN and was also unable to access the ETD; this has been the case for all of the ETDs I've looked at since I was notified of this issue. There are no issues with the ETDs' authorizations; they are correctly set to "VT Campus" and I am able to view them using my networked desktop computer (I'm not signed-in to VTechWorks when I do this, by the way).

I've put in a TeamDynamix request and Aaron H. is looking into this issue; below is a screenshot of the message that I get when I'm signed-in to EZ-Proxy and attempt to look at a campus-only ETD (note that the "Off Campus Sign In" button reads "You Are Signed In"): 

<img width="1231" alt="screen shot 2016-02-09 at 5 14 57 pm" src="https://cloud.githubusercontent.com/assets/5408616/12932649/b9f0ea08-cf51-11e5-8362-cfd28302477d.png">

Thanks, everyone.

**Comment by keithgee** [comment]
I was asked by Aaron to check that IP address of 198.82.230.35 was whitelisted in our ip-config. It is, however the EZ-Proxied users are being seen with the 192.168.2.81 IP address.
I've let Aaron know on the chat.

**Comment by alawvt** [comment]
He said it was an issue with the F5 appliance and that he was working on a fix.
