### ISSUE TITLE
OAI-PMH harvest search by date returns error

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#20]
The request, https://vtechworks.lib.vt.edu/oai/request?verb=ListRecords&metadataPrefix=oai_dc&from=2015-08-20, produces the error, "invalid date given in until parameter." There is mention of a similar error in the DSpace issue, https://jira.duraspace.org/browse/DS-2542.

**Comment by keithgee** [comment]
I think we probably shouldn't spend time on this issue here, unless it is hurting us in some way.

**Comment by keithgee** [comment]
What I mean is:  we'll have a lot of other issues and I'd be happy to make this a low priority unless it's interfering with one of our current processes or workflows.

**Comment by alawvt** [comment]
I agree, I can live without it. I did want to note it, though.

**Comment by amandafrench** [comment]
@alawvt @keithgee Definitely, note all issues here -- really all the issues we're putting here are for revisiting later. On Monday (I hope, assuming we've gotten outstanding issues from the server move resolved) we will decide what to work on in the next sprint. We'll mark those with the "current sprint" lavel. I'm going to reopen these two but mark them to revisit later.

**Comment by amandafrench** [comment]
We are working on this with Francis over on GitLab (which I hope we can soon clean up and close out!), so I will indeed close this here.

**Comment by keithgee** [comment]
This is fixed in DSpace 5.4, which is merged into our codebase but not yet deployed.
See the update at the bottom of the aforementioned page at https://jira.duraspace.org/browse/DS-2542

Closing.
