### ISSUE TITLE
Items uploaded via CSV import (2/16/2016) don't show up in search

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#203]
Hi, everyone, I was mentally prepping myself for the backlog meeting today and thought about the Open Access Subvention Fund articles that I uploaded to VTW last week (yes, I know it's late at night, but if I didn't add this issue now I'd completely forget about it).

In short, I uploaded 25 articles using the "Import Metadata" functionality and then added the article files manually. The items are in VTW and can be accessed via their handles (I get to them via my "Submissions" page), but they don't show up in search. I just thought I'd bring this up since it's been almost a week since I've uploaded them. Below is a list of the offending items; with my luck they'll probably be searchable in the morning. Thanks, everyone!

http://hdl.handle.net/10919/64832
http://hdl.handle.net/10919/64831
http://hdl.handle.net/10919/64829
http://hdl.handle.net/10919/64830
http://hdl.handle.net/10919/64825
http://hdl.handle.net/10919/64826
http://hdl.handle.net/10919/64828
http://hdl.handle.net/10919/64824
http://hdl.handle.net/10919/64827
http://hdl.handle.net/10919/64823
http://hdl.handle.net/10919/64821
http://hdl.handle.net/10919/64820
http://hdl.handle.net/10919/64822
http://hdl.handle.net/10919/64818
http://hdl.handle.net/10919/64819
http://hdl.handle.net/10919/64816
http://hdl.handle.net/10919/64815
http://hdl.handle.net/10919/64817
http://hdl.handle.net/10919/64814
http://hdl.handle.net/10919/64813
http://hdl.handle.net/10919/64811
http://hdl.handle.net/10919/64812
http://hdl.handle.net/10919/64810
http://hdl.handle.net/10919/64809
http://hdl.handle.net/10919/64808

**Comment by alawvt** [comment]
@mello99, as you predicted, I just searched for two authors and both items were in the search results.

**Comment by amandafrench** [comment]
I just searched for keywords in the title of 64819 (Phosphorylation collective) and found it as well. I also tried it using an off-campus proxy, just in case, and that worked too, so I guess I'll close the issue!
