### ISSUE TITLE
Test frog sprint changes on vtechworks.lib.vt.edu

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#204]
The frog sprint changes (from January) have been deployed to development. Please test. There are release notes at https://github.com/VTUL/vtechworks/releases.

**Comment by AmberPoo1** [comment]
@keithgee, @alawvt , @amandafrench , The test sheet has been created in Google Drive/VTechWorks Team/Testing/Dspace_5.4_Feb_Frog_Sprint_Testing.
I have tested all changes on vtechworks.dev expect this item: "Added more IP addresses as authentic Virginia Tech IPs".

And the Altmetrics badges show too close to the above row, should add some space between two rows. 
I have created a related issue: #206
![screen shot 2016-02-25 at 12 31 49 pm](https://cloud.githubusercontent.com/assets/13734326/13328302/daa224a8-dbbb-11e5-9427-9e80f8d063cc.png)

**Comment by amandafrench** [comment]
These changes are ready to go -- #206 was resolved in commit 39aec0922e9ef20a8ed87891f7ea123712eaaa7c -- so I will move the changes to pprd_deploy.

**Comment by alawvt** [comment]
@AmberPoo1, please test these changes on pprd. The Almetrics badge padding commit won't be pushed until the next testing cycle.  Thanks.

**Comment by AmberPoo1** [comment]
I have tested all changes on vtechworks.pprd expect "Added more IP addresses as authentic Virginia Tech IPs". item. According test report has been created in Google Drive/VTechWorks Team/Testing/Dspace_5.4_Feb_Frog_Sprint_Testing/Test on vtechworks.pprd.

**Comment by alawvt** [comment]
@AmberPoo1, thank you for testing.
@amandafrench, these changes are ready for production. We'll hold until you deploy the Altmetric commits to dev and pprd before proceeding to production.

**Comment by alawvt** [comment]
@amandafrench, I see the padding change on dev and it looks fine. You can push those changes to pprd. You could move the whole lot to production to test next week or wait until the following week.

**Comment by amandafrench** [comment]
Might as well get them to prod today if we can: I'll create both pprd and prod branches today and ask @kayiwa if he can get them out before C4L.

**Comment by alawvt** [comment]
@AmberPoo1, please add the additional Altmetrics commits to the frog testing spreadsheet and test all these changes on production.

**Comment by AmberPoo1** [comment]
Have tested these new changes expect for the "Added more IP addresses as authentic Virginia Tech IPs" on production, and the test results are in "Google Drive/VTechWorks Team/Testing/Dspace_5.4_Feb_Frog_Sprint_Testing/Test on vtechworks.lib.vt.edu".

**Comment by alawvt** [comment]
@AmberPoo1, thank you for testing the frog changes.

I added an item to the Technology Backlog to investigate improving the Altmetric results.
