### ISSUE TITLE
Test Shibboleth on development

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#209]
Test Shibboleth login on development server

**Comment by amandafrench** [comment]
Hi @alawvt, @AmberPoo1, and @mello99 -- if you get a chance, can you test the Shibboleth login on dev now that it's back up?  You will almost certainly need to set or reset your PID and password on the middleware pprd server first: I will email you all the link that will let you do that.

**Comment by amandafrench** [comment]
I did get a PID & pwd on middleware pprd today and tested, and all works very well! (In Firefox.) Even better than expected, in fact. I can log in with both my PID via the Shib link and with my existing VTW login and pwd, with no error message, which is great. Means I don't have to choose.

**Comment by amandafrench** [comment]
This did used to work, but today I'm getting an "Authentication Failed" message. 
![screenshot 2016-03-09 12 37 26](https://cloud.githubusercontent.com/assets/227453/13644435/c9994faa-e5f3-11e5-8e53-f742c982d843.png)

**Comment by alawvt** [comment]
No response yet trying to reset middleware password.

**Comment by alawvt** [comment]
My password was reset and I changed it successfully. I tried to log in to vtechworks.dev and saw the same "Authentication Failed" screen. I filed a TD request.

**Comment by alawvt** [comment]
Waiting on ITS to reconfigure DSpace and Shibboleth.

**Comment by alawvt** [comment]
@amandafrench, ITS has reconfigured DSpace and Shibboleth. I am now able to log into vtechworks.dev with Shibboleth.

**Comment by keithgee** [comment]
We want to make sure that IP Authentication stuff still works even after Shibboleth has been turned on, too.

**Comment by amandafrench** [comment]
I'll test this tonight from home. I never quite trust the proxy servers when it comes to IP authentication.

**Comment by amandafrench** [comment]
Whoops, I forgot, one can't test on development when off-campus. But I need to clarify, @keithgee: is it that you want to make sure that IP address-based restriction of certain items still functions when Shibboleth is implemented? I think we will have to wait until Shib moves to production to test that.

**Comment by keithgee** [comment]
Yes, that's helpful.

It was partly because on some of our systems (production for example), we
weren't using Apache httpd in the request chain, but needed to enable it
for Shibboleth.

Aaron changed production on Tuesday so that all requests go through Apache
httpd now, and IP restriction was still working, so it may not be a problem.

But definitely test when Shibboleth is installed, too.

**Comment by amandafrench** [comment]
I'm going to close this issue for now, since Shibboleth login is currently working on <strike>production</strike> development. I'll add a reminder to the backlog to test restricted item IP authentication whenever Shib moves to production.
