### ISSUE TITLE
Font has insufficient contrast 

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#21]
color is #7f7f7f
lightest to pass minimum standard (1:4.5) is #767676
lightest to pass enhanced standard (1:7.0) is #595959

**Comment by amandafrench** [comment]
In general sometime it'd be good to run http://wave.webaim.org/ and do an accessibility review of the whole site, but for now we can address this very old issue of making a small alteration in the style so that our font color has sufficient contrast.

**Comment by pgray64** [comment]
Web accessibility 2.0, https://www.w3.org/WAI/intro/wcag  
Color contrast checker, http://webaim.org/resources/contrastchecker/

**Comment by pgray64** [comment]
Made contrast changes with pull request #302
