### ISSUE TITLE
Put in new vtechworks-requests Google Group address into dspace.cfg

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#216]
We need to alter the following line in dspace.cfg (line 2094 in my version, in the Request Item Configuration section): 

 mail.helpdesk = ${mail.admin}

I created a Google group with the address vtechworks-requests-g@vt.edu to manage these requests. Carrie will be handling these -- I added her to that group, as well as Melissa and Anne, although I might remove Melissa and Anne so that we don't all get the emails.

**Comment by mello99** [comment]
I can ask Aaron Hunnewell to forward emails from "etd-submit@dla.lib.vt.edu" to Carrie; that way they would go directly to her mailbox. I currently get emails from "etd-submit@dla.lib.vt.edu" sent to my personal mailbox (not just the VT Support Mailbox), and I could forward her any related ETD request emails that are sent to vtechworks@vt.edu. Then again, if your strategy is more efficient, that's fine.

**Comment by amandafrench** [comment]
Sigh, I don't know why those requests are going to etd-submit@dla.lib.vt.edu, but you're right, they are. All the email stuff is a complete mess -- way too many darn email addresses in this thing. I thought all the requests were going to the administrator email address, ${mail.admin}, which should be vtechworks@vt.edu, but they aren't.

**Comment by amandafrench** [comment]
I think a few people get etd-submit@dla.lib.vt.edu emails, actually, though I don't seem to.

**Comment by amandafrench** [comment]
Apparently the "helpdesk" option in dspace.cfg was never really working. Aaron added Carrie to the etd-submit email delivery list, so I'll close this issue.
