### ISSUE TITLE
Turn off or enhance ORCID functionality 

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#217]
We need to either turn off or enhance ORCID functionality; we could research it more to make it more useful: the hash error is annoying, and the fact that there's no link to the ORCID profile of the researcher makes it pointless. Not for the current sprint.

**Comment by alawvt** [comment]
It definitely makes metadata clean up and manipulation harder.

**Comment by alawvt** [comment]
July 20, 2015 Pull Request #3, commit 242ec71, to turn on ORCID authority control.

**Comment by alawvt** [comment]
This change would make metadata work easier and safer.

**Comment by amandafrench** [comment]
Feel free to just do it, @alawvt or @mello99! Or rather undo it. :) Assign yourself if you want to volunteer to remove the associated lines from dspace.cfg. And thanks for finding it, @alawvt.

**Comment by alawvt** [comment]
@keithgee, would reverting commit 242ec71 and removing `/dspace/bin/dspace index-authority` and `/bin/dspace dsrun org.dspace.authority.UpdateAuthorities` from crontab, if they exist, do it?

**Comment by keithgee** [comment]
I think so, but I don't know. This sounds like a good one to try on an LDE
or on dev.

**Comment by alawvt** [comment]
Neither of these tasks appear in crontab on vtechworks.lib.vt.edu.

**Comment by alawvt** [comment]
Resolved with Pull Request #273
