### ISSUE TITLE
Thumbnails not showing for restricted items

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#218]
Hi, all, I think @keithgee said that this was a bug (#167 - @keithgee wrote "I've also seen this, going way back to work at OhioLink from 2007-2009. It seems to be triggered by thumbnails with access restrictions, though it's still a bug").

Anyways, here's a screenshot of what I see when I try to access VTechWorks using a VPN: 

![restricted_thumbnail_issue](https://cloud.githubusercontent.com/assets/5408616/13756398/1f1a57c0-e9f6-11e5-9948-df9d684bded3.png)

I don't know if there's much we can do since the file is restricted, but I thought I'd bring this up just in case. Take care.

Melissa

**Comment by keithgee** [comment]
Hey, @mello99. 

If it's okay to display the thumbnail, there are options.
1. Use the web interface to add Anonymous read permission to the thumbnail of each of these items
2. When these items are loaded in via batch, there may be parameter that can be set in the CONTENTS file that can give Anonymous read to the thumbnails. @alawvt may be able to find out more.

If it's not okay to display the thumbnail, then I wonder if it might be possible to make a theme change that doesn't attempt to display thumbnails on these items. If it's possible, someone in the DSpace community has probably already done it.

**Comment by keithgee** [comment]
EDIT above: add Anonymous READ permission to _the THUMBNAIL_s of these items... And not the entire item. :)

**Comment by alawvt** [comment]
When we load these restricted ETDs, we're loading the PDF as "-r VT_campus". DSpace uses that to create a thumbnail with the same restriction. If I were loading the thumbnail, I could set a different restriction for it. I don't see an easy option for changing this behavior.

**Comment by amandafrench** [comment]
Aha, this is an existing issue at DSpace Core with an apparent fix: https://jira.duraspace.org/browse/DS-2789 

We will need to generate a "restricted item thumbnail" image, though. Will assign the project of creating that image to you, @mello99, though I won't put it in this sprint. You can do it next month, or this month you want to avoid other work. :) It should be about 100px by 125px and clearly say something like "This item is restricted to Virginia Tech." 

Once we've got the image, we can try out the fix in the Jira issue.

**Comment by alawvt** [comment]
To not break our theme, I suggest our standard thumbnail size, which is 80x80 pixels.

**Comment by amandafrench** [comment]
Sure, that's fine. But I don't think it would break the theme -- I went by the size of the actual thumbnail shown on the item Melissa listed above (from on campus, obviously), which is 99px by 128px.

**Comment by alawvt** [comment]
That's interesting; there are multiple thumbnail sizes. The latest items that I had sampled were 80x80px. I could dig into the thumbnail generating script to find out the latest setting.

**Comment by amandafrench** [comment]
Doesn't matter. Seems wise to have the default "restricted item" thumbnail be smaller, though, so go for the 80 x 80 size, @mello99. Thanks.

**Comment by mello99** [comment]
Thanks everyone for clarifying; I'll stick to the 80 x 80 size, then create 2 canned thumbnails: 
- One that can be used for VTechWorks' restricted items
- Another that is sufficiently general and can be used for restricted items in any DSpace instance
  Thanks for your help!

**Comment by mello99** [comment]
Hi, everyone, I've created some thumbnails for us to evaluate (see attached ZIP file). I created 7 possible thumbnails for restricted items (a lot, I know), and the difference between each thumbnail mostly involves the language used. 

I actually think we should go with thumbnail 7, which is just a padlock. Including language with the thumbnail works when the thumbnail is much larger, but not as much when the thumbnail is 80 x 80 pixels. 

I would also recommend (and I'd be willing to do this) revising the language that a user sees when he or she requests a restricted item. To be specific, I'd like to include a sentence about how the item is restricted to VT faculty, staff, and students, and that the aforementioned groups can access the item by logging-in to VTW via "Off Campus Sign In" (a lot of VT users overlook that notice, or aren't aware that they need to use it in order to access restricted ETDs).

Thanks, everyone!
[Resized_Thumbnails.zip](https://github.com/VTUL/vtechworks/files/191994/Resized_Thumbnails.zip)

**Comment by alawvt** [comment]
@mello99, I can see the lock symbol clearly in all the images (viewed at 100% zoom level). However, I can only, just barely, read the text in Restricted_1_80x80.tiff and none of the text in the others. The lock symbol by itself in Restrict_7_80x80.tiff is the clearest, but I am afraid that might scare off patrons, not realizing what it means. Maybe you could experiment with larger font. 

Another possibility is to use the VT Shield logo, which is used on the Libraries' website for VT only items, for example, http://www.lib.vt.edu/find/databases/A/abi-inform-from-proquest.html. The tooltip for the shield is, "This resource is restricted to Virginia Tech users only"
![l_vtonly](https://cloud.githubusercontent.com/assets/13037168/14148427/671f2e28-f66d-11e5-92cc-d504514bd610.gif)

**Comment by amandafrench** [comment]
I'm going to put a "revisit later" mark on this and close it for now, though I think we'll need to reopen it and several others next month.
