### ISSUE TITLE
Investigate why Google Scholar is not finding PDF of item

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#219]
The author of http://vtechworks.dev.lib.vt.edu/handle/10919/64500?show=full points out that Google Scholar cannot find the PDF of his work; it only points to the item record. 
![screenshot 2016-03-15 11 26 01](https://cloud.githubusercontent.com/assets/227453/13783217/d919d330-eaa0-11e5-985d-3c3d31742b4c.png)

It should find the PDF, as in this example: 

![screenshot 2016-03-15 11 21 39](https://cloud.githubusercontent.com/assets/227453/13783226/e5a5d900-eaa0-11e5-85dd-e5b8cd1f301b.png)

We have tried correcting the name metadata and increasing the font size of the title, to no avail. However, it might take 6-9 months for Google to reindex, in any case, since there's an existing record. 

I added a new, duplicate item at http://vtechworks.lib.vt.edu/handle/10919/64920 to see if that one gets fully indexed.

**Comment by alawvt** [comment]
We added a suggestion to the ETD projects file that the Grad School add larger title font size to their ETD formatting guidelines, http://etd.vt.edu/guidelines/index.html.

**Comment by keithgee** [comment]
Google Scholar is now finding the PDF for this item.
Removing "revisit later" tag.
