### ISSUE TITLE
Need a larger logo in the header

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#22]
```
<a class="navbar-brand" href="/">
   <img src="/themes/vtmirage2//images/VT_white_cmyk_invt.png">

header .navbar-brand img {
    height: 22px; /*change to 50px*/
}

.navbar-brand {
    float: left;
    font-size: 18px;
    height: 50px; /*change to 80px*/
    line-height: 20px;
    padding: 15px;
}
```

**Comment by amandafrench** [comment]
This definitely does create issues on mobile devices -- see comments on pull request https://github.com/VTUL/vtechworks/pull/43. I think one good way to resolve this might be to use em or % instead of px to set the .navbar and img size. Actually I'm surprised they aren't already expressed in those units, since this is supposed to be a responsive theme! Can you try this out if you come in tomorrow, @AmberPoo1?

**Comment by AmberPoo1** [comment]
Sure @amandafrench

**Comment by amandafrench** [comment]
Actually, never mind, @AmberPoo1 -- I looked into this and made a change that I *think* will solve it. It's not deployed to the dev server yet: we've got a couple other changes we might want to deploy to development tomorrow, so I'll wait until I know about those.

**Comment by amandafrench** [comment]
Looks like my fix worked! This change did get deployed to dev today, so you can take a look there on mobile if you like, @keithgee and @alawvt. Closing the issue. Thanks, @AmberPoo1.

**Comment by keithgee** [comment]
That's a huge improvement @amandafrench, and I'm surprised that such a small change can make such a big difference.
