### ISSUE TITLE
Customize error page(s) in VTechWorks

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#220]
We've been asked by ITS to customize an error page so that it does not give debug information, including the stack trace.

The error page is at /dspace-xmlui/src/main/webapp/exception2html.xslt. 

Please remove stack trace and other debug information from this page. Just let the user know there was an error, and how to get in touch with us.

If you can do this as a Maven overlay, that would be best.
@AmberPoo1 lease work with @amandafrench to prioritize this issue.

**Comment by alawvt** [comment]
@keithgee, I understand the security concern but wonder if this will hinder development work on our Vagrant instances. Will this error info and stack trace be available anywhere else (i.e. log file)?

**Comment by keithgee** [comment]
@alawvt, that's a great point! A friend told me that I might want to point out to our IT security office that DSpace is open source and the stack traces aren't state secrets, which made me laugh!

The cocoon stack trace will still be recorded in the cocoon.logs, and this may help diagnose some problems.

**Comment by amandafrench** [comment]
This is done and merged.
