### ISSUE TITLE
Issue with Mary Finn's VTW Access and Modification Credentials

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#223]
Hi, all, Mary Finn, for some reason, is not able to edit items in VTechWorks because the "Edit Metadata" pane in the menu on the right hand side of the screen does not appear. She has administrative privileges to selected collections, but I forget specifically where I need to go in order to correct her permissions so that she can make edits. I'll look into this, but I just wanted to see if anyone had any suggestions. Thanks!

**Comment by amandafrench** [comment]
I've added Mary to the general Administrators group [id=1] via Access --> Manage Groups. Jana was already in that group. Mary can now edit any item in the repository. (I'm going to remove her email from the issue, too.)
