### ISSUE TITLE
Create VTechWorks Elements mapping file

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#224]
I started a wiki page about the Elements integration in GitLab, https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/Elements_integration.  
I renamed our mapping file to VTechWorks_Elements_Field_Mappings to distinguish it from the DSpace-Elements default mapping file.

**Comment by amandafrench** [comment]
Great, thanks, @alawvt! Take note, @mello99. Closing.
