### ISSUE TITLE
"View Usage Statistics," http://vtechworks.lib.vt.edu/statistics-home, not viewable unless logged in as administrator 

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#23]
Logged in as an admin, "View Usage Statistics," http://vtechworks.lib.vt.edu/statistics-home, seems to show cumulative statistics on the home page, collection page, and individual item pages.

Logged out, there are not statistics links from the home page or an item page. Previously, "View Usage Statistics" was viewable without being logged in.

Keith Gilbertson @vtkeithg about 10 hours ago

This is by design. Under a fresh DSpace install, the usage statistics are not viewable except by administrators. Allowing non-administrators to view statistics is a custom configuration change that we made in a previous install. For this deployment, we agreed to forgo most of our customizations in order to start with a clean copy of DSpace. This seems non-critical; I think this issue should be placed on GitHub for review in the next update. Closing.

**Comment by amandafrench** [comment]
Whoops, same as #32. Will close this one.
