### ISSUE TITLE
Error submitting file to DSpace via Elements

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#231]
Hi, @keithgee and @amandafrench , I tried to deposit the attached file - "Zou_Targeting_Fox.pdf" - to DSpace PPRD via the Symplectic Elements user interface (I'm logged-in to ed.lib.vt.edu, NOT clio), but I received the following error message:

<img width="538" alt="screen shot 2016-04-04 at 1 09 35 pm" src="https://cloud.githubusercontent.com/assets/5408616/14256405/eee529e6-fa66-11e5-84b4-fab88b8ede37.png">

Any ideas as to what might be going on? I was hoping to test this particular item because I was including rights information directly in the Symplectic metadata schema (rather than via the Creative Commons API - the metadata from that API hasn't been transferring over to DSpace). 

However, I couldn't even get to the part where I'm prompted to enter metadata from the Creative Commons API because the file upload failed. Thanks so much, take care.

[Zou_Targeting_Fox.pdf](https://github.com/VTUL/vtechworks/files/202962/Zou_Targeting_Fox.pdf)

**Comment by mello99** [comment]
I'd also like to note that I've been unable to upload PDF, RTF, and CSV files.

**Comment by keithgee** [comment]
@mello99 let me look into it. vtechworksdev recently had a deployment, so I probably need to run a script again.

**Comment by keithgee** [comment]
oops - I just realized that our elements is connected to vtechworks pre-production. i'll look into it, though.

**Comment by keithgee** [comment]
I was able to submit a PDF file to the repository just now, from ed.lib . It's at http://vtechworks.pprd.lib.vt.edu/handle/123456789/64484. I'll come by and take a look, @mello99. You're probably testing more thoroughly than I have, and amight be doing something I haven't tried.

**Comment by keithgee** [comment]
@mello99 manually entered the metadata for an article, including eISSN metadata.
The VTechWorks Pre-prod was missing dc.identifier.eissn. Now she has added idenitfier.eissn it to the 
Dublin Core metadata registry on pre-prod, and then submitted the PDF file again. The deposit was successful.
We'll have to remember to check metadata fields in all registries on production when we do the install there, too.
Deposit with eISSN is now successful. 
***closing

**Comment by mello99** [comment]
Thank you, Keith!
