### ISSUE TITLE
Can a PPRD administrator reset my account password?

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#233]
Hi, all, I've been trying to log-in to VTW PPRD for quite some time using my email address - mlohrey@vt.edu - and password, but I've been prevented from doing so every time.

I'm able to receive a password reset message at mlohrey@vt.edu, but whenever I try to reset my password the changes don't go through. I've been able to log-in to PPRD using the vtechworks@vt.edu email account, **so there's no rush on this**, but I was wondering if a PPRD admin could reset my password for me (@kayiwa suggested this course of action since it's not a filesystem request).

@keithgee or @alawvt , when you have time, could either of you try this since Amanda's out of town? Like I said, it's **definitely not urgent** since I can log-in to PPRD using the vtechworks@vt.edu account, but it would be nice if I could log-in using my personal email address and password sometime down the road. Thanks so much!

**Comment by keithgee** [comment]
@mello99 I'm interested in troubleshooting this when you're in the office. @kayiwa resolved a similar issue on production in 2015 May by changing the dspace hostname in the dspace.cfg file to use https. So I did this on pre-production this morning.

I wonder if this fixes the reset feature for you. Either way, we'll fix it so you can login to PPRD.

**Comment by mello99** [comment]
Hi, @keithgee , we can meet anytime after 1pm on Monday. For now I can just sign-in using the VTW support email. Thanks for your help, and take care.

**Comment by keithgee** [comment]
@mello99 I just used the reset password function from the "People" control panel in DSpace on PPRD to send a message that will allow you to reset your password.
Does this work for you now?

**Comment by mello99** [comment]
Hi, @keithgee , it worked, so we're good now!
