### ISSUE TITLE
Created 2 new user accounts and no emails were received

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#234]
Monday, I created two new VTechWork accounts for library employees. They both reported that they did not receive emails notifying them that the accounts were created. However they did receive password-reset emails.

**Comment by amandafrench** [comment]
You might try testing this yourself, @alawvt, just to verify -- you can use mailinator.com to create temporary email accounts to test with. If you can reproduce the issue, I'd report it to @kayiwa using TeamDynamix.

**Comment by alawvt** [comment]
@amandafrench, thank you for the suggestion to use mailinator.com. So far, no email for  ClueDinkle@mailinator.com.

**Comment by alawvt** [comment]
The email for the new account never arrived. The email to reset the password was received immediately,
I tried with another email address and no response.  
It should send the email in vtechworks/dspace/config/emails/register.

I have submitted a TeamDynamix request.

**Comment by alawvt** [comment]
@kayiwa replied in the TeamDynamix request,

"This looks like an application problem. We do know that mail on vtechworks works since it is able to reset my password etc., Unfortunately I don't know enough about dspace to begin to guess why this particular variable is not working. I do know @amandafrench made a request to change how one aspect of mailing works but I doubt this would be the source. Since AH worked on this I will defer to him if that is the source of the break."

**Comment by mello99** [comment]
Hi there, a VTW user cannot reset her password (she's not receiving the reset email). Her email is correctly entered into VTW, so I'm at a loss as to what the issue is. I've tried resetting her password for her, but I haven't heard back. I'll keep you updated if I need additional assistance.

**Comment by mello99** [comment]
Ok, never mind, @kayiwa , the user eventually got her password reset emails, it just took longer than she'd anticipated. We're good (as far as the password reset emails are concerned), thanks so much.

**Comment by alawvt** [comment]
We are still having the issue with no email for new accounts. We had two NLI classes full of folks who hadn't received the emails about their new accounts.

**Comment by mello99** [comment]
Yeah, I just wanted to clarify that the password reset emails weren't a problem (they are a little slow to get out, however).

**Comment by keithgee** [comment]
This isn't a bug; it's just the design of the system. It has always worked this way.

When an administrator uses the "People" screen to create new accounts for users, DSpace does not send e-mails to notify the users of the new accounts. This is on purpose. It sends e-mails when people self-register on DSpace, or when an administrator resets their password, but not when an administrator creates accounts for other people.

**Comment by alawvt** [comment]
@keithgee, thank you for this information.
