### ISSUE TITLE
Update Sherpa/Romeo green message in messages.xml

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#235]
Hi, @amandafrench , @alawvt , and @keithgee , I tested out VTW's Sherpa/Romeo lookup functionality for the "Journal of Library Metadata," and the information provided by the lookup functionality is, in my opinion, not entirely accurate. 

To elaborate, the pithy message I received when I tried to upload a dummy publication from the Journal of Library Metadata was the following: "green - you may deposit any version of your work (More info)." I strongly doubt that many users will click on "More info" (which takes you to the Sherpa/Romeo page that lists the complete set of archiving rules). I think they'll just focus on the green message and move forward.

According to Sherpa/Romeo, "green" publications are those for which the user "Can archive pre-print and post-print **or** publisher's version/PDF". So "green" does not inherently mean that you can archive the publisher's PDF - in many cases, you can't.

Below is a screenshot of the message I received when I tried to deposit a dummy pub from the Journal of Library Metadata:

![sherpa_romeo_library_metadata](https://cloud.githubusercontent.com/assets/5408616/14571512/9cedf780-0317-11e6-88da-a857ad6b93fc.png)

I just think this message is slightly misleading and may give users the impression that they can upload publisher's PDFs when they can't. Thanks all, take care.

**Comment by alawvt** [comment]
Perhaps instead of "green - you may deposit any version of your work," it might say "green - you may be permitted to deposit any version of your work."
And perhaps instead of "More info" it could say "Please read detail" or something to that effect.

**Comment by mello99** [comment]
I'm reluctant to insert a "Please read detail" link in the same place as the "(More Info)" link because I doubt that people will take the time to do that. Perhaps it would work if we inserted a "Please read detail" link inside the green text; that text stands out and is easier to catch.

I just think it's too easy to get the wrong impression from the current message that's up there.

**Comment by amandafrench** [comment]
Hi @mello99 - Please write the exact message that you think would be appropriate and include it here -- or you can change it yourself in the messages.xml file.

**Comment by amandafrench** [comment]
Will bring these into line with what Elements says (Draft version, Submitted version, Accepted version, Publisher's version)

**Comment by alawvt** [comment]
@amandafrench, I have a suggestion for the green message: "you **might** also be allowed or required to deposit the publisher's version" instead of  "...you **may** also be allowed or required to deposit the publisher's version.." I think "might" better conveys the uncertainty of uploading the publisher's version (and need to check) than "may." May has two possible meanings: permission and possibility.

**Comment by amandafrench** [comment]
Sure thing, @alawvt -- feel free to correct this and push it yourself. No need to create a pull request even.
