### ISSUE TITLE
dc.description.provenance has duplication

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#239]
Hi, @keithgee , we're having issues with the "dc.description.provenance" field. There's some duplication occurring in that field, specifically for the address information that's exported from Elements (see [this PPRD record](http://vtechworks.pprd.lib.vt.edu/handle/123456789/64511?show=full) - you have to be signed-in to PPRD and have admin privileges, though).

Tell you what - why don't we try adding "dc.description.provenance" to the DSpace config file and see if it's overwrites or breaks something important. If not, we can keep it there. If it does break something, I will map the Elements' "addresses" field to another DSpace field. Thanks, take care.

**Comment by keithgee** [comment]
I've added dc.description.provenance to the pubs metadata authority fields on PPRD and restarted Tomcat.

**Comment by mello99** [comment]
Thanks, I'll keep testing today since the new version of Elements is up and running; we'll see how it goes.

**Comment by mello99** [comment]
This is working, thank you!
