### ISSUE TITLE
Document location of and any notes on ETD scripts

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#24]
Hey @rotated8, when you're finished with the ETD scripts (or while you're working on them), could you update the wiki page at <strike>https://wiki.duraspace.org/pages/viewpage.action?pageId=32481931</strike> https://github.com/VTUL/vtechworks/wiki/Automatic-imports with their location on the server and any necessary notes about them? I remember we had suggested that the scripts have their own repositories, so if you do that, a note about where the new repos are would also be helpful.

**Comment by alawvt** [comment]
I'm curious about that wiki page. It looks like it is from version 3.

**Comment by amandafrench** [comment]
@alawvt Crumbs, second time this week where I pasted the wrong link -- I meant to link to our own wiki page here on Github. I was looking at that DSpace page for an entirely different reason. 

Correct link: https://github.com/VTUL/vtechworks/wiki/Automatic-imports 

I'll edit the note above.

**Comment by amandafrench** [comment]
The ETD scripts are now maintained on GitLab at git.it.vt.edu.

**Comment by alawvt** [comment]
There are two ETD script projects on GitLab at git.it.vt.edu: the current script (not up to date with latest email and eperson changes) and the unfinished script rewrite.
