### ISSUE TITLE
XSLT error (my bad) - duplicate "dc.format.extent" information

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#240]
Hi, @keithgee , I neglected to comment out a line of markup on the XSLT file for "dc.format.extent", so that caused some additional duplication ([see this latest commit for the fix](https://github.com/VTUL/vtechworks/commit/d203f13b83c76fe1b5b2f00970c18f494fa6584b)). 

When you get the chance on Wednesday, could you restart PPRD to see if the change I made to the XSLT resolved this issue? Thanks so much.

**Comment by keithgee** [comment]
@mello99, I have installed your changes and restarted PPRD.

**Comment by mello99** [comment]
Thanks!

**Comment by keithgee** [comment]
Is this fixed?

**Comment by mello99** [comment]
Fixed
