### ISSUE TITLE
XSLT Issue - "dc.date.available" is duplicated

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#242]
See screenshot below. @keithgee , could you add "dc.date.available" to the DSpace config. file when you get the chance? Thanks so much.

<img width="734" alt="screen shot 2016-04-20 at 5 04 48 pm" src="https://cloud.githubusercontent.com/assets/5408616/14690432/200773b6-071a-11e6-8dc4-e95caa0f183a.png">

**Comment by keithgee** [comment]
I've added it.

**Comment by mello99** [comment]
Thanks! Also, I've decided not to use it (sorry I decided this after you added it to the config!), so we're done with this field. Closed.

**Comment by mello99** [comment]
Hi, @keithgee , even though this issue is closed, I just wanted to make sure that "dc.date.available" was still in the config file, because I decided to change the mapping back to "dc.date.available". Thanks!
