### ISSUE TITLE
Embargo period is available in Elements 5.0

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#243]
Hi, @amandafrench , I thought that we weren't going to allow users to select an embargo period for Elements items that they're depositing in VTechWorks, but the latest upgrade of Elements - 5.0 - gives users that choice (see below). Should we go ahead and test this functionality anyway? Thanks, take care.

<img width="489" alt="screen shot 2016-04-20 at 5 17 01 pm" src="https://cloud.githubusercontent.com/assets/5408616/14690795/e7668234-071b-11e6-8a98-212701d3b9d7.png">

**Comment by amandafrench** [comment]
No, let's not give users that option, at least not yet. If they don't want their item to be publicly available, they needn't deposit it to the repository. We can always test later if it proves to be a desired functionality.
