### ISSUE TITLE
Can you add me to the branch listed below?

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#249]
I think I need to add the XSLT code for removing the forward slashes to [this branch](https://github.com/VTUL/vtechworks/blob/b79a7ca97cc15e5a068a9d81178312acc4238bb4/dspace/config/crosswalks/symplectic_xwalks_toolkit.xsl). Thanks, take care.

**Comment by amandafrench** [comment]
@mello99 - That's not a branch: that's a commit. All you need to do is pull or fetch the current vt_5_x_dev branch and make the changes to the /dspace/config/crosswalks/symplectic_xwalks_toolkit.xsl file on your own machine, then push your own commit as described at https://github.com/VTUL/vtechworks/wiki/3.-Making-changes-on-the-local-development-environment, Feel free to reopen this issue if I've misunderstood.
