### ISSUE TITLE
 HTML encoding for abstracts

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#25]
Would be excellent, since there are many abstracts that contain bulleted lists, etc. But I realize we're still in the testing phase, so no rush! Thanks so much :).

Reported by Melissa Lohrey.

**Comment by amandafrench** [comment]
Example: http://vtechworks.lib.vt.edu/handle/10919/43537 -- shows <p> tags.

**Comment by alawvt** [comment]
I want to add a related observation, but it probably needs its own issue: abstracts from the Grad School system come with line breaks between paragraphs, example http://vtechworks.lib.vt.edu/handle/10919/56637. (Metadata from the Grad School does not include any HTML tags.) These line breaks are not displayed (per usual HTML rendering) in the Simple and Full Item views in VTechWorks. However they are apparent in the "Edit Item" view. It might be helpful if we could enable the display line breaks in metadata. To provide more consistency across our various sources of ETDs, we might shoot for a standard of either <p> for line breaks or the display of hard coded line breaks. (A long term goal of the BTD project had been to add abstracts to the metadata of the 1000's of early BTDs.)
