### ISSUE TITLE
Altmetrics badges (blank ones) not showing on items deposited from Elements

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#254]
Pre-production still has the altmetric badges showing for all items, even when there is no data, but items deposited from Elements do not have that badge. 

![screenshot 2016-04-27 16 51 37](https://cloud.githubusercontent.com/assets/227453/14867813/5a69c29c-0c98-11e6-8e27-507585489b01.png)

**Comment by mello99** [comment]
Hi, @amandafrench , this appears to be a consistent issue for all items uploaded to PPRD. I recently uploaded an open access article that was one of the top [100 Altmetrics articles for 2015](https://www.altmetric.com/top100/2015/#explore); it has 2432 mentions.  

I uploaded this article using the PPRD submission form - I did not use the Elements submission form. The article can be accessed here: http://vtechworks.pprd.lib.vt.edu/123456789/64555. I added the article's DOI (dc.identifier.doi), which I think I recall is important for Altmetrics to be able to identify the publication. Anyways, I'm not seeing the donut with the statistics, so this may be a consistent issue for all PPRD publications. 

Would you like me to upload this publication to the "Library Test" collection on production to see what happens? It's an open access article, so no harm no foul if it's made public. Thanks, take care!

**Comment by amandafrench** [comment]
Hmm, I just tested myself in a different collection, and you're right, it's some issue with all new items on pprd. Again, it's not so much that I expect items in VTechWorks to show altmetrics data (our badges track only mentions of VTechWorks handles, so they won't capture mentions of article DOIs: basically, altmetrics thinks our article is a different item altogether from the one in the Top 100) as that the gray doughnut with the question mark should be appearing. 

There could actually be a lot of reasons for this, though, so I'm not going to worry about it a lot yet. Will close and tag for later revisting, and will include it in my test plan. If it persists on production when we deploy there, we can troubleshoot further.
