### ISSUE TITLE
Change alert box background color

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#260]
to orange, so it's more prominent

**Comment by amandafrench** [comment]
Administrators can set "system alerts" that appear on the home page to let users know of downtime and so on. It needs a background color of some kind in the div (perhaps orange) so that it's more prominent. 
![screenshot 2016-06-09 12 25 31](https://cloud.githubusercontent.com/assets/227453/15937547/64332a36-2e3d-11e6-83ad-88c95ca65173.png)

**Comment by amandafrench** [comment]
I set up that alert on pre-production. Here's the code: 
![screenshot 2016-06-09 12 27 03](https://cloud.githubusercontent.com/assets/227453/15937585/878d95c0-2e3d-11e6-9c2f-290b596e681f.png)

**Comment by pgray64** [comment]
Is there a way I can trigger that alert to show up on my local DSpace instance?

**Comment by alawvt** [comment]
Resolved by PR #295. I suggest contributing this to DSpace main project.

**Comment by pgray64** [comment]
![alert-bg](https://cloud.githubusercontent.com/assets/7339589/16096789/9560d0ec-3318-11e6-8ee3-45159e1e8ead.png)
Using Bootstrap's `alert-warning` class

**Comment by amandafrench** [comment]
Great, thanks! Exactly the right choice, too, to apply an existing "alert-warning" class from Bootstrap instead of redefining the "alert" class in our custom theme. Agree about contributing to DSpace main -- relevant file is here. Have applied the "dspacecore" label to indicate that the issue is still open until it's been contributed to DSpace core, @pgray64  -- see instructions at https://github.com/VTUL/vtechworks/wiki/9.-Contributing-to-the-main-DSpace-project. Once you've created the issue there you can close this one. No need to wait until the DSpace issue is accepted.

**Comment by pgray64** [comment]
Created an issue on the Duraspace issue tracker. Created fork from DSpace master with the modification and submitted pull request.

**Comment by alawvt** [comment]
Thanks, @pgray64. Please add a link to the Duraspace issue, https://jira.duraspace.org/browse/DS-3249, so we can refer to it.
