### ISSUE TITLE
Fix color of link in mobile breadcrumb bar

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#262]
![link_color_breadcrumbs](https://cloud.githubusercontent.com/assets/227453/15162362/73d2a8a6-16d0-11e6-9c0f-a318b7eed6b4.jpg)

**Comment by amandafrench** [comment]
That "View Item" link in the mobile view of an item disappears because it's maroon. Should be changed to white.

**Comment by alawvt** [comment]
Resolved with PR #293.
