### ISSUE TITLE
Incorrect links and non-functioning search box on error page

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#264]
In the attached screen shot of the error page, the link in the breadcrumb for "VTechWorks Home" is http://vtechworks.lib.vt.edu/handle/10919/236910 (the URL causing the error) but should be http://vtechworks.lib.vt.edu/handle. The link for "Log In" is also http://vtechworks.lib.vt.edu/handle/10919/2236910 (the URL causing the error) but should be http://vtechworks.lib.vt.edu/login. 

Also the search box does not take one anywhere. It looks like there is some redirection in the status bar, but I can't see the detail.

![errorpage](https://cloud.githubusercontent.com/assets/13037168/15185787/81ba17ae-1768-11e6-9df5-774a3953eaf3.png)

**Comment by amandafrench** [comment]
I'm going to assign this bug to @AmberPoo1 to take a look at -- unless you can, @keithgee? I'm not sure where the error page is generated. It can wait, but let's try to fix it this sprint if possible.

**Comment by keithgee** [comment]
This is fixed with commit 11c4d0b.

**Closing
