### ISSUE TITLE
Versioning issue - items (and their handles) are being deleted

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#268]
Hi, all, I tried creating versions of an item in VTW on 3 different occasions. On 2 of those occasions, the versioning functionality went totally awry and created an entirely new handle, deleting (or rendering inaccessible) the old version of the item. On top of that, the new "version" of the item with the new handle is no longer accessible - you get a message saying that an error occurred.

I have no idea what I did wrong - I simply went through and selected "Create a new version" of this item, then approved the metadata and bitstreams so that the item could be entered into the repository. I would suggest that we refrain from doing any further versioning until we get to the root of this bug. 

@keithgee , you did such an awesome job helping me earlier - can you help me again? Thanks so much!

**Comment by mello99** [comment]
I think I know what the problem is, because I just tried creating a versioned item on PPRD. 

In essence, if you're going to create a new version of an item, you have to make changes to that particular version _during the process of creating that version_. 

What I did the first time was create a second version and leave it the same as the first because I planned on making the changes after the second version was in the repository. It appears that you can't do this - you have to make the changes to the new version _before_ it's submitted and approved.

This is just a guess - I don't have the code to prove that this works or that this was what caused the glitch - but I encountered no problems with the versioning functionality when I did this. If I don't hear back from anyone in the next 24 hours about this issue, I'll close it. Thanks for your help (especially yours, @keithgee ), and take care.

**Comment by keithgee** [comment]
Good research, @mello99!
