### ISSUE TITLE
Thumbnail different in collection item list and search results than in simple item view

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#269]
The author noted that the thumbnail in simple item view, http://vtechworks.lib.vt.edu/handle/10919/70924, is different than the one in the collection item list, http://vtechworks.lib.vt.edu/handle/10919/64855, and in search results. She would prefer to have the thumbnail that appears in the collection list, fair-use-week-2016-panels.pdf.jpg, appear in the simple item view, instead of FairUseWeek2016_Event-Toolkit_VTUnivLib.pdf.jpg, which is in simple item view now. 

She placed fair-use-week-2016-panels.pdf.jpg first in the bitstreams Bundle: THUMBNAIL list in "Edit Item" view, http://vtechworks.lib.vt.edu/admin/item?administrative-continue=3440426a3b5225050e434a611450374013733b26&submit_bitstreams. However, she wants to have a different file, FairUseWeek2016_Event-Toolkit_VTUnivLib.pdf, listed first in the files list in Simple Item View, so that is listed first in Bitstreams Bundle: ORIGINAL.

If the thumbnail order is applied in the collection view and search results, it should also be applied in simple item view.

I reported this issue in https://jira.duraspace.org/browse/DS-3215 on 5/20/2016.

By the way, this item has Altmetrics=4.

**Comment by amandafrench** [comment]
Reported to DSpace -- will close since there's probably nothing we can do about it on our end.

**Comment by alawvt** [comment]
Please try to reproduce on DSpace Demon


     [ https://jira.duraspace.org/browse/DS-3215?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel ]

Tim Donohue updated DS-3215:
----------------------------
    Status: Volunteer Needed  (was: Received)

Needs volunteer to reproduce this behavior in DSpace itself (e.g. on demo site). It sounds like a possible bug, but we need to verify it's not specific to this one site.

Thumbnail different in collection item list and search results than in simple item view
---------------------------------------------------------------------------------------

                 Key: DS-3215
                 URL: https://jira.duraspace.org/browse/DS-3215
             Project: DSpace
          Issue Type: Bug
          Components: XMLUI
    Affects Versions: 5.5
         Environment: Mac
            Reporter: Anne Lawrence

The author noted that the thumbnail in simple item view, http://vtechworks.lib.vt.edu/handle/10919/70924, is different than the one in the collection item list, http://vtechworks.lib.vt.edu/handle/10919/64855, and in search results. She would prefer to have the thumbnail that appears in the collection list, fair-use-week-2016-panels.pdf.jpg, appear in the simple item view, instead of FairUseWeek2016_Event-Toolkit_VTUnivLib.pdf.jpg, which is in simple item view now. She placed fair-use-week-2016-panels.pdf.jpg first in the bitstreams Bundle: THUMBNAIL list in "Edit Item" view, http://vtechworks.lib.vt.edu/admin/item?administrative-continue=3440426a3b5225050e434a611450374013733b26&submit_bitstreams. However, she wants to have a different file, FairUseWeek2016_Event-Toolkit_VTUnivLib.pdf, listed first in the files list in Simple Item View, so that is listed first in Bitstreams Bundle: ORIGINAL.
If the thumbnail order is applied in the collection view and search results, it should also be applied in simple item view.



--
This message was sent by Atlassian JIRA
(v7.0.0#70107)

**Comment by pgray64** [comment]
I made a test submission: http://demo.dspace.org/xmlui/handle/10673/100
Still waiting for thumbnails to be generated. Default Dspace settings generate them at 3:00 AM. The demo will reset on Saturday.
