### ISSUE TITLE
Browsing by Issue Date

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#275]
Hi all, Gail asked me to mention a possible enhancement involving DSpace's "Browing by Issue Date" functionality. In short, a user contacted her and asked why it wasn't possible to browse by issue date for single years prior to 2005. This involves the "Browse" function, _not_ the faceted search function. As you know, the "Jump to a point in the index" function is set up to look back in 5-year increments before 2005, then in 10-year increments prior to 1980 (see screenshot at the bottom).

The user eventually figured out that he or she could enter the issue date in the search bar and get the correct results that way, but found the "Jump to a point in the index" function confusing. Thanks so much, and take care.

![screen shot 2016-05-25 at 1 34 48 pm](https://cloud.githubusercontent.com/assets/5408616/15550384/2aaf2f68-227f-11e6-8a57-41ee20df7c81.png)

**Comment by amandafrench** [comment]
Okay, I've put this in the backlog. Will close until we decide to address it.

**Comment by amandafrench** [comment]
Question, @mello99 -- what exactly is the task? Are you (and Gail) just suggesting that we change the language of the phrase "Jump to a point in the index"? If so, I'd suggest we change the language to "Choose year." Will assign to Philippe to do that: it'll be in messages.xml, Philippe, though I don't recall the directory offhand. 

This small language change is also a good candidate for contributing back to the Mirage2 theme on the DSpace project. Will assign to @pgray64 to change this phrase _and_ to create a pull request for the main DSpace project, which it will be good for him to learn to do. 

Add a comment, @mello99, if there are other things that need to happen for this issue to be fixed besides that language change.

**Comment by mello99** [comment]
Hi @amandafrench , according to Gail, the user was confused by this functionality because all of the searchable years weren't showing up (the index, after a certain point, eventually starts going back in increments of 5 and 10 years). Because all of the years weren't showing up, the user assumed that there was no content created in the years between the 5 and 10-year increments. She eventually ascertained that she could just enter a year in the "Or type in a year" box to the right of the index.

I suppose we could change the language to "Choose year", or perhaps add a sentence that says "Not all years are listed," or "Starting in XXXX, only 5/10-year increments are displayed, but you can search for a year within that timeframe." That's not the best language, of course, but I can think it over (I'll add it to the backlog).

I'm not sure if we could or would want to display all of the years - I think that would get unwieldy very quickly. Does this answer your question?

**Comment by amandafrench** [comment]
We are not sure what to do about this issue, so we'll close it until further notice.
