### ISSUE TITLE
Maven Build Error - Error loading property file '.../target/dspace_local.properties.properties' 

### ISSUE THREAD

**Issue by AmberPoo1** [VTUL/vtechworks#277]
Hi @keithgee, I have updated the configuration files under "vtlibans_dspace" from git.it.vt.edu, and also get the latest code from Branch: "vt_5_x_dev", but still get the following build error (it seems like "dspace_local.properties.properties" is missing, I cannot find this file anywhere), any ideas about it?

This is the error log:

---

[INFO] DSpace XML-UI (Manakin) ............................ FAILURE [  0.125 s]
[INFO] DSpace XML-UI Mirage2 Theme ........................ SKIPPED
[INFO] DSpace XML-UI Mirage2 Theme :: Local Customisations  SKIPPED
[INFO] DSpace XML-UI (Manakin) :: Local Customizations .... SKIPPED
[INFO] DSpace JSP-UI ...................................... SKIPPED
[INFO] DSpace JSP-UI :: Local Customizations .............. SKIPPED
[INFO] DSpace RDF ......................................... SKIPPED
[INFO] DSpace RDF :: Local Customizations ................. SKIPPED
[INFO] DSpace REST :: API and Implementation .............. SKIPPED
[INFO] DSpace REST :: Local Customizations ................ SKIPPED
[INFO] DSpace SWORD ....................................... SKIPPED
[INFO] DSpace SWORD :: Local Customizations ............... SKIPPED
[INFO] DSpace SWORD v2 .................................... SKIPPED
[INFO] DSpace SWORD v2 :: Local Customizations ............ SKIPPED
[INFO] Apache Solr Webapp ................................. SKIPPED
[INFO] DSpace SOLR :: Local Customizations ................ SKIPPED
[INFO] DSpace OAI-PMH ..................................... SKIPPED
[INFO] DSpace OAI-PMH :: Local Customizations ............. SKIPPED
[INFO] DSpace Assembly and Configuration .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.855 s
[INFO] Finished at: 2016-05-28T12:25:36-04:00
[INFO] Final Memory: 49M/513M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project dspace-xmlui: Error loading property file '/Users/pjing/vtlibans_dspace/dspace/dspace-xmlui/../target/dspace_local.properties.properties' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project dspace-xmlui: Error loading property file '/Users/pjing/vtlibans_dspace/dspace/dspace-xmlui/../target/dspace_local.properties.properties'
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error loading property file '/Users/pjing/vtlibans_dspace/dspace/dspace-xmlui/../target/dspace_local.properties.properties'
    at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:307)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: Error loading property file '/Users/pjing/vtlibans_dspace/dspace/dspace-xmlui/../target/dspace_local.properties.properties'
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.loadProperties(DefaultMavenFileFilter.java:290)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.getDefaultFilterWrappers(DefaultMavenFileFilter.java:205)
    at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:161)
    at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:301)
    ... 21 more
Caused by: java.io.FileNotFoundException: /Users/pjing/vtlibans_dspace/dspace/dspace-xmlui/../target/dspace_local.properties.properties
    at org.apache.maven.shared.filtering.PropertyUtils.loadPropertyFile(PropertyUtils.java:65)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.loadProperties(DefaultMavenFileFilter.java:284)
    ... 24 more

**Comment by kayiwa** [comment]
Could you please confirm what steps you did? Did you run a `vagrant destroy` and then `vagrant up` and get this error?

If not thank you for doing this. If you did run `vagrant destroy` and then `vagrant up` you should have a symbolic link to that file as this step describes.

https://git.it.vt.edu/it-services/vtlibans_dspace/raw/master/provisioning/roles/dspace/tasks/maven_setup.yml

Pull requests welcome from anyone who understands the maven weirdness.

Cheers

**Comment by AmberPoo1** [comment]
Hi @kayiwa, it's not a VM issue. It happened in the build step which builds dspace target classes,  before start virtual machine.

**Comment by AmberPoo1** [comment]
@kayiwa, ok, I will try vagrant destroy and then vagrant up. Thanks.

**Comment by kayiwa** [comment]
I'm confused. Where are you doing the building? on your computer? 

```
I have updated the configuration files under "vtlibans_dspace" from git.it.vt.edu, and also 
```

Could you explain how what you mean ^^^ 

In the meantime you can fix that by running 

```
$ ln -sf $PWD/dspace_local.properties $PWD/dspace_local.properties.properties
```

In the directory where you run the `mvn clean...` command.

**Comment by kayiwa** [comment]
The steps have changed a little bit so you can't do this on `autopilot` 

I have another hour online and can be reached via IM if you run into problems.

I forgot to say make sure you run `git pull` before you run `vagrant up`

**Comment by AmberPoo1** [comment]
Well, I just want to say all my code is the latest version. And I want to know how to generate "dspace_local.properties.properties" on local host, I will try your solutions. :-)

The steps to run dspace on the vm is (This error happened in step 1. ):
1. build dspace target classes on local host
2. run "vagrant up" to open vm
3. resynchronize the built code on your local host to the vm
...

**Comment by kayiwa** [comment]
the file is here. You will need to replace the `{{ }}` content with the variables. 

https://git.it.vt.edu/it-services/vtlibans_dspace/raw/master/provisioning/roles/dspace/templates/build.properties.j2

**Comment by AmberPoo1** [comment]
Ok, thanks, @kayiwa

**Comment by alawvt** [comment]
@AmberPoo1, the instructions, https://git.it.vt.edu/it-services/vtlibans_dspace/blob/master/README.md, have changed. I just fixed the path for this step that links the properties file, 

```
Then, from the vtlibans_dspace directory, build the DSpace project using Maven.
$ cp templates/dspacedevvm.local.vt.edu.properties dspace/dspace_local.properties
$ cd dspace
$ git checkout vt_5_x_dev
$ ln -sf $PWD/dspace_local.properties $PWD/dspace_local.properties.properties
$ mvn clean package -Denv=dspace_local.properties -Dmirage2.on=true

Make sure you do the previous provisioning/secret_things step.
```

**Comment by alawvt** [comment]
I was finally able to build the new vagrant box. Please destroy and rebuild yours. Please note carefully the updated README and notes above.

**Comment by alawvt** [comment]
Update - @kayiwa made another update to the vagrant box. After I built the vagrant box, I switched to another commit, rebuilt and there were no communities listed on the home page. I destroyed and am rebuilding vagrant again. 

@keithgee, do you have any idea why the communities wouldn't show up on the home page? I tried `reindexing, sudo -u vtechworks ./dspace index-discovery -b`, to no avail. The items are there because I can see them in the submissions list when I'm logged in.

**Comment by alawvt** [comment]
@keithgee, never mind. @kayiwa  figured out the issue. 
"When we ran the vagrant rsync the /var/local/vtechworks/src/dspace/dspace/target/dspace-installer directory is then owned by the user vagrant I have updated the documentation here. https://github.com/VTUL/vtechworks/wiki/3.-Making-changes-on-the-local-development-environment to reflect this. The reason the build was running quickly is because it was getting the build info from the vagrant user instead of the vtechworks user." 
@AmberPoo1 and I will be testing the box and instructions. Hopefully things are ok now.

**Comment by alawvt** [comment]
@keithgee, even with the changes noted above, I'm still having the issue with no communities after rsyncing with a new branch.

**Comment by alawvt** [comment]
@keithgee, never mind again. @kayiwa figured out the next issue. He changed the solr port from 8081 to 8080 in templates/dspacedevvm.local.vt.edu.properties. It all seems to work now.

Everyone, please be sure to pull the latest commit for https://git.it.vt.edu/it-services/vtlibans_dspace and use the latest instructions on that page.

**Comment by AmberPoo1** [comment]
Hi @kayiwa , when running "vagrant up", always get this error:

TASK [ant : download the ant binary] *******************************************
fatal: [vtechworksvm]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.bz2, timed out"}

Is there any solution for this? the previous installations are successful, such as Java 8.

**Comment by kayiwa** [comment]
always helpful if you say what you did. When you say this _always_ happens to you. I am assuming this is  after a `vagrant destroy` and then `vagrant up`. In which case you have really miserable luck. I've run (I can recall) at least 3 of those today and experienced no problem. 

this makes me think you have a cached attempt that you are running.

Ideally try this (humor me) completely delete anything you've done on this directory. 

Then start completely fresh. Intermittent failing will happen but "always" (apologies for being pedantic) failing suggests caching may be playing a role.

Cheers.

**Comment by AmberPoo1** [comment]
Each time I run "vagrant destroy" and then "vagrant up", and got this error, 3 times.

**Comment by AmberPoo1** [comment]
Thanks, @kayiwa , but where and how to clear the cached stuff?

**Comment by kayiwa** [comment]
are you on campus when this happens? from your terminal can you run 

`wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.bz2`

Can you hangout right now?

**Comment by AmberPoo1** [comment]
I have gotten off work today. I can test it and hangout if you are free tomorrow. Thanks.

**Comment by AmberPoo1** [comment]
Hi @kayiwa, I tried to get my virtual box work today, I updated all the tools needed according to our instructions, I did "vagrant destory", then "vagrant up". Other tools such as git, java installed successfully until I encountered the ant installation error as follows:

```
TASK [java8 : Install Oracle Java 8] *******************************************
changed: [vtechworksvm] => (item=[u'oracle-java8-installer', u'ca-certificates', u'oracle-java8-set-default'])

**TASK [ant : create ant directory] **********************************************
fatal: [vtechworksvm]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
    to retry, use: --limit @provisioning/provision.retry

PLAY RECAP *********************************************************************
vtechworksvm               : ok=13   changed=7    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.**
```

My Ansible version is 2.1.0.0, I searched online which said some Ansible versions may contain bugs with the ssh (https://github.com/ansible/ansible/issues/13401). Is it the reason of my error?

**Comment by alawvt** [comment]
My vagrant box built with Ansible 2.0.2.0.

**Comment by kayiwa** [comment]
Log into the VM with 

```
vagrant ssh
```

manually download the file

```
wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.bz2
```

unarchive the file

```
bzip2 -d apache-ant-1.9.6-bin.tar.bz2 | tar xvf -
```

create the ant directory

```
sudo mkdir /opt/ant
```

move the unarchived directory in there

```
sudo mv apache-ant-1.9.6 /opt/ant/
```

create a symbolic link to the binary

```
sudo ln -sf /opt/ant/apache-ant-1.9.6/bin/ant /usr/local/bin/ant
```

exit the vm

```
exit
```

run 

```
vagrant provision
```

**Comment by AmberPoo1** [comment]
@kayiwa, thanks, I will try this.

**Comment by kayiwa** [comment]
one more thing.  For good measure temporarily block the ant role

by deleting it from `provision.yml` so it goes from looking like this

```
---
- name: provision vtechworks repo
  hosts: all
  user: "{{ ansible_user }}"
  vars_files:
    - secret_things.yml
    - site_vars.yml
  gather_facts: true
  pre_tasks:
  - debug: var=hostvars[inventory_hostname]
  roles:
      - { role: common, become: yes }
      - { role: java8, become: yes }
      - { role: ant, become: yes }
      - { role: apache2, become: yes }
      - { role: postgresql, become: yes }
      - { role: tomcat7, become: yes }
      - { role: dspace, become: yes }
```

to 

```
---
- name: provision vtechworks repo
  hosts: all
  user: "{{ ansible_user }}"
  vars_files:
    - secret_things.yml
    - site_vars.yml
  gather_facts: true
  pre_tasks:
  - debug: var=hostvars[inventory_hostname]
  roles:
      - { role: common, become: yes }
      - { role: java8, become: yes }
      - { role: apache2, become: yes }
      - { role: postgresql, become: yes }
      - { role: tomcat7, become: yes }
      - { role: dspace, become: yes }
```

**Comment by AmberPoo1** [comment]
I run the vagrant box built  on a MacBook and finally succeed, however, there were two problems in the whole process when running "vagrant up"":
1) ant download and install failure, @kayiwa has given a walk-around solution;
2) got a path-error problem when executing the "tomcat_setup.yml" task (other machines don't have such problem, don't know why), **the solution is modifying line 7 in the "tomcat_setup.yml". 
From "template: src=templates/server.xml.j2 dest=/etc/tomcat7/server.xml" 
to      "template: src=server.xml.j2 dest=/etc/tomcat7/server.xml"**

The error message is as follows (the path of server.xml is generated incorrectly):

TASK: [dspace | tomcat | configure server.xml] *******************************\* 
fatal: [vtechworksvm] => input file not found at /Users/alfrench/vtlibans_dspace/provisioning/roles/dspace/templates/templates/server.xml.j2 or /Users/alfrench/vtlibans_dspace/provisioning/templates/server.xml.j2

**Comment by kayiwa** [comment]
did you run `git pull` before running `vagrant up` 

I see the file here.  

https://git.it.vt.edu/it-services/vtlibans_dspace/blob/master/provisioning/roles/dspace/templates/server.xml.j2

./fxk

**Comment by AmberPoo1** [comment]
No, I didn't run git pull before vagrant up.

**Comment by amandafrench** [comment]
Sounds like this issue is closable -- @AmberPoo1 does have a working environment on my laptop at the moment, and it sounds like the key to getting it working on her desktop is to 1) make sure it's a neutral, unmodified environment (maybe even reinstall the OS??) and 2) be sure to pull the latest from the vtlibans_dspace project on GitLab. 

Any further issues with vtlibans_dspace should be reported on GitLab in that project.
