### ISSUE TITLE
Test and deploy Irish Setter sprint

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#283]
Write an Irish Setter sprint testing plan. 
Test on vtechworks.dev.

**Comment by alawvt** [comment]
The test plan is in Google Drive at Dspace_5.5_April_28_June_3_Irish_Setter_Testing. I have finished all the non-Elements tests on vtechworksdev and they all pass.  
I have written two possible tests for Elements:
- Check the myriad mapping changes
- Check that the Elements upload functionality still works

@amandafrench, what do you want to about testing Elements?

**Comment by mello99** [comment]
Hi, @alawvt , @amandafrench , and @keithgee , I tried to deposit 4 items from Elements (ed.lib.vt.edu) into VTW Dev and all of the deposits failed. I got a message in Elements for each that read "The repository experienced a problem and indicated failure of the file upload." See the [testing spreadsheet](https://docs.google.com/spreadsheets/d/1zxlgMRBcAO39rjJ6zZGAjE1FcVHQzaqMnz39Qu98ozQ/edit#gid=0) for more info. Should I contact Keith B. about this, or is this solely in our hands? Thanks.

**Comment by alawvt** [comment]
@mello99, thank you for testing Elements. I'm sorry I can't help with Elements-- @amandafrench, @keithgee, TeamDynamix?

**Comment by keithgee** [comment]
I'll open a separate GitHub issue for the problem that @mello99 mentioned with Elements deposits.

**Comment by alawvt** [comment]
@keithgee compared the Elements configuration files on GitHub and vtechworks.dev, https://github.com/VTUL/vtechworks/issues/290, and they are identical. Testing is complete on vtechworks.dev.  
@amandafrench, the Irish Setter changes are ready to deploy to pprd.

**Comment by amandafrench** [comment]
Okay, will create pprd deployment branch, thanks @alawvt.

**Comment by amandafrench** [comment]
Done: have asked @kayiwa to deploy.

**Comment by amandafrench** [comment]
Both @mello99 and @alawvt can test this on pprd: assign it to me for deployment to production when it's done.

**Comment by alawvt** [comment]
I have completed testing the non-Elements changes and they all passed. I did note in the backlog that the contact page, http://vtechworks.pprd.lib.vt.edu/contact, lists `vtechworks@dla.lib.vt.edu`, which I believe should be changed to `vtechworks@vt.edu`.

**Comment by alawvt** [comment]
The Irish Setter changes have been deployed to production. All the non-Elements changes are ok except `mail.helpdesk = vtechworks-request-copy@vt.edu` has not been implemented yet. I submitted a TeamDynamix request for that.

**Comment by alawvt** [comment]
After the email meeting today, the helpdesk has been disabled. All requests go directly to the eperson associated with the item. For etds, the eperson has been changed from etd-submit@dla.lib.vt.edu to vtechworks-request-copy@vt.edu. vtechworks-request-copy@vt.edu is now receiving requests for ETDs. Therefore, all tests of non-Elements changes have passed.

**Comment by amandafrench** [comment]
@mello99 Can you close this issue after you've spot-checked Elements deposit on production today, please? Thanks!

**Comment by mello99** [comment]
Yep, will do!

**Comment by mello99** [comment]
Finished testing. No surprises, nothing different from the DEV testing. Thanks, all!
