### ISSUE TITLE
Elements deposits broken on VTechWorks Dev

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#284]
@mello99 has tried four deposits from ed.lib to VTechWorks Dev via the Elements Repository tools, and received an error on each one. The deposits were unsuccessful.

**Comment by keithgee** [comment]
There is a parameter in dspace.cfg that specifies the handle of the collection where new items from Elements should be deposited.
On vtechworks.dev, this has reverted to an incorrect collection handle:

```
publications.specifiedcollectionmapper.collection = 123456789/70861
```

The timestamp on the dspace.cfg file is June 6.

I believe that this parameter should match what we have in source control, on our vt_5x_dev branch, instead:

```
publications.specifiedcollectionmapper.collection = 10919/70873
```

**Comment by mello99** [comment]
Hi @keithgee , thanks so much for looking into this. When you think it's ready to be retested, could you let us know on GitHub? Thanks again!

**Comment by keithgee** [comment]
@mello99 I requested on talk.lib for @kayiwa to change the parameter on dev and restart Tomcat so that it can be tested again.

**Comment by mello99** [comment]
@keithgee , okay, sounds good, I'll try again in about 2 hours (I'm guessing that should be enough time).

**Comment by mello99** [comment]
I heard through @alaw that @kayiwa said that I could retest. I just tried redepositing a conference item and a journal article and they both failed :(. I'll keep going.

**Comment by keithgee** [comment]
The dspace.cfg file has been repaired and we've just tested two deposits successfully.
*\* Closing

**Comment by mello99** [comment]
Just retested, @keithgee , and all of the items were accepted and deposited in VTW Dev. Below are their handles:

1) http://hdl.handle.net/10919/71320
2) http://hdl.handle.net/10919/71319
3) http://hdl.handle.net/10919/71318
4) http://hdl.handle.net/10919/71321

There are some issues with the metadata that I thought I addressed by adding all of the fields to the dspace config file, but I'll create another issue for that. Titles also appear twice on the records' homepages (again, I'll create an issue for this). Thanks so much for your help on this!

**Comment by keithgee** [comment]
Okay, thanks @mello99.

**Comment by keithgee** [comment]
I updated the links above in your comment to point to vtechworks.dev. instead of hdl.handle.net. There's a canonical url parameter on dev that also is not what it should be right now.
