### ISSUE TITLE
Metadata duplication occurring for Elements deposits (VTW Dev)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#286]
Hi everyone, I thought I corrected this issue in the DSpace config file by adding all of the metadata elements that we planned to use, but there continues to be metadata element duplication in the Elements records that were deposited into VTW Dev. Below are the URLs for the items' full records:

1) http://vtechworks.dev.lib.vt.edu/handle/10919/71319?show=full
2) http://vtechworks.dev.lib.vt.edu/handle/10919/71321?show=full
3) http://vtechworks.dev.lib.vt.edu/handle/10919/71320?show=full
4) http://vtechworks.dev.lib.vt.edu/handle/10919/71318?show=full

It looks like I'll have to go back into the DSpace config file. I don't know if I added the metadata fields to the right place in that file (or if that branch was ever merged). Thanks so much!

**Comment by mello99** [comment]
Hi, @keithgee , I'm going to assign this to you, if you don't mind, because I just checked the DSpace config file and all of the duplicative elements are in there (at least _most_ of them are - I did a cursory search, so I may have missed some). I'm a bit lost as to what's happening, but I'll keep thinking. Thanks so much for your help getting Elements talking to DEV earlier!

**Comment by keithgee** [comment]
@mello99 please ask ITS to restart Tomcat on vtechworks.dev, and then test again. The config file on dev also appears correct, but Tomcat may not have been restarted since the latest update.

**Comment by mello99** [comment]
Hi @keithgee , I just put in a TD request and asked them to restart Tomcat on vtechworks.dev. Thanks for addressing the earlier issue with the duplicate titles, and take care!

**Comment by mello99** [comment]
@kayiwa restarted Tomcat. Metadata element duplication is still occurring (see http://vtechworks.dev.lib.vt.edu/handle/10919/71324?show=full). There's also another issue involving Elements displaying the wrong URL for associated publications - I'll create an issue for that.

**Comment by mello99** [comment]
@keithgee I'd also like to mention that I put in a support ticket on the Elements website for a related issue and they're reviewing the crosswalk; maybe they'll find something wacky in there that will bring this to an end

**Comment by mello99** [comment]
So, in case neither we nor Symplectic can identify the issue that's causing the duplicative metadata elements, I've created a new branch called "elements_original_xwalk" that contains the default, unedited XSLT that came with the Elements toolkit (this was the original Elements toolkit that we installed - it may have changed since April, but I was not able to find the newer version of the toolkit WITH the XSLT files - the "elements-5.1.0.921-x86.zip" file didn't have them). 

My reasoning is that, if it comes to this (and I hope it doesn't), we may have to revert to an unedited version of the XSLT to resolve the duplication (or at least determine that the issues aren't a result of the edits I made to the crosswalk). I created a new branch just for this and didn't alter anything else - just wanted to clarify that. Thanks.

**Comment by keithgee** [comment]
Okay. I'm not seeing the problem on efarqa/pre-prod, though. I'm not sure what's different.

**Comment by keithgee** [comment]
@mello99 it's working now. The dspace.cfg had some trailing white space in the section with this entry:

```
publications.metadata.authority-list = \
```

All of the lines in that section end with a "\" character. But on vtechworks.dev there were some spaces after the slash on some of those lines. When I took out the extra spaces, that resolved the issue.

I looked in the code on GitHub and there isn't any trailing whitespace in this section (you can double-check me if you want) so I think that it might have been inadvertently added on dev only when Francis and I were manually editing the file yesterday.

Fixed.
***Closing

**Comment by mello99** [comment]
Trailing whitespace!!! It's the little things that kill, lol. Thanks so much for figuring this out!
