### ISSUE TITLE
Create list of correct values for dspace.cfg and foo.properties for each server

### ISSUE THREAD

**Issue by kayiwa** [VTUL/vtechworks#288]
Thanks for filling out the values that change on dspace.cfg based on server (we will ignore LDE for now)

I'm starting out with the ones I know

Thanks for the correct entries. 

```
dspace.hostname = 
dspace.baseUrl =
dspace.url =
db.username =
db.password =
mail.allowed.referrers =
assetstore.dir.1 =
assetstore.incoming = 1
handle.canonical.prefix = 
```

**Comment by keithgee** [comment]
```
db.url
```

**Comment by amandafrench** [comment]
Hi @alawvt -- turns out that issue #309 is related to this issue, so I can't just update dspace.cfg and push it to GitHub and ask @kayiwa to deploy. Instead, what we need to do is create a full list on git.it.vt.edu of the correct values for each of these items. I went ahead and changed "http" to "https" for dspace.url and dspace.baseUrl in all the files I found those parameters in on vtlibans_dspace, and I removed a trailing slash from those files, too. 

I am also going to update all the files in vtlibans_dspace, and we'll need to pull again from there.

**Comment by amandafrench** [comment]
I think we actually probably need to assign this to @keithgee, and I think we need to get this straightened out before we deploy again. Keith, could you fill out the values at https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/home as soon as you can? @alawvt, I don't think we need to replicate it in the Documentation project.

**Comment by alawvt** [comment]
@amandafrench, I am able to access the servers and added the values in the GitLab wiki page. 

@kayiwa, the settings for each server are in https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/home. For dspace.url and dspace.baseUrl, dev and pprd have HTTP and prod has HTTPS . There is also a difference in assetstore.incoming for the three.

**Comment by keithgee** [comment]
So, do you all want me to do anything on this, or not?

**Comment by amandafrench** [comment]
You could look it over and make sure it's correct! If so, then you can close it -- @alawvt went ahead and did it.

**Comment by keithgee** [comment]
Okay @amandafrench. Am I checking to see that that the documentation matches the current values on the servers, even if the values are incorrect and will break things?  Or should I change the documentation to what the values should actually be, even if the values on the servers are currently different?

That sounds like a silly question, probably, but I wanted to make sure I understand what we're doing.

**Comment by keithgee** [comment]
Basically - are we trying to document the way things are now, or the way they should be?

**Comment by amandafrench** [comment]
Oh, the latter, I'd say -- change them to what they should actually be. Thanks.

**Comment by keithgee** [comment]
I've updated the wiki page with desired values for configurations that are different across servers. 

@alawvt wanted me to be sure to mention to @kayiwa that some of the values in the wiki page don't match the values currently on the servers.

_**Closing *_*
