### ISSUE TITLE
I tried to map an item to another collection and it disappeared!!!

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#300]
Hi all, I tried to map an item from one collection to another using the "Item Mapper" function (this was an item authored by Nancy Dudek about ETDs) and the item just disappeared altogether from VTechWorks!!! I was never asked to delete the item at any point. I can't find the item in DEV or PPRD, and I have no idea what happened or why. Any help would be much appreciated. Thanks so much, and take care.

**Comment by mello99** [comment]
Ok, pretty sure this is an indexing issue - the handle still works (phew): http://hdl.handle.net/10919/71365. I did notice, however, that when I typed the handle into my browser, the URL that returned was the following:

vtechworks.lib.vt.edu//handle/10919/71365

That doesn't look quite right; any ideas as to what caused it? Thanks again.

**Comment by mello99** [comment]
This appears to be a network issue, so I'm closing it (I reported the double backslash issue on TeamDynamix). I can't log in to VTUL Talk, for some reason, which I also reported.

**Comment by alawvt** [comment]
The handle issue has been resolved. 

dspace.cfg was corrected from `dspace.url = https://vtechworks.lib.vt.edu/` to `dspace.url = http://vtechworks.lib.vt.edu`.
