### ISSUE TITLE
Fix display of Sherpa/Romeo messages

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#304]
In the submission form, if you add an ISSN as an identifier, at the bottom of the next page (file upload step) of the submission form will be a Sherpa Romeo message. We recently lengthened those messages and the text box should wrap for multiple lines of text. (Note: we may also want contribute this to the main DSpace project.)
![sherparomeonowrap](https://cloud.githubusercontent.com/assets/13037168/16308112/b812f45c-3931-11e6-9103-c2073c99e8d7.png)

**Comment by pgray64** [comment]
I think the first looks better than the second
![screenshot](https://cloud.githubusercontent.com/assets/7339589/16317665/14b870ba-395a-11e6-9021-dd75af7c90cf.png)
![screenshot2](https://cloud.githubusercontent.com/assets/7339589/16317807/8b02234c-395a-11e6-97af-1a70a5444a6e.png)

**Comment by amandafrench** [comment]
Yes, the first does look much better! If you can do that for all the colors in messages.xml, please make it so.

**Comment by pgray64** [comment]
Fixed in pull request #305
