### ISSUE TITLE
ClamAV issue

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#307]
More detail in https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/issues/2

**Comment by amandafrench** [comment]
I've just been updating the backlog, so I think what was on line #118 has changed. This was the ClamAV issue, correct, @alawvt? Either way, can you please edit the subject line of this issue? Thanks.

**Comment by alawvt** [comment]
See appropriate line of Technology Backlog

**Comment by pgray64** [comment]
Assuming the ClamAV daemon is installed and running on port 3310, the only code change is to set a boolean flag to true in `dspace/config/modules/submission-curation.cfg`.

Don't know if that's the case, because otherwise it breaks submissions.

**Comment by pgray64** [comment]
ClamAV is failing on the submission form file upload for recognized formats > 3.6 mb and unrecognized formats > 2 mb. Its odd, because I configured the ClamAV daemon with high size limits and timeouts.

**Comment by pgray64** [comment]
ClamAV is failing to detect a test file that is designed to look like a virus to scanners (including ClamAV). Uploads are succeeding with all filetypes and sizes though.

**Comment by pgray64** [comment]
Pull Request #314
