### ISSUE TITLE
Fix insufficient contrast between the text and links

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#308]
Fix insufficient contrast between the text and links in paragraphs, for instance the home page intro has color rgb (51, 51, 51). The links are rgb (26, 0, 0). Requirements: http://webaim.org/blog/wcag-2-0-and-link-colors/

**Comment by pgray64** [comment]
For AA Accessibility 

> A 3:1 contrast between the link text color and the surrounding non-link text color.

This is not possible without changing links to have pastel colors. VT maroon and pure black is 1.56:1.

Both link and nonlink text still has to have 4.5:1 contrast to the white background, further limiting choices.
Alternative is to underline links, which would still look strange in my opinion

**Comment by alawvt** [comment]
It would be ok if the body text were black for maximum contrast. Links will have to be lighter if we don't want them underlined. Please mock up a few possibilities: light maroon (contradiction in terms, I know), a blue, etc. Page 7 of 2015 VT Brand Guide, https://www.branding.unirel.vt.edu/2015-brand-guide.pdf, has official colors that you trial.

**Comment by pgray64** [comment]
Passes both Link:Text = 3:1 contrast and Link:background = 4.5:1 contrast
Links: c7510e (A little darker than VT orange ff6600)
Text: 2e2e2e (A little lighter than current 33333)

<img width="1284" alt="screen shot 2016-07-11 at 2 57 58 pm" src="https://cloud.githubusercontent.com/assets/7339589/16742943/0b561fbe-4778-11e6-9bcb-eae27377ed57.png">

**Comment by pgray64** [comment]
984422 links (close to one of VT's secondary web colors) 
2e2e2e text 
Passes both contrast reqs again.

<img width="1054" alt="screen shot 2016-07-11 at 3 09 28 pm" src="https://cloud.githubusercontent.com/assets/7339589/16743274/81022482-4779-11e6-883a-3c3d68ce429b.png">

**Comment by pgray64** [comment]
Links: 557082 An unmodified secondary VT web color
Text: 2e2e2e
Passes both contrast reqs

<img width="1108" alt="screen shot 2016-07-11 at 3 12 53 pm" src="https://cloud.githubusercontent.com/assets/7339589/16743366/fb1f646e-4779-11e6-9ef0-e3d7aae3bc0f.png">

**Comment by pgray64** [comment]
Default boostrap link color: #337ab7
Text: 2e2e2e
Passes both contrast reqs

<img width="1080" alt="screen shot 2016-07-11 at 3 17 37 pm" src="https://cloud.githubusercontent.com/assets/7339589/16743470/a3afd492-477a-11e6-85bf-b4f3bcf14029.png">

**Comment by alawvt** [comment]
I just received a link with more official VT web colors, [Web color palette](http://www.unirel.vt.edu/web/web-guidelines/guidelines-colors.html), linked from [Web guidelines and procedures](http://www.unirel.vt.edu/web/web-guidelines/guidelines-index.html).

**Comment by alawvt** [comment]
@amandafrench, we'd like your feedback on these options or others.

**Comment by amandafrench** [comment]
@alawvt @pgray64 Sorry for my delay! I got really behind on GitHub notifications the last couple of weeks. Hmm, I think https://github.com/VTUL/vtechworks/issues/308#issuecomment-231834844 is my favorite, the second one with the dark orange links. I'd say meeting accessibility guidelines (which is federal law) is more important than meeting university branding guidelines. 

@pgray64, if you haven't already, could you please try out all of the "Reds" and the "Golds" specified at http://www.unirel.vt.edu/web/web-guidelines/guidelines-colors.html as link colors and see if you can get those to pass the font contrast accessibility guidelines? If not, then let's go with your number 2 above.

**Comment by pgray64** [comment]
Passes both AA requirements
Text: 000000
Links: a86107
<img width="600" alt="screen shot 2016-07-29 at 10 32 49 am" src="https://cloud.githubusercontent.com/assets/7339589/17251734/f624afbc-5577-11e6-98f0-7c939fd5760d.png">

**Comment by pgray64** [comment]
Passes both AA
Text: 000000
Links: 8c5206
<img width="600" alt="screen shot 2016-07-29 at 10 35 47 am" src="https://cloud.githubusercontent.com/assets/7339589/17251823/3cd1baae-5578-11e6-9636-98ebc4ad6b25.png">

**Comment by pgray64** [comment]
All the other reds and golds fail and are not close to meeting contrast reqs

**Comment by amandafrench** [comment]
Ugh, bummer. None of the solutions look all that great, but I can live with Text: 000000
Links: a86107 above. Make it so, and we'll incorporate it at the end of August.

**Comment by pgray64** [comment]
Contrast changes made with pull request #358.
Text: 000000
Links: a86107

In my opinion _links: 557082, text: 2e2e2e_ looks better.
<img width="400" alt="screen shot 2016-07-11 at 3 12 53 pm" src="https://cloud.githubusercontent.com/assets/7339589/16743366/fb1f646e-4779-11e6-9ef0-e3d7aae3bc0f.png">

**Comment by amandafrench** [comment]
@pgray64 Ah, and that one _is_ a secondary VT color too, correct? I forgot about that one! I agree -- that one does look better. You can change it on pull request #358. Thanks for the input.

**Comment by amandafrench** [comment]
@pgray64 Also you can close this issue once you've updated the pull request.

**Comment by pgray64** [comment]
Yes, it's a VT secondary color

**Comment by pgray64** [comment]
Updated pull request #358 to links: 557082, text: 2e2e2e.

**Comment by alawvt** [comment]
I think the links in #557082 are a very greyish blue and don't contrast enough with the black text. 

Here are two more attempts:
#4078C0 (GitHub blue links)
![4078c0_link_color](https://cloud.githubusercontent.com/assets/13037168/17637107/6a7e7036-60af-11e6-9e29-b8bf08f42b9c.png)

#DD4048 (The same hue as the Hokie maroon but lightened - winds up rather orange-y)
![dd4048_link_color](https://cloud.githubusercontent.com/assets/13037168/17637144/a36ac214-60af-11e6-9542-5fb313c5f0ac.png)

**Comment by alawvt** [comment]
The gold (8c5206) wins.

**Comment by amandafrench** [comment]
Glad we got a solution that passes both federal accessibility & university branding guidelines, though I will admit that it's not very attractive. Will be glad when the university rebrands, though I know it'll take a long time. Thanks for your work on this, @pgray64 and @alawvt.
