### ISSUE TITLE
Reset password is broken

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#309]
A user reports, and I have confirmed, that the Forgot Password flow is broken. Here's what happens: 

1) Click "Forgot password" link on https://vtechworks.lib.vt.edu/password-login page
2) Be taken to https://vtechworks.lib.vt.edu/forgot 
3) Enter email address, get "Verification email sent" confirmation page 
4) Receive  "Change Password Request" email with link and token such as http://vtechworks.lib.vt.edu/forgot?token=58242059ce8ebc46f131dd7f0c2d3008 
4) Click link with token
5) Be taken to "Reset password" page with token at e.g., http://vtechworks.lib.vt.edu/forgot?token=58242059ce8ebc46f131dd7f0c2d3008  (so far so good, apparently)
6) Enter new password information and click "Reset password" (here's where it breaks down)
7) Be taken to "New User Registration" page at https://vtechworks.lib.vt.edu/register instead of to a confirmation page. (BADNESS)

Note that I also tested whether the Reset Password page will validate the password with "Retype to confirm," and it doesn't -- it still just takes you to the New User Registration page. Confirmed in both Firefox and Chrome. Seems to me like the token is crap. 

![screenshot 2016-06-29 11 54 31](https://cloud.githubusercontent.com/assets/227453/16459282/48f8d082-3df0-11e6-840a-a0a6d63ca60b.png)

**Comment by amandafrench** [comment]
Should add, too, that the password itself is not changed, which isn't surprising.

**Comment by keithgee** [comment]
Here are the current values in dspace.cfg for DSpace URLs:

```
# DSpace base host URL.  Include port number etc.
dspace.baseUrl = http://vtechworks.lib.vt.edu

# DSpace base URL.  Include port number etc., but NOT trailing slash
# Change to xmlui if you wish to use the xmlui as the default, or remove
# "/jspui" and set webapp of your choice as the "ROOT" webapp in
# the servlet engine.
dspace.url = http://vtechworks.lib.vt.edu
```

I believe that @kayiwa corrected a similar issue in Spring of 2015 by changing these to "https" instead of "http". We will need to be careful so that a trailing slash is not added while editing, as that recently contributed to a separate issue.

**Comment by keithgee** [comment]
I've modified dspace.cfg, live on the server, and will request a restart.

```
# DSpace base host URL.  Include port number etc.
dspace.baseUrl = https://vtechworks.lib.vt.edu

# DSpace base URL.  Include port number etc., but NOT trailing slash
# Change to xmlui if you wish to use the xmlui as the default, or remove
# "/jspui" and set webapp of your choice as the "ROOT" webapp in
# the servlet engine.
dspace.url = https://vtechworks.lib.vt.edu
```

**Comment by keithgee** [comment]
Francis has restarted Tomcat, and password reset is working now.
**\* closing ***

**Comment by amandafrench** [comment]
Great! Thanks.

**Comment by alawvt** [comment]
This needs to be fixed on vtechworks.dev, too. I am filing a TeamyDynamix request. (pprd seems ok.)

**Comment by amandafrench** [comment]
@alawvt It's broken just because dspace.cfg is out of sync with the other servers. All we need to do is make sure the dspace.cfg file is correct locally, push that to GitHub, and then deploy it in the usual fashion to dev and pprd. I'll make sure that the changes @keithgee has entered above are in the file properly. 

There is a "hotfix" protocol that we outlined at https://github.com/VTUL/vtechworks/wiki/8.-Deploying-code-changes but we haven't been following it. I think I'll break it out into a separate wiki page and ask everyone to review it.
