### ISSUE TITLE
Has the latest XSLT file been deployed to DEV and PPRD?

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#315]
Hi @kayiwa and @amandafrench , do you know if the latest XSLT file has been deployed to DEV and PPRD? I clearly see that the latest XSLT file is included in the vt_5_x_dev branch, but when I look at the vt_5_x_dev_deploy and vt_5_x_pprd_deploy branches, the latest XSLT file isn't in either of them (sorry if I'm misinterpreting things - GitHub's organization is still an enigma to me). I just wanted to make sure that the latest XSLT had been uploaded - I tried testing the new features today and this evening and they all failed :(. Thanks, take care.

**Comment by alawvt** [comment]
Melissa,

You were looking in the right branches. I don’t think the Jaguar changes have been deployed yet. (We have to get this dspace.cfg stuff straight first.)

Thanks,

Anne

**Comment by amandafrench** [comment]
No, we haven't deployed yet -- will let you know when we have. Sorry for chopping and changing.
