### ISSUE TITLE
Take off Search Stats and Workflow Stats from home page

### ISSUE THREAD

**Issue by pgray64** [VTUL/vtechworks#316]

**Comment by pgray64** [comment]
@alawvt @amandafrench Do non-admins need to see search and workflow stats at all? If not, its an easy fix to remove those from home page, but non-admins won't be able to see those stats elsewhere too.

**Comment by alawvt** [comment]
Yes, you can remove those links for all users.

**Comment by pgray64** [comment]
Resolved with Pull Request #318
