### ISSUE TITLE
Increase number of items on statistics-home to 100

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#319]
The link on the home page that goes to Usage Statistics for the whole repo at http://vtechworks.lib.vt.edu/statistics-home shows only the top ten most-visited item records. I'd like it to show more, preferably 100.

**Comment by pgray64** [comment]
As of now, almost every option for xmlui's statistics view is hardcoded in the Java source. I'm modifying the java so these options can be changed via usage-statistics.cfg instead.

**Comment by alawvt** [comment]
That sounds good, @pgray64.

**Comment by pgray64** [comment]
Addressed with pull request #335.
Number of results for usage stats is now configurable instead of hardcoded in java. 

I could make similar changes for the other stats (search and workflow) as well. Figured a separate pull request would be better for that.

**Comment by alawvt** [comment]
Works, thank you!
