### ISSUE TITLE
Display DSpace usage stats on home page

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#32]
For all users, including those who are not logged in. See https://redmine.lib.vt.edu/issues/214 

Note too that there was a request for explanatory text, as well: https://redmine.lib.vt.edu/issues/144 -- seems a good idea to include that. If you want me to write it, @keithgee, let me know: otherwise please just do something short and sweet yourself.

**Comment by keithgee** [comment]
@amandafrench let's make the explanatory text a separate issue in the backlog and handle it in another sprint. I've already finished the task with the original scope.

**Comment by keithgee** [comment]
See pull request #34

**Comment by amandafrench** [comment]
Okay, will add that to backlog! Man that was fast, @keithgee.

**Comment by amandafrench** [comment]
And bad @amandafrench for adding to the scope. :)

**Comment by amandafrench** [comment]
I've suggested in https://github.com/VTUL/vtechworks/wiki/Issue-tracking that we close issues upon pushing a fix to GitHub that we *think* will solve the issue. We can always reopen it if, after testing, it isn't actually fixed and can't be deployed to production. Therefore closing this, @keithgee, since you submitted a fix in #34.
