### ISSUE TITLE
Write GitLab documentation for how to change case in Content Type fields with SQL commands (e.g., "article" to "Article")

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#323]
The only way we can make repository-wide data changes is with SQL commands. We'd like to start creating a library of such commands to do particular tasks -- sort of a recipe book. One common issue is that since the search filters are case-sensitive, things like "Article" and "article" are perceived as different types. We'd like a recipe for changing that (all types should be capitalized in sentence case, so "Article" and "Journal article" are correct).

**Comment by pgray64** [comment]
Adding the custom SQL functions as I make them on the [SQL Resources Wiki](https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace)

**Comment by pgray64** [comment]
Function to change specified metadata field values to sentence case is done. [SQL Resources Wiki](https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace).

**Comment by amandafrench** [comment]
Great! I think we'll test these next week / month on development & pre-prod before we run them on production to clean up our actual data. Thanks!
