### ISSUE TITLE
Write GitLab documentation for how to move text from one field to another SQL commands (e.g., "Text" from dc.type to dc.type.dcmitype)

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#324]
Related to #323

**Comment by amandafrench** [comment]
This task isn't specifically addressed in https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace, is it? Doesn't look like it to me, but maybe I'm missing something.

**Comment by amandafrench** [comment]
Think I'll close this and #325: let's just run some tests on #323 first.

**Comment by pgray64** [comment]
Completed at
https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace
