### ISSUE TITLE
Write GitLab documentation for how to move a collection from one community to another with SQL

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#325]
Related to #323 and #324. This recipe would be for moving (for example) a collection from one community (or sub-community) to another without changing the handle. Example: moving http://vtechworks.lib.vt.edu/handle/10919/18629 (BioMedCentral) FROM the sub-community http://vtechworks.lib.vt.edu/handle/10919/8195 (Journals) in the community http://vtechworks.lib.vt.edu/handle/10919/25799 (Special Collections) TO the community http://vtechworks.lib.vt.edu/handle/10919/5553 (College of Science).

**Comment by amandafrench** [comment]
Revisit after we test #323.

**Comment by pgray64** [comment]
Finished at: https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace
