### ISSUE TITLE
Add Content Type browse facet to all pages

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#33]
Will apply to the home page but also all collections. 

See https://redmine.lib.vt.edu/issues/293

**Comment by alawvt** [comment]
Content Type has been added as a facet with pull request #47 for the default and homepage but not for the ETD search configuration.

**Comment by keithgee** [comment]
I've verified that Content Type has been added as a facet to the main page, and to the collections, except for ETDs. Some metadata cleanup  of Content Type would  also be useful - e.g. article/Article, Dissertation/dissertation,Image/Photograph/Digital Photographs/Digital photographs.

Closing.

**Comment by alawvt** [comment]
Thanks for testing. Not including Content Type in the ETD collections was intentional. I added ETD Level in its place.

**Comment by amandafrench** [comment]
Agree about metadata cleanup of content types -- have put that in the metadata backlog.
