### ISSUE TITLE
Shouldn't handles with hdl.handle.net resolve to collections?

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#336]
I thought that since collections and communities are assigned handles, the official permalink structure that works for items would work for them as well. Handles are currently working fine for items, but when I attempt to link to the collection https://vtechworks.lib.vt.edu/handle/10919/5540 using the syntax http://hdl.handle.net/handle/10919/5540 the link doesn't work. Is this expected behavior? Have Googled a little but not extensively.

**Comment by keithgee** [comment]
@amandafrench use this instead;
https://hdl.handle.net/10919/5540

or http

**Comment by alawvt** [comment]
I was able to use http://hdl.handle.net/10919/5540 to access this community. (you need an e)

**Comment by amandafrench** [comment]
Huh, it does work now. The lack of 'e' in the comment above was a typo, but I'm almost certain I was spelling it correctly before when it wasn't working. Oh, well. Mysterious, but maybe my fault. Will close. Thanks for testing.
