### ISSUE TITLE
Tested "Report - Technical" and "Report - Annual" on PPRD

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#338]
Hi @amandafrench , I created an item in PPRD called "Findability Test" and gave it the following content types: "Report - Technical" and "Report - Annual". When I typed in "Technical report" and "Annual report" (separately) in the free-text search field, the new item I created appeared first in my search results. 

Additionally, when I used the advanced filters and entered "Technical report" and "Annual report" (separately) in the "Content type" field (I used "Contains"), I was also able to find the item in my search results, though it wasn't at the top (I'm not sure where it was, but it wasn't on the first page of my search results). 

That being said, if I used "Equals" in the "Content type" field for both "Technical report" and "Annual report", the item did not appear at all in my search results (which is understandable).

If anyone would like to test this further (or would like me to test this further), just let me know. Thanks, and take care.

**Comment by amandafrench** [comment]
Thanks, @mello99 -- sounds like we can keep these values, then.
