### ISSUE TITLE
Create a test plan for jaguar and koala commits

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#345]
Please create a test plan for jaguar and koala commits. Use the files in Google Drive VTechWorks/Testing/ as a template.

**Comment by alawvt** [comment]
I added some instructions for creating the test plan in the Wiki, [06. Testing](https://github.com/VTUL/vtechworks/wiki/06.-Testing). Please feel free to improve these.

**Comment by amandafrench** [comment]
Can you link to the test plan from this issue when it's done, please, @pgray64?

**Comment by pgray64** [comment]
Test plan 
https://docs.google.com/a/vt.edu/spreadsheets/d/1glO8ERl28f8uVZz2BgTiZD5OCm2jNoH_G3GTur0GB48/

**Comment by alawvt** [comment]
Very nice. @mello99, the Elements tests are at the top of the spreadsheet. I've asked @pgray64 to let you know when Elements is ready to test. (We have to get ClamAV working first.)

**Comment by alawvt** [comment]
@pgray64, we have decided to revert the ClamAV commit. 
Please remove ClamAV from the test plan and add the test of PR #347.

**Comment by amandafrench** [comment]
See comments on #343 -- for now we can test ClamAV on development but not Elements deposit to vtw.dev.

**Comment by alawvt** [comment]
@pgray64, do not add these items to the test plan. We'll keep it as you first wrote it.
