### ISSUE TITLE
Submission not working on vtechworks.dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#348]
The jaguar and koala changes have been pushed to vtechworks.dev. Attempted submission produces an error message.

@pgray64, you might want to ask IT Services to turn off ClamAV temporarily to isolate the error.

**Comment by amandafrench** [comment]
@alawvt @pgray64 That's the kind of error that has in the past been caused by trailing slashes and/or conflicts between http and https in the config files, I think. Not necessarily a ClamAV error.

**Comment by amandafrench** [comment]
![screenshot 2016-07-25 11 31 47](https://cloud.githubusercontent.com/assets/227453/17107011/7e2b8630-525b-11e6-9347-874652eb57d7.png)

**Comment by amandafrench** [comment]
Note too in screenshot above that although I _did_ log in on the previous page, the "Log in" link in the upper right on the submission page seems to indicate that I'm not logged in.

**Comment by amandafrench** [comment]
Possibly related to #282?

**Comment by mello99** [comment]
Hi all, I recently tried depositing an item from ed.lib.vt.edu (Elements) to DEV and got the following message, so these issues are probably related:

![screen shot 2016-07-25 at 11 57 01 am](https://cloud.githubusercontent.com/assets/5408616/17107839/ec1fc1ee-525e-11e6-9fd5-e7c121af482c.png)

**Comment by alawvt** [comment]
@kayiwa reran the Elements script and now the event handler works. That means the submission form works until you get to the file upload step where there is an antivirus error.  
@pgray64, would you look into the ClamAV?
![clamaverror](https://cloud.githubusercontent.com/assets/13037168/17113343/4c3f65b6-5278-11e6-9334-a6b95a67f0f1.png)
?

**Comment by pgray64** [comment]
I'll test that uploads work on my local box and link to a copy my clamav config file.
That is, once I figure out why I'm getting`java.lang.IllegalStateException: DSpace kernel cannot be null` errors with Tomcat when I try to rebuild

**Comment by pgray64** [comment]
My local LDE is now up and running with vt_5_x_dev_deploy. Uploads and ClamAV is working fine on it without modification.

**Comment by alawvt** [comment]
I submitted a [Symplectic support ticket](https://support.symplectic.co.uk/support/tickets/23553) about this issue.

"We are running DSpace 5.5 with Elements Repository Tools 1.7.3.5. DSpace supports ClamAV to check submissions for viruses, https://wiki.duraspace.org/display/DSDOC5x/Curation+System#CurationSystem-VirusScan. On our Local Development Environments that do not have Elements Repository Tools installed, ClamAV works. However on our development and production servers which do run Element Repository Tools, the submission file upload step produces the error shown in the attached screenshot.

Has anyone been able to install both Elements Repository Tools and ClamAV on their DSpace instance? Are there additional configuration or installation steps necessary?"

**Comment by amandafrench** [comment]
@kayiwa has gotten direct deposit working on vtechworks.dev (with ClamAV), but Elements deposit from ed.lib is still broken. Let's go ahead and start testing all the non-Elements stuff on vtw.dev. 

I think @keithgee and @kayiwa will need to troubleshoot this together, since it might involve changes to the Elements install scripts, DSpace debugging mode, and/or the Ansible playbook. Keith is busy this week but I'll drop him a line to see if he can do this next week.

**Comment by keithgee** [comment]
I will open a separate issue for the Elements deposit. It's already resolved, but I want to make sure it is documented. Elements is ready for testing from ed.lib -> vtechworks.dev @mello99 @amandafrench

**Comment by alawvt** [comment]
Thank you, @kayiwa and @keithgee, for resolving this issue.

**Comment by amandafrench** [comment]
Ditto on the thanks, @keithgee and @kayiwa.
