### ISSUE TITLE
Document IP addresses etc. for Elements

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#349]
Which Elements IP addresses do VTW dev and pprd connect to? Please document at https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/home. Thanks!

**Comment by keithgee** [comment]
I have added this information here:
https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/elements-ip-addresses
Tagging @kayiwa because he was the original requestor.
***Closing

**Comment by alawvt** [comment]
I added a link to this page from the [wiki home page](https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/home).
