### ISSUE TITLE
Remove Author, Subject, Date facets from home page

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#35]
Related to https://redmine.lib.vt.edu/issues/328 

Note that I looked in Google Analytics to determine whether anyone actually uses these and found no evidence of use from the home page. These facets are all in the "Discover" feature, and links of this type from the home page are constructed with the syntax "discover?filtertype=".  A report from the last three weeks (8/21/15 - 9/14/15), when we've had DSpace 5 with these facets enabled out of the box, showed that the first page with that syntax was in 245th place out of all pages visited, and only 11 out of the top 1000 pages visited had that query structure at all. 

An analysis of the whole year, from September 14, 2014 - September 14, 2015, showed that the "Content Type" filter (currently missing, see #33) ranked 112th out of all pages visited, so is clearly more useful. The next most common Discover facet visited was "Date 2010-2015," which came in 384th place.

**Comment by alawvt** [comment]
With the pull request #47, the home page and default advanced search page facets are:
* Content Type
* Date Issued
* Subject

Each has a maximum of 5 items (same as facets in Summon).

**Comment by keithgee** [comment]
Verified content type, date issued, subject facets on home page and search page. 
Collections also have an author facet.
ETDs have a custom configuration with department/advisor/ETD level facets, though  NDLTD is configured with configuration of other collections.
Found no missing i18n key/value pairs.
Closing.

**Comment by alawvt** [comment]
Thanks for testing and realizing the NDLTD collection was missing. I'll add it to the list.
