### ISSUE TITLE
Add documentation for Elements troubleshooting

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#352]
Please expand on Elements checklist, https://docs.google.com/spreadsheets/d/1YN0Y4ClOSd99k7sB3ID721LV8FWN4A56vNQ1EeZPkY4/edit#gid=1946758951.

**Comment by amandafrench** [comment]
Related to #349.

**Comment by keithgee** [comment]
I've started a page here:
https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/elements-troubleshooting

Honestly it just boils down to making sure the script ran and that the network configuration didn't change.

**Comment by keithgee** [comment]
I've added some more details to the page. I think that all of the Elements problems we've had during testing and re-deployments are covered between these two pages:
https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/elements-troubleshooting
https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/elements-ip-addresses

I'll close this issue now, but will make updates as requested or as new issues come up.

**\* Closing
