### ISSUE TITLE
Journal Title Sherpa Romeo look up not working on vtechworks.dev.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#356]
The new submission form should have a Sherpa Romeo look up button for the journal title field but it does not appear.

The regular Sherpa Romeo look up for the ISSN field does work in the submission form on vtechworks.dev.

The Sherpa Romeo lookup button for the journal title field does appear in LDEs built with the latest commits on vt_5_x_dev, https://github.com/VTUL/vtechworks/commit/fbb75505388d2e2bdbacb8b33f5a26d9a09cf104, and vt_5_x_dev_deploy, https://github.com/VTUL/vtechworks/commit/a78b620c7be12eed73ffbf7aa01b507e7d4b19bb, branches.

**Comment by pgray64** [comment]
@kayiwa The only difference I can think of between LDEs and the dev server would be the dev server's dspace.cfg lacking settings consistent with the changes at https://github.com/VTUL/vtechworks/pull/306/files.

**Comment by amandafrench** [comment]
Hey, I bet that's it, @pgray64. I have to admit I can't remember what if any process we developed for making sure that dspace.cfg changes make it into deployment -- last I recall, @kayiwa was going to diff that file every time he deployed. But maybe it's for things like that that we need to submit pull requests to the Ansible playbook.

**Comment by pgray64** [comment]
Journal lookup works fine now on dev. There is another minor problem - the selection modal doesn't close when you hit accept - you have to hit cancel or the 'X'
