### ISSUE TITLE
Test Plan for SQL helper functions

### ISSUE THREAD

**Issue by pgray64** [VTUL/vtechworks#361]
Create a testing plan for the SQL functions at
https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace

**Comment by pgray64** [comment]
Initial test plan - hard to know what could possibly break upon running the functions.
https://docs.google.com/spreadsheets/d/1xpA-PnSaAR5o6mBZQqXG8UkpD1hduYPTv4L9XK2_-L0/edit#gid=0

**Comment by alawvt** [comment]
@pgray64 and I have reviewed the SQL instructions and will be making improvements, #373. After that, we'll review the test plan again.
