### ISSUE TITLE
Unable to deposit from Elements to vtechworks production

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#369]
@mello99 tried to deposit items from the production version of Elements, http://efars.provost.vt.edu, to vtechworks.lib.vt.edu and got the following error message:

![screen shot 2016-08-08 at 3 54 10 pm](https://cloud.githubusercontent.com/assets/5408616/17493962/890f7c16-5d80-11e6-8107-c3892730dceb.png)

Regular submissions and other functions on VTechWorks seems to work, so it seems like the Elements install script ran ok.  
@keithgee or @kayiwa, do you have any ideas for troubleshooting?

**Comment by kayiwa** [comment]
Hey @mello99 could you try this now? 

./fxk

**Comment by mello99** [comment]
Hi @kayiwa , @alawvt , and @keithgee , it's working now - I was able to successfully [deposit an item ](http://hdl.handle.net/10919/72114)(I will delete it shortly). Thanks for your help with this!
