### ISSUE TITLE
Add three static HTML pages: About, Policies, and Help

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#37]
Ideally these three pages should be available from any page in the site, and ideally they wouldn't be in the footer, but for preference in the top right hand sidebar above the Browse facets. I'll write the text for the first three as soon as I can -- feel free to assign it back to me, @AmberPoo1, if you need the text before you can implement the pages.

**Comment by amandafrench** [comment]
There's a bit of documentation about how to do this at  http://dspace.org/sites/dspace.org/files/archive/1_5_2Documentation/ch05.html#N11EFE  -- don't know if that's the best way, but it'd do.

**Comment by amandafrench** [comment]
I've edited this issue to reflect the need for only three pages: I think I'll link or embed the "Request Service" form on the Help page.

**Comment by amandafrench** [comment]
Move pages below search bar

**Comment by amandafrench** [comment]
I'm getting very confused by your lack of commit messages, @AmberPoo1! There's a pretty good blog post about good git commit messages at http://chris.beams.io/posts/git-commit/ -- I do tend to use only the subject line of less than 50 characters and not a full message, but at the very least could you write "Fix bug #61" or "Separate pull request #37 into four commits" or something? Thanks!

**Comment by AmberPoo1** [comment]
@amandafrench , I have updated the title of the pull requests.

**Comment by keithgee** [comment]
@amandafrench, that's a great post you've referenced.
@AmberPoo1, it's not just the pull requests, it's the actual commits. Sometimes it's helpful to quickly browse the commit messages to get an idea of recent changes. If all we see is numbers, it's hard to quickly get an idea of what's new.
@AmberPoo1 I do like the way that you use GitHub's abilities to cross reference issues/commits/pull-requests. I should do this more often, too, and still follow the guidelines in the post that @amandafrench has given: 
http://chris.beams.io/posts/git-commit/

**Comment by amandafrench** [comment]
@keithgee @AmberPoo1 @alawvt @mello99 -- The last sprint's changes have been deployed to development, by the way, and this issue has been resolved, so I'm closing it. It is true that the About, Help, and Policies pages don't show up on the search results page, but I'll make that a separate issue.
