### ISSUE TITLE
Research whether we can upload the text file for a pdf

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#370]
Please research whether we can upload the text file for a pdf. Usually, when we load a pdf with an item, a cron job, `/dspace/bin/dspace filter-media`, https://wiki.duraspace.org/display/DSDOC5x/Mediafilters+for+Transforming+DSpace+Content, also https://wiki.duraspace.org/display/DSDOC5x/Command+Line+Operations, runs to create a text version of the pdf. Solr uses this text file to index the item. 

The patents from the USPTO are pdfs that have not been OCRed. However, the complete text is available in the the claims and description fields. Would it be possible to load this as the text file?  Also, it is not clear that these fields can be imported with the USPTO API, so please report on whether those fields are available.

**Comment by pgray64** [comment]
The API has the abstracts, but not the full text. This could easily be inserted as metadata in the PDFs, and would therefore be used by the full text indexing command.

The OCR used by my script is very accurate for actual text, but it picks up photocopy marks, line numbers, and parts of figures. My script embeds the text for convenient searching and copying of text in the PDF, but would definitely look bad when it shows up in the full text from a search in DSpace.
[3939044.pdf](https://github.com/VTUL/vtechworks/files/411494/3939044.pdf) (original)
[3939044.txt](https://github.com/VTUL/vtechworks/files/411492/3939044.txt)
[with_text_3939044.pdf](https://github.com/VTUL/vtechworks/files/411502/with_text_3939044.pdf)

**Comment by alawvt** [comment]
I think our default will be to OCR the patents as part of your script and let the filter-media job pick up the text for indexing. But since the UPSTO has gone to all the work of creating amazingly clean text versions of the claims and description sections, I was hoping we could leverage them for indexing.

**Comment by alawvt** [comment]
It looks like the Rice University DSpace patent collection, https://scholarship.rice.edu/handle/1911/79705, was OCRed with Acrobat in this default method.

**Comment by alawvt** [comment]
USPTO does have the complete metadata, including description and claims fields, in https://bulkdata.uspto.gov/data2/patent/grant/redbook. However, the file is extremely large, so we'll just use the OCR.
