### ISSUE TITLE
Refine instructions for SQL commands

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#373]
add instructions for creating an SQL dump for backup purposes

add instructions to get a list of all values and counts for a field, for example dc.type and count of each value.

research ways to make command safer and reversible, if needed.

rename command that have effects to warn user.

**Comment by amandafrench** [comment]
Waiting for next sprint.

**Comment by alawvt** [comment]
@pgray64, I have added some instructions in [SQL for DSpace](https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace) from our DevOps meeting about how SQL changes will be implemented on the servers. Please align your instructions with these.
