### ISSUE TITLE
Prepare patent harvest script for release on GitHub

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#376]
When we are ready, we'll fork the project to a public repository on GitHub.

**Comment by alawvt** [comment]
@pgray64, please edit the README for this project to make it as clear as possible for the public. Please review the code and add comments, etc., as needed for clarity.

**Comment by pgray64** [comment]
I think it's ready for release. I added Pdfsandwich's source code and license info so it's okay to have the OSX Pdfsandwich binary in the repo.

**Comment by pgray64** [comment]
Actually I do need to add more information for non-programmers.

**Comment by pgray64** [comment]
I've added more documentation, I think it's ready.

**Comment by alawvt** [comment]
completed, https://github.com/VTUL/patent-harvest
