### ISSUE TITLE
Refine ETD-db harvesting script

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#377]

**Comment by pgray64** [comment]
Not sure why double pipes are appearing in files names when you ran it - I'm getting the correct filenames for entries with multiple files when I run it.

**Comment by amandafrench** [comment]
Possibly related to https://github.com/VTUL/vtechworks/issues/83 ?

**Comment by alawvt** [comment]
@pgray64, please see the notes in etd_db_ingest_notes_20160920.txt on Google Drive.

**Comment by alawvt** [comment]
@pgray64, thank you for a great job.

**Comment by alawvt** [comment]
Continued on https://git.it.vt.edu/digital-research-services/etd_db_ingest/issues/15.
