### ISSUE TITLE
Increase number of items in RSS feed from 4 to 10

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#383]
Links to the RSS feed are on the main page at https://vtechworks.lib.vt.edu.

http://vtechworks.lib.vt.edu/feed/rss_1.0/site
http://vtechworks.lib.vt.edu/feed/rss_2.0/site
http://vtechworks.lib.vt.edu/feed/atom_1.0/site

There are currently 4 items showing in the feed. Please increase the number to 10.

**Comment by pgray64** [comment]
Addressed with pull request #400

**Comment by amandafrench** [comment]
As requested, I've created a test page for this and #384. Once these changes have been pushed to development and then to pre-production, you can test them by refreshing the page at https://researchinformatics.lib.vt.edu/vtechworks-rss-test/.

**Comment by amandafrench** [comment]
Let me know if you think it's necessary to also test the Atom and RSS 1.0 feeds, or if you need anything else.

**Comment by keithgee** [comment]
Merged PR #400. Closing.
