### ISSUE TITLE
Change selection color from pink to something more subdued

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#387]
You might see what other VT sites use.

**Comment by alawvt** [comment]
Issue #308 with PR #358 are previous examples of color changes that you might want to use for reference.

**Comment by AnushaPillai** [comment]
resolved with pull request #402

**Comment by AnushaPillai** [comment]
Adding a screenshot of how it looks 
![selectioncolour](https://cloud.githubusercontent.com/assets/22099712/18758576/a49f9ace-80c6-11e6-88b9-692a779d4c6c.png)

**Comment by keithgee** [comment]
When I built the code with this change, I saw an error scroll by in the terminal:

```
------ (Mirage2) de.saumya.mojo:gem-maven-plugin:1.0.6:exec

[INFO]     error styles/main.scss (Line 22 of styles/_style.scss: Undefined variable: "$chicago-maroon".)

[INFO] Compilation failed in 1 files.

[WARNING] 
```

Yet, I was able to deploy the code to my local development environment and the change of the highlight color to VT maroon works.

**Comment by alawvt** [comment]
I saw something similar when I was testing your video PR and didn't have the right css file linked, I recall vaguely.

**Comment by keithgee** [comment]
@alawvt, did you do something to fix that?

**Comment by alawvt** [comment]
I think I did a brew update and upgrade. The error did involve something about de.saumya.mojo:gem-maven-plugin:1.0.6:exec but I don't recall that it was a missing variable.

**Comment by alawvt** [comment]
@keithgee,

I just built the pull request and received that error, too. 
$chicago-maroon is defined in `modules/xmlui-mirage2/src/main/webapp/themes/vtmirage2/styles/classic_mirage_color_scheme/_bootstrap_variables.scss` 

```
$chicago-maroon: #660000;
```

It is called in `~/GitHub/vtlibans_dspace/dspace/dspace/modules/xmlui-mirage2/src/main/webapp/themes/vtmirage2/styles/_style.scss` 

```
@include selection {
    color: white;
    background: $chicago-maroon;
}
```

**Comment by alawvt** [comment]
I think this error occurred because $chicago-maroon was called in `dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_style.scss` where it was not defined. We only need to use it in the theme we are actually using, `dspace/modules/xmlui-mirage2/src/main/webapp/themes/vtmirage2/styles/_style.scss`.
