### ISSUE TITLE
Error message when user tries to reset password on vtechworks.dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#393]
I just created an account for @AnushaPillai on vtechworks.dev. She used the password reset page to reset her password (unfortunately this is standard procedure for new users). When she submitted it, she received an error. 
![passwordresetdeverror](https://cloud.githubusercontent.com/assets/13037168/18586695/dbeeae0a-7beb-11e6-963c-7d0e3aca67aa.png)
We tried the same thing on vtechworks production and it worked as expected. Therefore I think it has something to do with the latest security changes.

**Comment by alawvt** [comment]
This was caused by the change in University mail settings. Thank you, AH and @kayiwa, for resolving this issue. It now works again.

**Comment by alawvt** [comment]
@kayiwa, The form said the email was sent. Unfortunately, @AnushaPillai has not received any of the emails that were sent for the password reset.

**Comment by alawvt** [comment]
ITS is waiting on VT IT to fix this.

**Comment by alawvt** [comment]
This has been resolved. vtechworks.dev is able to send emails again.

**Comment by keithgee** [comment]
Will I need to do anything to get mail working on my LDE?

**Comment by alawvt** [comment]
@kayiwa says, "no."
