### ISSUE TITLE
Video display issue on dev

### ISSUE THREAD

**Issue by AnushaPillai** [VTUL/vtechworks#395]
Video control icons missing. Refer to https://vtechworks.dev.lib.vt.edu/handle/10919/52246

![video display issue on dev](https://cloud.githubusercontent.com/assets/22099712/18598054/0a500536-7c1f-11e6-906d-a61973c02bd2.png)

**Comment by keithgee** [comment]
Thank you, @AnushaPillai. @zoto724, can you please add the following to the Content-Security-Policy header on vtechworks.dev?

```
; font-src https: data:
```

**Comment by zoto724** [comment]
Done @keithgee

**Comment by alawvt** [comment]
Issue resolved
