### ISSUE TITLE
Deploy Maltipoo sprint commits to vtechworks

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#398]
Reminder to note that changes include manual ones for the server for ClamAV. (This will probably have to be incorporated in vtlibans_dspace, as well.)

It is also necessary to modify ClamAV daemon's config file `/etc/clamav/clamd.conf`

```
StreamMaxLength: 2000M
maxFileSize: 2000M
maxScanSize: 2000M
```

**Comment by alawvt** [comment]
@kayiwa, please deploy the latest commit on vt_5_x_pprd_deploy, https://github.com/VTUL/vtechworks/commit/5df07b12f54c05d86f8b7b29353da2b73576b8b6, to vtechworks.pprd.

Please note that /dspace/config/dspace.cfg will need manual updating.

Please note the ClamAV settings listed above.

**Comment by alawvt** [comment]
@kayiwa, please deploy the latest commit on vt_5_x_prod_deploy, d9af1ae, to vtechworks.lib.vt.edu. I will also request this in TeamDynamix.

Please note that /dspace/config/dspace.cfg will need manual updating.

Please note the ClamAV settings listed above.

**Comment by alawvt** [comment]
Complete

**Comment by keithgee** [comment]
Woohoo!
