### ISSUE TITLE
Get a count of how many items in the repo have ORCIDs and DOIs.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#404]
Get a count of how many items in the repo have ORCIDs (dc.identifier.orcid is not null)

Get a count of how many items in the repo have DOIs

Please see me for a recent SQL dump.

**Comment by pgray64** [comment]
**Using dump: dspace_2016-09-30_06h39m.Friday.sql**

_Metadata ID's_
DOI: 96
ORCID: 105

`SELECT count(*) FROM "metadatavalue" WHERE metadata_field_id=96 AND text_value IS NOT NULL;`
=> 3187

`SELECT count(*) FROM "metadatavalue" WHERE metadata_field_id=105 AND text_value IS NOT NULL;`
=> 7

**Comment by alawvt** [comment]
@pgray64, thank you.

**Comment by amandafrench** [comment]
Belatedly, yes, thanks, @pgray64! I'm going to start tracking these in the VTechWorks Statistics spreadsheet, available in GDrive and from the intranet. 

One question: do the counts above reflect number of items with DOIs / ORCIDs, or just the number of DOIs / ORCIDs? I know that one item can definitely have multiple ORCIDs. LMK.

**Comment by alawvt** [comment]
I believe this is the number of DOIs/ORCIDs, not number of items.

**Comment by amandafrench** [comment]
I suspected as much! Hate to reopen this, but I do think we need to have the number of _items_ with one or more DOIs (usually that'll be one DOI) and the number of _items_ with one or more ORCIDs. If it turns out to be massively difficult let me know. Good to post the query here, though -- and on GitLab, so we can easily run it when we want to.

**Comment by pgray64** [comment]
Fixed:
`SELECT DISTINCT ON (resource_id) FROM "metadatavalue"  WHERE metadata_field_id=96 AND text_value IS NOT NULL;`
=> 3184

`SELECT DISTINCT ON (resource_id)  FROM "metadatavalue" WHERE metadata_field_id=105 AND text_value IS NOT NULL;`
=> 7

**Comment by pgray64** [comment]
It shouldn't be too difficult to add author fields to RSS 1.0 and 2.0, though for those specs only one author field is allowed, so could be comma separated if multiple. A CSS stylesheet can be added to the feeds as well.

**Comment by amandafrench** [comment]
Awesome, thanks @pgray64. Not much of a difference now but might be later. 👍

**Comment by alawvt** [comment]
Request for stats for Nov. 30. 2016-11-30 dump is in Google Drive...VTechWorks/Technology/.

**Comment by alawvt** [comment]
number of items with one or more DOIs: 3363  
number of items with one or more ORCIDs: 8

**Comment by alawvt** [comment]
We need to update the query for DSpace 6.

**Comment by alawvt** [comment]
Number of items with DOIs (DSpace 6)
`SELECT DISTINCT ON (dspace_object_id) FROM "metadatavalue" WHERE metadata_field_id=96 AND text_value IS NOT NULL;`

Number of items with ORCIDs (DSpace 6)
`SELECT DISTINCT ON (dspace_object_id) FROM "metadatavalue" WHERE metadata_field_id=105 AND text_value IS NOT NULL;`
