### ISSUE TITLE
Fix full item view so long file names display

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#405]
Fix full item view so long file names display. This is needed to distinguish identical long filenames from ETD-db, such as http://vtechworks.lib.vt.edu/handle/10919/73012?show=full.

You might refer to a similar issue, #138.

**Comment by pgray64** [comment]
Resolved with PR #406

**Comment by keithgee** [comment]
I'm attaching a screenshot from a successful test and closing.
<img width="537" alt="longfilename_full_view" src="https://cloud.githubusercontent.com/assets/6785790/18838054/0454a27e-83d4-11e6-820c-2f720e51ac66.png">
