### ISSUE TITLE
Video do not scale in full screen mode.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#407]
Video, for example, https://vtechworks.lib.vt.edu/handle/10919/52246, do not scale in full screen mode.

**Comment by keithgee** [comment]
I've labeled this as wontfix. We can add to the backlog and address later if necessary.

**Comment by keithgee** [comment]
Actually, I may have time to fix this before deployment if it is just a CSS problem. I'll look tomorrow.

**Comment by keithgee** [comment]
This issue was fixed with commit de63944.

**Comment by keithgee** [comment]
Tested at http://vtkeithg.lib.vt.edu/handle/10919/52944. This hasn't been tested with the new Content-Security-Policy header yet but that can be done on dev.
