### ISSUE TITLE
Research a Postgres GUI for our LDEs

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#410]
Please research a postgres GUI for our LDE. @keithgee, do you recall any detail of the suggestion @zoto724 made to implement a GUI listening on a port to the DB?

**Comment by kayiwa** [comment]
Give this a look. https://www.sequelpro.com/ 'er... looks like it changed. https://macpostgresclient.com/

**Comment by pgray64** [comment]
Instructions for setting up Adminer on LDE: 
https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace

**Comment by keithgee** [comment]
That looks nice, @pgray64, and is very much like the web based database tools for LAMP sites that we were discussing the other day.

@alawvt, Aaron has suggested the approach of using SSH tunneling for port forwarding, which you can use with any database client, such as the second client that @kayiwa has suggested.

I have this working and will demonstrate for you, if you are still interested in this approach.

**Comment by alawvt** [comment]
@keithgee, yes I would like to see that, too. If you want to document any of it on the wiki page the @pgray64, linked to, that would be great.

**Comment by alawvt** [comment]
@pgray64, thanks, that is a nice easy solution.
