### ISSUE TITLE
Crosswalk ORCIDs from EFARs (Symplectic Elements) to VTechWorks

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#414]
See
- https://support.symplectic.co.uk/support/tickets/26226
- https://support.symplectic.co.uk/support/discussions/topics/6000037525
- https://support.symplectic.co.uk/support/discussions/topics/6000034614

**Comment by alawvt** [comment]
Given the metadata structure of DSpace, I like the solution used at the University of Cambridge, 

```
"dc.contributor.orcid" field and the ORCIDs are stored as follows: 
Surname, Initial [0000-0000-0000-1234]
```

Like a name followed by a birth date in a bibliographic record, the name followed by the ORCID in the same field allows a user to easily relate the ORCID to the name to verify his/her identity.  If we left the ORCID as a separate value without the author name, the user could click on the ORCID link (which we hope to implement) to find the name associated with it. But U. of Cambridge's method eliminates the need for the user to do this additional step.

**Comment by keithgee** [comment]
I've e-mailed the Cambridge Libraries' Office of Scholarly Communication to see if they can put me in touch with someone who will share code.

**Comment by amandafrench** [comment]
I admit, that is a better solution than the one I envisioned, in which ORCIDs are just stored with no names. Make it so!

**Comment by keithgee** [comment]
If it works out, we could still make the ORCIDs linkable, in case there is
other information in the ORCID profile that users might want to see.

**Comment by alawvt** [comment]
@amandafrench, thank you for your consideration. I will add an item to the backlog to investigate if we can do this concatenation with the ORCID and dc.contributor.author in a non-interactive step in the submission form.

**Comment by keithgee** [comment]
I've also posted a request for code in the Symplectic forum.

**Comment by alawvt** [comment]
[University of Cambridge "Apollo" DSpace repository](https://www.repository.cam.ac.uk)

[Item with an ORCID in the dc.contributor field](https://www.repository.cam.ac.uk/handle/1810/255131)

If we don't hear from U. of Cambridge, I think we could modify J.S.'s code in https://support.symplectic.co.uk/support/discussions/topics/6000034614. The hard part is testing it since our LDE don't have a connection to an Elements server. I believe this code goes in  ~line 80 of vtechworks/dspace/config/crosswalks/symplectic_xwalks_dspace_default.xsl. This code would have to be changed for the field names in DSpace, rather than in Eprints. The template is getting the pubs:people/pubs:person info from Elements, which I assume is in the item data. We'd have to see if pubs:people/pubs:person has any connection to the profile information of the submitter in Elements.

**Comment by keithgee** [comment]
Thanks, @alawvt. I've been contacted by University of Cambridge and they'll
send more details this week.

**Comment by keithgee** [comment]
@alawvt I am attaching correspondence from Dr. Martinez at Cambridge.

[cambridge_orcid.pdf](https://github.com/VTUL/vtechworks/files/530019/cambridge_orcid.pdf)
[orcid-mapping.txt](https://github.com/VTUL/vtechworks/files/530020/orcid-mapping.txt)

**Comment by alawvt** [comment]
I believe all our modification has been in [symplectic_xwalks_dspace_default.xsl ](https://github.com/VTUL/vtechworks/blob/6a570013b75906379eb67480e2e794a2a12c6bc3/dspace/config/crosswalks/symplectic_xwalks_dspace_default.xsl) and we don't have crosswalks based on item type, as Cambridge has.

**Comment by amandafrench** [comment]
We're going to revisit this later.

**Comment by keithgee** [comment]
I've opened Symplectic ticket #32546 for additional help. It's been several months since I looked at this, but initial experimentation with Cambridge's method failed when applied to our setup.

```
#32546 Get ORCID ids from Elements to put into DSpace repository items
K
Keith Gilbertson
reported less than a minute ago
Hi,

It's my understanding that it's possible to get the ORCiD associated with an Elements user
 when the user chooses to send an item to the repository, and then store that ORCiD in a metadata
 field on the DSpace item

 I don't understand how to do this, and probably need very detailed, step-by-step instructions.

Can we get help for this?
We are using Elements 5 and the DSpace repository tools.> 
```

**Comment by keithgee** [comment]
Jeff at Symplectic has me working with Kate Byrne and Andrew Bennet. Here is a restatement of the problem from Kate:

```
It was to bring in the ORCIDs appended to the author string, so they appear in the format: "Lastname, Firstname (1234-5678-9101-1121)"

This uses the ORCIDs from the linked Elements users (all authors for that publication that are linked to a person within Elements), where those ORCIDs resolved to the author metadata (i.e. they have added their ORCID to Elements via their search settings page). 

So if a publication in Elements has 5 authors total, 3 of which are from VTech and are linked to the publication in Elements. 2 of those three authors have added their ORCID to Elements. When that publication is deposited the ORCIDs would be transferred with the author name for those 2 authors out of the total 5 authors. 

Does that align with what you are expecting? 

Best wishes

Kate
```

Andrew Bennet has sent some code modifications based on our GitHub repository, and I am currently testing.

Some questions came up during Virginia Tech's brief discussion today. 

- If an article was not harvested from ORCiD, but added to Elements via another means, will the Space metadata still have the ORCiDs for Virginia Tech authors that have configured their ORCiD search setting?

- Should we just store the ORCiD in dc.contributor.author instead of placing it in an additional field?

**Comment by keithgee** [comment]
This issue was resolved with commits 3160671 and e8c9fcc from @AndrewBennet.

I've added the question/task of storing ORCID in contributor.author to the backlog.

**Closing

**Comment by alawvt** [comment]
Please try mapping the ORCiD directly in contributor.author field instead of identifier.orcid by changing dspace/config/crosswalks/symplectic_xwalks_dspace_default.xsl:101  to `<xsl:when test="$repo_field = 'dc.contributor.author'">`.

**Comment by keithgee** [comment]
@alawvt, I've made this code change and tested on my local. When I deposit from ed.lib.vt.edu, the ORCIDs vanish - they are no longer in any field.
Here's a sample:
http://vtkeithg.lib.vt.edu/77777/8?show=full

You're also welcome to try a deposit from ed.lib.vt.edu, if you want to verify the behavior. Or it might work for you!

**Comment by alawvt** [comment]
@keithgee, thank you very much for trying this. I tried one too, and it didn't show, as well.
