### ISSUE TITLE
RSS 1.0 feed only lists 4 items

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#417]
RSS 1.0 feed only has 4 items listed on https://vtechworks.lib.vt.edu/feed/rss_1.0/site. It has 10 items on dev and pprd. RSS 2.0, https://vtechworks.lib.vt.edu/feed/rss_2.0/site and Atom, https://vtechworks.lib.vt.edu/feed/atom_1.0/site both have 10 on all three servers. I'm observing this on Firefox, Safari, and Chrome. 

`# number of DSpace items per feed (the most recent submissions)
webui.feed.items = 10` is correct on the server at /dspace/config/dspace.cfg.

**Comment by keithgee** [comment]
I've cleared the Cocoon cache. This is an option in the "Java Information" tab of the "Control Panel", displayed when a person is logged into the VTechWorks web interface as an administrator.

10 items are now displaying in the RSS 1.0 feed.

Note: if there are future problems like this, also pay attention to the webui.feed.cache.age setting in the dspace.cfg file. It is currently set to cache feeds for 48 hours.

**Closing

**Comment by alawvt** [comment]
Thanks, @keithgee! 

For future reference, [DSpace Technical FAQ - Clearing Cocoon (XMLUI) cache](https://wiki.duraspace.org/display/DSPACE/TechnicalFAQ#TechnicalFAQ-ClearingCocoon%28XMLUI%29cache)
