### ISSUE TITLE
Test vtechworks-ansible, the public version of vtlibans_dspace project

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#423]
Please test the public version of vtlibans_dspace project, https://github.com/VTUL/vtechworks-ansible

**Comment by kayiwa** [comment]
I encourage you to fork and submit pull requests where you find anything about this wanting. I have a finite amount of days at VA Tech but will happily make sure this continues to be useful even on my departure. 

Each of the roles (working on the vtechworks one) has a description of what it does, the variables it expects etc.,

**Comment by pgray64** [comment]
I followed the instructions and everything loads as expected, except there are no items displaying. I did import `fewer_items_database_dump.sql` and reindex.

**Comment by kayiwa** [comment]
made this an issue here https://github.com/VTUL/vtechworks-ansible/issues/1

will try to recreate and solve this.

**Comment by kayiwa** [comment]
made this an issue here https://github.com/VTUL/vtechworks-ansible/issues/1

will try to recreate and solve this.

**Comment by kayiwa** [comment]
please run

`vagrant destroy`

`git pull`

and then

`vagrant up` again. I've committed the fix. Solr was listening on 8081 instead of 8080. 

Cheers.

**Comment by pgray64** [comment]
I've been using this on my local dev box without any issues.
