### ISSUE TITLE
Create a test plan for DSpace 5.6, Newfie and Ostrich commits

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#425]
Please create a test plan for DSpace 5.6, Newfie, and Ostrich commits in the Google Drive/VTechWorks Team/Testing/ folder. This will cover the period October 01-November 14 and commits ad4f586 through the present.

The test plan is on Google Drive at VTechWorks/Testing/Dspace_5.6_2016_Oct_01_Nov_13_Newfie_Ostrich_Testing

**Comment by pgray64** [comment]
I made  a test plan based on commit sfrom that time period, though I'm not sure how to test elements related things.

**Comment by alawvt** [comment]
I have completed the test plan.
