### ISSUE TITLE
Update Elements files on git.it.vt.edu for DSpace 5.6

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#429]
Use DSpace 5.6 branch, add_5_6_changes, to create changes needed for Elements with DSpace 5.6. Update vtlibans_dspace and elements_install_scripts projects on GitLab.

**Comment by keithgee** [comment]
I have tested our current Elements install package with @alawvt's DSpace 5.6 branch, and it works without change.

I'll look into why I needed to make changes during a previous upgrade and provide documentation if appropriate.

**Closing
