### ISSUE TITLE
Move help, policy, and about pages to google site

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#431]
Please move the help, policy, about pages to google site, https://sites.google.com/a/vt.edu/vtechworks-help/. Please change the links in the right side bar to these pages. Moving these pages will make it easier to maintain and edit them.

**Comment by pgray64** [comment]
The google site is finished. Pull Request #432 updates links on VTechWorks to go to google sites pages.

**Comment by alawvt** [comment]
@amandafrench, the new pages are   
- About, https://sites.google.com/a/vt.edu/vtechworks-help/home  
- Policies, https://sites.google.com/a/vt.edu/vtechworks-help/policies  
- Help, https://sites.google.com/a/vt.edu/vtechworks-help/help
