### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#435]
https://github.com/VTUL/vtechworks/blob/vt_5_x_dev/dspace/modules/xmlui-mirage2/src/main/webapp/themes/vtmirage2/xsl/core/page-structure.xsl

**Comment by keithgee** [comment]
The footer was recently updated with information about the VTechWorks takedown request policy. Otherwise, there isn't enough information in this issue to determine the original change. Removing "revisit later" label.
