### ISSUE TITLE
Revise etd-ingest script so that it transforms or allows non UTF-8 characters

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#436]
The ESS system often sends us XML files with non UTF-8 characters. The ingest script flags any XML file with non UTF-8 characters and sends it to an error directory instead of loading it. The script needs to either 

1) transform the non-UTF-8 characters to UTF-8 before ingest is attempted (preferred), or 

2) load the files with "junk" characters anyway instead of putting them in the error directory. 

At some point the ESS system and/or database needs to be fixed so as to better handle non UTF-8 characters, but until then this will fix the most urgent problem, which is a year-old backlog of unloaded ETDs. 

Make it so.

**Comment by amandafrench** [comment]
See also https://git.it.vt.edu/digital-research-services/etd_ingest/issues/1.

**Comment by alawvt** [comment]
If we are going to replace each bad character with another, I'd prefer one that would be easy to search for in DSpace, so we can clean up the metadata.

**Comment by keithgee** [comment]
There is a merge request in the GitLab etd_ingest project, with code to replace non-UTF_8 characters in the ETD-MS metadata file with the Unicode Replacement Character �.
