### ISSUE TITLE
Create a script to export all metadata from the Withheld collection in ETD-db.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#437]
Please create a script to export all metadata from the Withheld collection in ETD-db.

**Comment by amandafrench** [comment]
@alawvt Can you please update the README for this script in GitLab so that it explains that this is what the script does? Thanks.

**Comment by alawvt** [comment]
@pgray64, when you get this variation of the script working, please add it to https://git.it.vt.edu/digital-research-services/etd_db_ingest and add it to the description of the project and readme. Thanks.

**Comment by pgray64** [comment]
Readme and script updated in Gitlab

**Comment by alawvt** [comment]
Continued on https://git.it.vt.edu/digital-research-services/etd_db_ingest/issues/14
