### ISSUE TITLE
Can't move items from one collection to another

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#44]
Hi all, I remembered that I needed to move some items from the [2014 Veterans in Society collection] (http://vtechworks.lib.vt.edu/handle/10919/56348) to the [2013 Veterans in Society collection](http://vtechworks.lib.vt.edu/handle/10919/56640), but unfortunately that didn't work out. 

I tried to do this using the "Move" functionality under "Edit Item". Although certain items are now listed as being part of the 2013 Veterans in Society collection, such as [this one] (http://vtechworks.lib.vt.edu/handle/10919/25211), they don't appear in the indexing or search results when you click on the 2013 Veterans in Society collection. I talked to @kayiwa about this and he did the following: 

ran index-db-browse -f
ran index-lucene-update
ran index-discovery

Unfortunately these steps didn't fix the problem. @alawvt and @keithgee, do you have any idea as to what might be going on? Some of these items were already mapped to other collections, specifically the [following collections in the Center for Rhetoric in Society community] (http://vtechworks.lib.vt.edu/handle/10919/54939), so perhaps that's why I can't move them. I'll look into this tomorrow when I'm not so tired. So sorry for the hassle, and thanks for your help.

**Comment by keithgee** [comment]
@mello99, the specific item you've pointed out - "Veterans and Broadband Access in Virginia: Implications for Healthcare Planning and Policy" - looks fine right now. Maybe it's been fixed?
[Item showing in correct collection](http://vtechworks.lib.vt.edu/handle/10919/25211)
[Item appearing in title browse index of collection](http://vtechworks.lib.vt.edu/handle/10919/56640/browse?type=title)
[Item appearing in date browse index of collection](http://vtechworks.lib.vt.edu/handle/10919/56640/browse?type=dateissued)
[Item appearing in search result of collection](http://vtechworks.lib.vt.edu/discover?scope=10919%2F56640&query=Veterans+and+Broadband+Access+in+Virginia%3A+Implications+for+Healthcare+Planning+and+Policy&submit=)

**Comment by mello99** [comment]
Yep, it works now - over 3 hours later. Don't know why or what happened, but it works. Me and my need for instant gratification :). 

Do we want to close this issue? It seems to be related to Issue #41 .

**Comment by keithgee** [comment]
It might be related. I'm not sure.

I want to close it. Instant gratification.

**Comment by keithgee** [comment]
This issue has not been seen again, to my knowledge, in the several weeks that the Tomcat user on the VTechWorks machine was changed.
