### ISSUE TITLE
Modify the submission form to map the ORCID to dc.contributor.orcid

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#442]
Add dc.contributor.orcid to the metadata registry. Change the submission form to map the ORCID to this field rather than dc.identifier.orcid. (Check it may appear in multiple custom submission forms.)

**Comment by pgray64** [comment]
The dropdown menu that the ORCID option is in has an XML parent of type "identifier" so the field can't simply be changed:

<img width="400" alt="screen shot 2016-11-18 at 1 33 52 pm" src="https://cloud.githubusercontent.com/assets/7339589/20441717/b24f64a2-ad93-11e6-86ad-8f2de65303c8.png">
