### ISSUE TITLE
ezproxy off-campus sign-in issue

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#446]
I tested the off-campus sign-in, and (as reported by two users) even though ezproxy sign-in is apparently successful, I still am not allowed to access restricted items. I've reported this to ITS in TeamDynamix. 
![screenshot 2016-12-06 08 30 40](https://cloud.githubusercontent.com/assets/227453/20927368/4a2caf7e-bb8f-11e6-922f-c619fbd01b78.png)

**Comment by alawvt** [comment]
@amandafrench, thank you very much for testing this. I found the error in authentication-ip.cfg; have made the correction; and am sending a TeamDynamix request to take the change on production.

**Comment by alawvt** [comment]
@zoto724 made the fix. Thanks!

**Comment by alawvt** [comment]
q

**Comment by amandafrench** [comment]
@alawvt Great! Is it tested? Feel free to go off-campus and check!

**Comment by alawvt** [comment]
I tried the url, https://vtechworks-lib-vt-edu.ezproxy.lib.vt.edu/handle/10919/39519, from on campus and it worked. I have not tried it from off campus.

**Comment by amandafrench** [comment]
@alawvt Okay, I'll test it later today or maybe tonight. Thanks for addressing this so fast.

**Comment by amandafrench** [comment]
Tested off-campus and works correctly.
