### ISSUE TITLE
Grad School Thesis with truncated title "Exploring The"

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#449]
The recently (December 9th) processed thesis at https://vtechworks.lib.vt.edu/handle/10919/73650 has the truncated title "Exploring the".

Based on the title page of the PDF, the full title should actually be:

Exploring the “Where” and the “Why” of Conservation Easements: The Role of Community-level Factors in the Likelihood of Adoption

I looked into the ETD processing directory and found file /dspace/assetstore/ingest/etd-gradschool/unrestricted/thesis/2016120909_47_39094739-0500/vt_gsexam_9018/etd-ms/Hemby_TL_T_2016_DATA.xml.bak. This showed me that the truncated title "Exploring the" was sent to us from the grad school.

I don't know if this is a common or rare problem, and it doesn't seem to be something we can easily fix on our end, but it might be worth about a minute of discussion and also a mention the next time there's a meeting with the grad school.

**Comment by alawvt** [comment]
@keithgee, thank you for investigating this error. Yes, it does seem like something that we can fix in our script. I have corrected the title in VTechWorks.
