### ISSUE TITLE
Create a custom submission form for the ETD collections

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#458]
Please create a custom submission form using the specs in Google Drive...VTechWorks/Custom Submission Forms/VTW_Custom_Submission_Forms/ETDCustomSubmissionForm for collections, https://vtechworks.lib.vt.edu/handle/10919/11041 and https://vtechworks.lib.vt.edu/handle/10919/9291.

Please see issue #101 for a similar form.

**Comment by pgray64** [comment]
Pull request #461

**Comment by pgray64** [comment]
I think it is problematic to have a custom submission form with multiple fields using the same dublin core name. When I test the form adding a value to "proxy name", which is of type dc.description.provenance, it shows up for all 3 provenance fields on the form.

**Comment by alawvt** [comment]
If you can't get multiple form fields to map to the same dc.description.provenance, please make up multiple dc.provenance fields like dc.description.provenance2, etc for each mapping. Please submit a pull request with whatever you have on Friday so I can look it over next week. You might mention the issue to @keithgee, if he is available.

**Comment by pgray64** [comment]
I'll use the alternate dc fields. Looks like this issue is a common one.

**Comment by pgray64** [comment]
Made workaround so multiple fields can correspond to dc.description.provenance. 
I used 5 temporary dc fields: dc.description.provenance1 ... dc.description.provenance5 and a non-interactive submission step.

In metadata editor need to add: `dc.description.generalabstract` and `dc.description.provenance1`, `dc.description.provenance2`, ... `dc.description.provenance5`

Interface now works normally and the multiple fields end up in dc.description.provenance after submission. The temporary provenance fields are cleared and don't show up.

I pushed my changes to the existing branch, PR #461.

**Comment by pgray64** [comment]
PR #461 has the update changes pushed to branch

**Comment by pgray64** [comment]
Provenance reason label addition pushed to PR #461

**Comment by alawvt** [comment]
@pgray64, this is look very good. Please add the latest changes in red on the customization spreadsheet.
