### ISSUE TITLE
New item didn't automatically index

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#462]
Per @alawvt , the item at https://vtechworks.lib.vt.edu/handle/10919/74976 was not automatically indexed.

She was able to force indexing by making the item private and then public again.

**Comment by keithgee** [comment]
Log files show that the metadata for the item was indexed succesfully when it was initially added on February 9th. I'm wondering what type of specific search or browse indicated to the user that the item wasn't indexed properly, and what the problem might have been.

There was a problem indexing the full text of the item on the morning of February 10th. The implementation of the solr indexing for DSpace currently indexes the full text of only one bitstream for each item (this is a known issue, and a bug). The bitstream that is indexed is the bitstream that is the "last" bitstream in the main content bundle. In the case of this ETD, the last bitstream is a supporting document that contains an email granting permission to use intellectual property. There was a problem during indexing of this document containing the email:
```
2017-02-10 03:07:26,487 ERROR org.dspace.discovery.SolrServiceImpl @ Error while writing item to discovery index: 10919/74976 message:org.apache.tika.exception.TikaException: Failed to parse an email message
```
@alawvt or @amandafrench could you please point me to our vtechworks help request list and give me access if I don't already have it, so that I can see the initial query for this issue and others?

**Comment by alawvt** [comment]
@keithgee, thank you for mentioning this bug in indexing. This looks the issue, [DS-2952](https://jira.duraspace.org/browse/DS-2952). It sounds like it has not been fixed yet in either DSpace 5 or 6. We have many ETDs with supporting files and we list the main file first because that is the one most patrons want. I have requested you have access to the support email account.

**Comment by keithgee** [comment]
I looked in the email support account and the author reports that there were problems browsing by author. I'm not sure what happened, this was resolved earlier by Anne, and I don't know of other items that had this problem.

Closing.
