### ISSUE TITLE
BUG: modal window for journal lookup doesn't close after clicking Accept

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#463]
When users go through the submission form and use the Lookup feature for the journal title, they get a modal box that allows them to choose a journal title. Clicking "Accept" should close the window, but it doesn't -- the user has to click the top right-hand X to close the window, or else click "Cancel." Any way this box can be made to close automatically when the user clicks "Accept"? 

Not sure if this is in the Mirage theme or in DSpace, but whichever one it is, this fix should be contributed back upstream. 

![screenshot 2017-02-14 11 02 10](https://cloud.githubusercontent.com/assets/227453/22937078/708dc34a-f2a5-11e6-84bf-8356884108ce.png)

**Comment by keithgee** [comment]
I'd love if Philippe would get time to work on automating some tests.
I have a fix for this issue in pull request #464, which Philippe may review if he wishes - I don't work on front-end code much these days.

**Comment by pgray64** [comment]
Fixed with pull request #464

**Comment by keithgee** [comment]
I went to open a ticket for this on the DSpace Jira and found that one is already there.
https://jira.duraspace.org/browse/DS-2170?jql=project%20%3D%20DS%20AND%20text%20~%20%22authority%20control%22

**Comment by amandafrench** [comment]
@keithgee @pgray64 Thanks, guys! Keith, will you submit a PR to the DSpace project to fix the bug?
