### ISSUE TITLE
Create a modified file submission form for ETD collections

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#465]
Extends Issue #458.

Please add the text in Google Drive...VTechWorks/Custom Submission Forms/VTW_Custom_Submission_Forms/ETDCustomSubmissionForm, line 38, "loading instructions" hint to the file submission page of the ETD custom submission form.

**Comment by alawvt** [comment]
You will probably need to overlay a file to override UploadWithEmbargoStep.java. It would be great if you could set the embargo option on this page to only the fixed value of one year (don't have the person choose a release date) or remove the embargo option.

**Comment by pgray64** [comment]
PR #461 adds these customizations.

**Comment by pgray64** [comment]
I removed the file description field and updated the description text.

**Comment by alawvt** [comment]
@pgray64, thanks, this is excellent. Please add the latest changes in red on the customization spreadsheet.

**Comment by pgray64** [comment]
Latest changes pushed to #481

**Comment by pgray64** [comment]
Change to make NDLTD abstract required pushed too
