### ISSUE TITLE
Display the General Audience abstract in Simple Item View

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#468]
When an ETD or other item contains a general audience abstract (dc.description.abstractgeneral), display it in Simple Item View it below dc.description.abstract as,
```
"General Audience Abstract:"
Text of General Audience Abstract.....
```
Search results and browse should only display dc.description.abstract.

**Comment by pgray64** [comment]
PR #471 adds general audience abstract to simple item view

**Comment by alawvt** [comment]
@pgray64, thank you, it looks good.
