### ISSUE TITLE
Thumbnail not appearing in browse view

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#469]
Browsing the collection, for instance by issue date, https://vtechworks.lib.vt.edu/browse?type=dateissued, most items have thumbnails, but that a few are listed with a link for "Thumbnail" in Firefox and Safari or the broken image symbol in Safari, rather than the actual thumbnail. The thumbnail displays in Simple Item View and in Edit Item View. It seems like the items with this problem differ between browsers. Perhaps not enough time is given to load all the images?

@zoto724, do you think this could be caused by a caching issue related to the f5 appliance?

**Comment by keithgee** [comment]
It seems like there is an issue with the connectivity between the database and the DSpace web application this morning. It's not just the new ETDs that have problems, but all items, intermittently. Sometimes the thumbnails load and sometimes they don't. Also, occasionally a page loads without showing the list of items at all.
This procedure usually resolves it:

- stop Tomcat
- restart Postgres
- start Tomcat

**Comment by zoto724** [comment]
will restart in a few, still in a meeting.

**Comment by alawvt** [comment]
Thank you, @keithgee for the diagnosis and @zoto724 for restart. I cleared my cache and it seems good now. @zoto724 plans to reboot the f5 tonight, as well.

**Comment by alawvt** [comment]
Notes from @zoto724:
Restarted the f5, but it wasn't causing this.  

Looking through logs on the server, Apache is responding http 500.  
```
192.168.2.6 - - [13/Mar/2017:21:58:48 -0400] "GET /bitstream/handle/10919/10322/TX717.K6_1823.pdf.jpg?sequence=3&isAllowed=y HTTP/1.1" 500 2839 "https://vtechworks.lib.vt.edu/browse?type=dateissued" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```
There are psql errors, as @keithgee  mentioned.

 I'll look into the postgres instance tomorrow but nothing changed the past few days.

**Comment by alawvt** [comment]
DSpace logs:
```
2017-03-13 01:00:48,829 ERROR org.dspace.storage.rdbms.DatabaseManager @ SQL query singleTable Error
2017-03-14 09:15:31,646 ERROR org.dspace.storage.rdbms.DatabaseManager @ SQL findByUnique Error
```
