### ISSUE TITLE
Create instructions and SQL function or query to redirect one handle to another

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#477]
If we have duplicates, handledeleted and handlekept, create instructions and SQL function or query to redirect handledeleted to handlekept.

**Comment by pgray64** [comment]
Would you like it so visiting handledeleted returns the resource pointed to be handlekept (but still shows handledeleted in the URL bar).
Or would you want handledeleted to actually redirect in the browser to handlekept?
 The second option couldn't be done with just SQL queries.

**Comment by alawvt** [comment]
I think it would be ok to do the SQL-only one.

**Comment by pgray64** [comment]
Make handledeleted essentially an alias of handlekept:

`update handle set resource_id=handlekept.resource_id from (select resource_id from handle where handle='<HANDLE_KEPT>') as handlekept where handle.handle='<HANDLE_DELETED>';`

replacing <HANDLE_KEPT> and <HANDLE_DELETED> with the actual handles

**Comment by alawvt** [comment]
thank you.
