### ISSUE TITLE
Install the REST API on your LDE and document procedure

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#479]
Please install the [REST API](https://wiki.duraspace.org/display/DSDOC5x/REST+API) on your LDE and document your procedure.

**Comment by alawvt** [comment]
Please document it on https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api

**Comment by alawvt** [comment]
@keithgee added some note to the wiki page. Please continue with installing and documenting the REST API. If you need to change vtlibans for this to work, please submit it as a pull request for that project.

**Comment by alawvt** [comment]
@pgray64 and @keithgee, thank you very much for working on this. I have created an issue, https://git.it.vt.edu/it-services/vtlibans_dspace/issues/91, in the vtlibans project to continue this work.

**Comment by alawvt** [comment]
Please try to implement with a self-signed certificate.

**Comment by alawvt** [comment]
Please try to implement this with a Merge Request in the vtlibans project.

**Comment by keithgee** [comment]
This has been deployed to dev/pprd/prod. 
Documentation and a python script for checking that the REST API is operational, and to check on item security will be in the vtlibans project.
