### ISSUE TITLE
SWORD broken on production?

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#491]
SWORD appears to be broken on production VTechWorks.
I'm unable to get a Service Document.

There's also some unexpected behavior - error messages show http in urls instead of https, even when accessed via https.

**Comment by keithgee** [comment]
I put in a TeamDynamix ticket request 2945569 because I'm not sure if we will fix this in VTechWorks, or if ITS can doing something with server or network configuration.

> SWORD is broken on VTechWorks.
Attempting to access https://vtechworks.lib.vt.edu/sword/servicedocument/10919/18629 (and entering my username and password on VTechWorks) gives an error message: Unable to recognise URL as a valid service document: http://vtechworks.lib.vt.edu/sword/servicedocument/10919/18629.

>I noticed that this URL reported in the error is http, not https. Is this expected behavior with our current setup? Would anything that we're doing cause the server to think that URLs accessed via https used http? For example, it was mentioned today that we terminate SSL at the load balancer.

>The SWORD apps, both v 1.x and v1.2, do some checking on the request URL, and I believe that the unexpected "http:" instead of "https:" is causing SWORD to break. Is there a fix for this in the network configuration, or do we need to work around this in VTechWorks?

>This affects BioMed Central deposits, and also will need to be fixed before we upgrade to Repository Tools 2 in Symplectic Elements. Our last BioMed Central deposit was September 23 2016. It's possible - though not necessarily the case - that this has been broken for that long.

**Comment by alawvt** [comment]
@keithgee and @pgray64, thank you very much for researching this issue and reporting in in TeamDynamix.

**Comment by keithgee** [comment]
Aaron responded and said that the behavior I'm seeing is expected with our setup. The easiest fix for us might be to set separate, explicit http urls in the sword-server.cfg and swordv2-server.cfg files. They need to be different for dev, pre-prod, prod and LDEs though. @alawvt and @pgray64, do either of you know how to parameterize these configuration settings so that they can be different on each server? I get confused every time I look at it.

**Comment by alawvt** [comment]
@keithgee, thanks for relaying a possible solution. @pgray64, would you take a stab at it as a Merge Request in the vtlibans project and, @zoto724, would your review it?

**Comment by pgray64** [comment]
I pushed  to a branch https://git.it.vt.edu/it-services/vtlibans_dspace/commits/conditional_https so that in site_secrets you can specify https or http depending if you are on LDE or not (https being the default so it doesn't break anything).

The above setting is used in dspace.cfg, which is in turn used in both sword config files.

The actual hostname is appearing as http://vtechworksvm on my LDE, so that still needs to be fixed.

**Comment by keithgee** [comment]
Thanks @pgray64. There's a bit of a twist with the way that we have things configured.
With the current configuration, on the development, pre-prod, and production servers, the urls in dspace.cfg must be configured with https, while the urls in the sword config files must be configured with http.

This is counter-intuitive. I'm fuzzy on the exact details but I'll try to explain. There's a load balancer that ITS has configured that sits somewhere between the web browser and the Apache server for VTechWorks. I'm not sure why the load balancer is there right now; perhaps it offers some administrative advantages for ITS, and if we ever wanted to have two VTechWorks servers to handle more load, this is one less step that would need to be done before we could achieve that. The https/SSL traffic stops at the load balancer. The connection between the load balancer and the VTechWorks application server has been assumed to be secure, so traffic between the load balancer and VTechWorks is sent as plain old HTTP.

The SWORD apps running on the VTechWorks server are picky, and do some checking on the URLs that were used to access the app. With the current configuration of servers and networking, the app is expecting to see https on the URLs (because SWORD uses the setting in dspace.cfg when the SWORD cfg isn't set explicitly). It sees http instead, because this is how the load balancer is communicating with VTechWorks, and rejects the connection.

Meanwhile, we can't switch the main dspace.cfg on development, pre-prod, or production to have "http" instead of "https" in the urls because that breaks password resets and other things. There are some closed issues on GitHub (#309) with more details about that problem.  

We can resolve the issue by explicitly setting SWORD urls as http in the sword.cfg file. There are other ways to fix it, I think, but the advantages to this method are that it's relatively quick, I know it works (tested on dev), and ITS doesn't need to spend extra time helping us to solve it. Disadvantages: it could break in the future if the app server or network configuration changes again.

This is probably still unclear; perhaps we should all chat after standup.

**Comment by pgray64** [comment]
Okay, I understand. So this should work fine on LDEs too.

**Comment by keithgee** [comment]
I'll confess here, too, that last week I tested the SWORD http configuration on dev only for the service document url and the service document request. I didn't change all of the URLs and test a full deposit.

**Comment by pgray64** [comment]
The only files that need to be changed are sword configs in dspace, since the hostname already exists as a variable without the protocol specified. Testing the changes now on LDE.

**Comment by pgray64** [comment]
Something like https://github.com/VTUL/vtechworks/tree/sword_http_fix I think would work, though I managed to break my LDE and therefore didn't have time to test the change today.

**Comment by pgray64** [comment]
PR #493 addresses this.

**Comment by alawvt** [comment]
@zoto724 has fixed this with a change to the vtlibans project, https://git.it.vt.edu/it-services/vtlibans_dspace/commit/63b771601ed7c3966f5999426d780c049d7c40a1.

Thank you, @keithgee, @pgray64, and @zoto724!

**Comment by alawvt** [comment]
I added another fix for SWORDv2 in https://code.vt.edu/it-services/vtlibans_dspace/commit/64d0c00de522daa6797ffdc6a1330b83d06b1900. Both of these specify `http` as the base url so SWORD and SWORDv2 will work correctly.
