### ISSUE TITLE
Set up connection for SWORD ingest from Hindawi

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#502]
Set up connection for SWORD ingest from Hindawi. Please document the settings in VTechWorks documentation wiki.

**Comment by pyc1** [comment]
Hindawi was using https with the SWORD endpoints- @keithgee, can you look into our settings to see what the problem might be?  I will start a Hindawi stub on the SWORD wiki entry.  Thanks!

**Comment by alawvt** [comment]
@pyc1, could you post here the error that they received? That would help with troubleshooting.

**Comment by pyc1** [comment]
Oops sorry- they got a 502 bad gateway error.

**Comment by alawvt** [comment]
Thanks, @pyc1. I added @keithgee as a mention to your message.

**Comment by keithgee** [comment]
The problem may not be on our end. The DSpace log files show that BioMed Central successfully uploaded via SWORD on September 2nd. I can't find any activity for the Hindawi email address in our log files except for when the account was created and the password changed.

After our discussion in the group today, @pyc1 will send sample SWORD curl commands to Hindawi for testing on the command line, and also ask from which IP address or range the SWORD deposits are initiated. If we get stuck we'll pass this information along to ITS for troubleshooting, in case they are blocked from VTechWorks for some reason.

**Comment by keithgee** [comment]
I forgot to add that I'm able to access the service document at https://vtechworks.lib.vt.edu/sword/servicedocument, using web browser from on campus and off-campus. This hints to me that it is more likely to be an issue related to networking than a problem with the DSpace configuration.

**Comment by pyc1** [comment]
Should that be the endpoint, then, instead of just /sword which returns a 404?

**Comment by keithgee** [comment]
@pyc1 you can send them that information as well, as it may be helpful to them. Perhaps that's the URL that they need.

**Comment by pyc1** [comment]
The service document seemed to help.  Earlier today they uploaded 211 articles in both XML and PDF.  @keithgee I was wondering if this would cause a thumbnail generation problem, so on one article I put the PDF before the XML (https://vtechworks.lib.vt.edu/handle/10919/79127).  Other issues include:

- Not sure if there are any duplicates; do we have a way of detecting these?
- dc.date problems (for example, 2004-1-1)
- dc.description.version=Peer Reviewed; is that consistent throughout VTechWorks?
- copyright on PDF sometimes in conflict with dc.rights.holder (copyright with CC BY)
- language standard is rfc3066 (?) = en

**Comment by alawvt** [comment]
[Hindawi](https://vtechworks.lib.vt.edu/handle/10919/78797) collection

The easiest way to look for duplicates is to export the metadata for the collection and search in the CSV. 

I'd ask them to fix their dates in the future. You could fix these dates manually and re-import the csv. I should show you first our procedure for batch metadata changes. 

I think the "Peer Reviewed" is ok, at least for now. "en" is ok.

**Comment by alawvt** [comment]
The collection looks good.
