### ISSUE TITLE
Upload 17 theses and 4 dissertation ETDs in upload_problems_20170428

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#508]
In Google Drive...VTechWorks/Content/BTD_ETD_projects/etd_db_ingest/ETD-db_upload_problems_20170428 is a spreadsheet of 17 theses and 4 dissertations to load. The associated files are in folders in that folder. Please follow the notes in the spreadsheet. Upload the metadata files with the batch metadata upload tool and web interface. Record ETDs that are missing files in the missing files list. Record the uploaded ETDs to the Google Drive... VTechWorks/Content/ETDs/ETD-dbGonePublic2016_2017.

**Comment by kdweeks** [comment]
While working on:
etd-51797-145925 - at: [http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/etd.htm](http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/etd.htm) 
Used Acrobat to crawl 308 pages with 84 errors.  
Error Summary Base URLs:

[http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/carnitine/](http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/carnitine/)

[http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/cyclooctane/](http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/cyclooctane/)

[http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/methylphosp/](http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/methylphosp/)

[http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/phosphacinium/](http://theses.lib.vt.edu/theses/available/etd-51797-145925/unrestricted/full_text/phosphacinium/)

**Comment by alawvt** [comment]
@kdweeks, thanks for the notes on spreadsheet about the 16 theses you have uploaded and the metadata for the dissertations.

**Comment by alawvt** [comment]
Issue is complete
