### ISSUE TITLE
Error submitting new content to VTechWorks

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#509]
When trying to upload an item to VTW through the submission form, the submission cannot be completed. When you select "next" after reviewing your submission, the  generic error page comes up.  I tried to submit to both the Division of Student Affairs Collection (https://vtechworks.lib.vt.edu/handle/10919/19173) and the University Libraries test collection (https://vtechworks.lib.vt.edu/handle/10919/64337), and the same thing happened both times. So this appears to be a systemic issue. Could someone please take a look?

**Comment by alawvt** [comment]
@arunkp7489 rebooted Tomcat; still getting the error.

**Comment by cecross1** [comment]
FYI, batch uploading via csv is still working.

**Comment by keithgee** [comment]
Upload via web on VTechWorks prod seems to be working now;  @alawvt is following up with ITS.

Verified by @alawvt, @cecross1, and @keithgee .

**Comment by alawvt** [comment]
This was caused when the VM was automatically moved to a new host following a hardware failure on Sunday. It was resolved by moving the VM manually to a new host and restarting.
