### ISSUE TITLE
Error with thumbnails of new items in VTechWorks (resolved)

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#510]
Thumbnails of newer items in VTechworks weren't loading properly. An example:

https://vtechworks.lib.vt.edu/bitstream/handle/10919/79732/Nelson_AJ_D_2016.pdf.jpg?sequence=4&isAllowed=y

Instead of returning the thumbnail, this returned the libraries error page (we're working on the problem, this page will attempt to reload every 30 seconds)

Loading the thumbnail directly (via http connection to Tomcat or Apache httpd) worked successfully. Changing the parameters to the url (examples: https://vtechworks.lib.vt.edu/bitstream/handle/10919/79732/Nelson_AJ_D_2016.pdf.jpg , https://vtechworks.lib.vt.edu/bitstream/handle/10919/79732/Nelson_AJ_D_2016.pdf.jpg?sequence=4&isAllowed=yep) also loaded the thumbnails successfully.

This was broken for items uploaded over the last few days for at least several hours but now is working. Perhaps it was related to cache settings on the F5 or elsewhere?

This is resolved (but the VTechWorks team doesn't know how) I'm documenting it in case it was related to problem #509 , error submitting new content to VTechWorks, which was more important and also appears to be resolved.

**Comment by keithgee** [comment]
Tagging @zoto724 @arunkp7489 and closing. This appears to be resolved, at least presently.

**Comment by alawvt** [comment]
This was caused when the VM was automatically moved to a new host following a hardware failure on Sunday. It was resolved by moving the VM manually to a new host and restarting.
