### ISSUE TITLE
Test REST API in LDE

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#512]
@keithgee and @alawvt tested the latest commit from the add_5_8_changes branch, with the REST API script in https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api. Both found that item deposit only worked every 2nd run of the script. The other runs resulted in a 500 error.

@alawvt then checked out the commit before the add_5_8 branch, https://github.com/VTUL/vtechworks/commit/410cd071c8635eaea6c846eb55291de766c6bc33. With that commit, the script was able to add an item every run of the script.

**Comment by keithgee** [comment]
Thanks @alawvt. I may try with the scripts here:
https://gitlab.c3sl.ufpr.br/bnzanette/dspace-rest-requests

and check for different results. The test script we used started out as prototyping while I was at CPUT, and is bad code.

**Comment by alawvt** [comment]
Anton from University of Canterbury reports they are using Repository Tools 2 with DSpace 5.8, which indicates that item submission works with the REST API in DSpace 5.8 or that Symplectic has some way around it.

**Comment by alawvt** [comment]
I have been able to use the REST API with curl commands documented in https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api.
