### ISSUE TITLE
Item counts incorrect on pprd

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#521]
Last summer we de-dupped ~800 ETDs on production. Recently, we refreshed dev. with a copy of the production database and re-indexed. The item counts match for both servers. Then we refreshed pprd with a copy of the production database and re-indexed. The item count is too high for the ETD collection by ~800. Repeated indexing, `/bin/dspace index-discovery -b` yields no change. 

This morning we have tried `dspace index-discovery -c` https://wiki.duraspace.org/display/DSDOC5x/Discovery followed by `dspace index-discovery -b`.

@keithgee, have you ever used `dspace index-discovery -c`? It is suppose to delete all the documents in the SOLR core. It doesn't seem to have made any immediate difference.  Also, usually `/bin/dspace index-discovery -b` takes all the item counts to 0 and they build back from there but that is not happening now - the item counts have not changed. @zoto724 manually deleted the SOLR index and it is being rebuilt.

**Comment by keithgee** [comment]
@alawvt I don't think that the command:

> index-discovery -c

 has worked for me as I would have expected it to work. I remember that @AmberPoo1 had a problem on her LDE at one time where we had to delete a corrupt Solr index to fix an issue, so I think that the approach that @zoto724 took is a good step.

**Comment by alawvt** [comment]
@keithgee, thanks for the information about the `-c` command. The indexing has finally finished on pprd and the item counts are now correct. Perhaps it was a corrupt Solr index.
