### ISSUE TITLE
Update bower registry URL for Mirage 2

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#522]
From: Kim Shepherd <kim@shepherd.nz>
Date: Tue, Jun 26, 2018 at 1:35 AM
Subject: [dspace-tech] Important notice for XMLUI Mirage2 users (new bower registry URL)
To: DSpace Technical Support <dspace-tech@googlegroups.com>, DSpace Developers <dspace-devel@googlegroups.com>, DSpace Community <dspace-community@googlegroups.com>

Hi all,
 
If you use XMLUI with the Mirage2 in DSpace, you will need to update the bower registry URL used during builds (mvn package) of DSpace, as it has (in just the last few days) been taken offline. This URL has been deprecated for a while now, unfortunately it wasn't obvious that this was the default URL used in our version of bower.
 
This will be fixed in DSpace 6.3 and 5.9, due to be released very soon, but it will affect your existing source, so here are some tips if you need to fix your in-place DSpace source:
 
Quick fix instructions:
==
Edit the file ${dspace-src}/dspace-xmlui-mirage2/src/main/webapp/.bowerrc so that it reads:
{
    "directory": "vendor",
    "registry": "https://registry.bower.io"
}
 
(at the moment, you'll probably just see the "directory" property... the default registry for the version of bower we're using is the bad / deprecated one)
 
Once you've made this change, you'll be able to build XMLUI with Mirage2 again. Depending on how you manage your code base / version control, you might like to do this in a fix branch or as an override in your dspace-src/dspace/modules directory (I haven't tested this method) rather than directory in the dspace-xmlui-mirage2 directory.
 
There's more information available at 
https://jira.duraspace.org/browse/DS-3936 (JIRA issue)
https://github.com/DSpace/DSpace/pull/2099 (Github PR applied to 5.x, 6.x)
 
Cheers!
 
Kim

**Comment by alawvt** [comment]
I have added commit https://github.com/VTUL/vtechworks/commit/a4e9a5dc1ad5eb2993e85c28306650b942d76d51 to the vt_5_x_dev branch to resolve this issue.

**Comment by alawvt** [comment]
@soumikgh and @zoto724, please note this commit may be needed for your deployments to pprd and prod but has not been pushed to those branches yet.

**Comment by soumikgh** [comment]
Got it. I'm going to deploy to pprd in a bit, and I'll put this commit in.

**Comment by alawvt** [comment]
Reported for pprd, adding the bower registry URL breaks the UI when DSpace is deployed. I don't have the specific error message, but it complains about not being able to find bootstrap.css for the Mirage2 theme or something to that effect. I re-deployed without that change and the UI comes up properly.

We will have to revisit this issue.

**Comment by alawvt** [comment]
It was missing a comma, which I added in https://github.com/VTUL/vtechworks/commit/b59db43e0d289f32956cc1adb97eb3157862a581.
