### ISSUE TITLE
Manuallly uploaded thumbnail not displaying because of non-matching file name.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#523]
@pyc1 created a thumbnail for an item (Welcome to the Beatles) because the automaticly created one is not as good.  In the index on the collection page, the manually created thumbnail appears (https://vtechworks.lib.vt.edu/handle/10919/10194, see recent submissions), but on the item itself the automated one shows up (https://vtechworks.lib.vt.edu/handle/10919/83838).  This is after deleting the automatically created one once.

@keithgee replied that if you use the same base name as the original file (with the hyphens and everything, plus the original extension before .jpg), this will convince DSpace that it doesn’t need to generate another thumbnail.

Try naming the thumbnail that you made with the exact same name as was given to the automated thumbnail. Then when you delete the automated one, it shouldn’t be generated again.  It’s a bit of a flaw in DSpace that it can’t determine which thumbnail goes with which original file without the naming conventions.

**Comment by alawvt** [comment]
Thank you, @keithgee, for this important information.

**Comment by alawvt** [comment]
@pyc1, it does look like you need to rename the PDFs to match the thumbnails or delete the thumbnails with old names.

**Comment by pyc1** [comment]
Done, thanks.
