### ISSUE TITLE
Add url to dspace/config/modules/swordv2/swordv2-server.cfg

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#525]
For SWORDv2 to work correctly, which is necessary for Elements Repository Tools 2 (RT2), it needs to create URLS that begin with HTTP, not HTTPS. Therefore, we need to add the url variable to [dspace/config/modules/swordv2/swordv2-server.cfg](https://github.com/VTUL/vtechworks/blob/vt_5_x_dev/dspace/config/modules/swordv2-server.cfg), below line 13. The values should be

production:
url = http://vtechworks.lib.vt.edu/swordv2

pprd:
url = http://vtechworks.pprd.lib.vt.edu/swordv2

dev:
url = http://vtechworks.dev.lib.vt.edu/swordv2

LDE:
url = http://vtechworksvm/swordv2

@zoto724 or @soumikgh , do you want us to add this as a variable in this config file and you define the value of the variable in the vtlibans project? If so, what variable name do you want? Thanks.

**Comment by keithgee** [comment]
Thank you for documenting this, @alawvt .

**Comment by alawvt** [comment]
We will proceed with this once the Ubuntu 18.04 upgrade is complete on production.

**Comment by alawvt** [comment]
@soumikgh has added this variable to dev and we are now able to deposit to dev using RT2. Thank you very much!

**Comment by alawvt** [comment]
This has been implemented on pprd and prod. Thank you.
