### ISSUE TITLE
Condolence archives map based on retired Viewshare platform no longer working

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#531]
This is minor, and I think it only is an issue in one landing page for a single collection.

Some years ago, a special collection for the April 16, 2007 condolence archive was created in VTechWorks. 

https://vtechworks.lib.vt.edu/handle/10919/11385

The collection was given unusual features, and I believe most of these features were accomplished by using html in the DSpace collection description field, in the settings page for the collection that is accessible to administrators.

One of the features was a map with a marker for each location that sent items to Virginia Tech. The map linked to a Viewshare document that allowed for some interactivity and visualizations.

Today, clicking on the map sends the user to a page that explains that the Library of Congress retired the Viewshare service in March of 2018, and the document is no longer available.

**Comment by alawvt** [comment]
@keithgee, thank you for reporting this. I have been aware of it and have asked whether a  replacement map would be possible. I will follow up on that request.

**Comment by alawvt** [comment]
@zhiwuxie suggested Historypin, https://www.historypin.org/en/. I have added a task to the Backlog to investigate recreating the map with Historypin.

I have removed the text for the map from the collection introductory text.
```
<h2>Explore the Collection by Place of Origin and Date Created</h2>
<p/>
<p/>
<p><a href="http://viewshare.org/share/836f4bbe-744c-11e1-b2f3-4040e007d488/" target="_blank"><img src="https://static.lib.vt.edu/vtechworks/4_16_viewshare.png" alt="Viewshare" width="568" height="248"/></a></p>
```
