### ISSUE TITLE
Change URLs for dev and pprd to https://vtechworks-dev.cloud.lib.vt.edu/ and https://vtechworks-pprd.cloud.lib.vt.edu/

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#534]
Change URLs for dev and pprd to https://vtechworks-dev.cloud.lib.vt.edu/ and https://vtechworks-pprd.cloud.lib.vt.edu/. These will be the same virtual machines as https://vtechworks.dev.lib.vt.edu/ and https://vtechworks.lib.vt.edu/, just new URLs.

**Comment by alawvt** [comment]
I have requested this change in the Element installation script and will verify after refresh.

**Comment by soumikgh** [comment]
We might need to re-deploy the pre-prod and dev instances to change the places in the configuration files where it uses the public URL of the instances. Or we might not even need to. Let me know if you run into issues regarding this.

**Comment by alawvt** [comment]
I announced the new URLs to Libraries and Elements personnel.

**Comment by alawvt** [comment]
I think we will need to redeploy them after we are sure the Elements setting have been changed correctly. The edit page for an item, for instance, https://vtechworks-pprd.cloud.lib.vt.edu/admin/item?itemID=94435, lists,

Item Page: | https://vtechworks.pprd.lib.vt.edu/handle/10919/83527
-- | --

and will need the correct URL.

**Comment by alawvt** [comment]
These changes have been made and the servers redeployed. Thank you, @soumikgh and @zoto724.
