### ISSUE TITLE
Resolve slow re-indexing on vtechworks.lib.vt.edu

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#535]
The DSpace 5.8 (Yak sprint) changes were deployed to vtechworks.lib.vt.edu yesterday morning. All tests that do not require indexing have passed, #513. However, indexing has been extremely slow and has restarted twice. I have added an alert to VTechWorks notifying of the trouble. 

@zoto724 is working on the problem and asks that we avoid loading new items until this is resolved. Yesterday, he tried migrating it to a SSD, however that did not affect the indexing rate.

**Comment by keithgee** [comment]
Only of interest if the Java version was changed recently, but the bin/dspace script that launches command line utilities such as the indexer has memory parameters for the Java VM. A few years ago @yinlinchen mentioned that different versions of Java may have different parameters for memory settings.  Probably not relevant here unless the Java version changed, but worth knowing.

**Comment by keithgee** [comment]
Regarding my previous comment, I think Yinlin may have just been explaining to us that the PermGen area was gone in newer versions. I don't think we adjusted that for DSpace anyway.

**Comment by alawvt** [comment]
@keithgee, thanks for that information about the Java memory settings.

@soumikgh and @zoto724 moved reindexing to a cloned VM and copied the index back to production. VTechWorks seems to be working fine. Also, they found that reducing the verbosity of the logs sped up the indexing.

@soumikgh noted that DSpace will automatically re-index if the release contains any database updates, https://wiki.duraspace.org/display/DSDOC5x/Upgrading+DSpace.  According to the DSpace 5.8 release notes, https://wiki.duraspace.org/display/DSDOC5x/Release+Notes#ReleaseNotes-5.8ReleaseNotes,” As it only provides bug fixes, DSpace 5.8 should constitute an easy upgrade from DSpace 5.x for most users. No database changes or additional configuration changes should be necessary when upgrading from DSpace 5.x to 5.8.” Apparently something else triggered the re-indexing.

Thank you very much, @zoto724 and @soumikgh!

**Comment by alawvt** [comment]
I notice that indexing is slow on my LDE with the latest vtlibans deploy. It used to take about an hour to index ~55,000 items. It has been an hour and it has only indexed 8,500 items.
