### ISSUE TITLE
Change EFARS name on home page to Elements

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#543]
We have been asked to change the name, "EFARS" to "Elements."

Currently the text on the home page is, 

"NEWS: Faculty can now deposit items to VTechWorks from the Electronic Faculty Activity Reporting System (EFARS). Visit the Provost's EFARS page to learn more and to log in to EFARS."

@pyc1, is the following ok with you?

"Faculty can deposit items to VTechWorks from the Electronic Faculty Activity Reporting System (Elements). Visit the Provost's Elements page to learn more and to log in to Elements."

**Comment by pyc1** [comment]
Yes, looks good to me, thanks.

**Comment by alawvt** [comment]
This has been resolved with commit https://github.com/VTUL/vtechworks/commit/76e46f6a6a11e5dc24e323e12ee29a2103b6b5a4
