### ISSUE TITLE
Upgrade from DSpace 5.8 to 5.10

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#550]
Upgrade from DSpace 5.6 to 5.8, https://github.com/DSpace/DSpace/releases/tag/dspace-5.10.

**Comment by alawvt** [comment]
Please also add Andrew Bennet's commit in PR [[DS-4085] Update abdera-client dependency to 1.1.3 #2271](https://github.com/DSpace/DSpace/pull/2271).

**Comment by alawvt** [comment]
I have pushed branch, add_5_10_changes. Currently, it builds with a blank window for http://192.168.60.4. However, http://192.168.60.4/oai/request?verb=Identify does display correctly (the same as vt_5_x_dev). Attached are logs from this branch, [bad_log.txt](https://github.com/VTUL/vtechworks/files/2672930/bad_log.txt) and the latest commit on vt_5_x_dev, [good_log.txt](https://github.com/VTUL/vtechworks/files/2672931/good_log.txt), that does display correctly. @keithgee or @soumikgh, if you see anything obvious in these logs, I'd appreciate it. Otherwise, I will keep digging.

**Comment by alawvt** [comment]
http://192.168.60.4/swordv2/servicedocument produces the username and password form. When I filled it out, it gave message, "This page isn’t working 192.168.60.4 unexpectedly closed the connection. ERR_INCOMPLETE_CHUNKED_ENCODING"

**Comment by keithgee** [comment]
@alawvt, I am closing this issue because I think we're skipping this upgrade and going directly to DSpace 6.3.

Please re-open if this is incorrect.

**Comment by alawvt** [comment]
Yes, thanks, @keithgee.
