### ISSUE TITLE
Import the Biological Systems Engineering collection from Discovery Commons

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#552]
Import the Biological Systems Engineering collection from [Discovery Commons](https://dcr.emd.vt.edu/vital/access/manager/Index?site_name=Agricultural%20Engineering) (1706 items)

The files are located in Google Drive...VTechWorks/Content/Special_VTW_Projects/BSE_collection_from_Digital_Commons

I have prepared a spreadsheet listing the assets in this folder. It appears that these are the files used to initially load the collection into Discovery Commons, rather than files exported from Discovery Commons. For instance, items in Discovery Commons include an identifier such as vatch:58490, which is not listed in the spreadsheet. I would like to get the metadata from Discovery Commons, to get this information, which would allow us to list the source URL and insure that we have exported all the items. According to the information about Vital, https://www.iii.com/wp-content/uploads/2018/11/Vital-WP.pdf, it should be possible to export the metadata from a collection via the command line, https://wiki.duraspace.org/display/FEDORA38/fedora-export, or OAI-PMH. I consulted with Michelle and it is not possible to export any metadata from Vital.

["Engineering a new archive"](https://www.vtmag.vt.edu/winter15/engineering-archive.html) is an announcement about the collection in Virginia Tech Magazine.

There is general information about the collection in https://dcr.emd.vt.edu/vital/access/manager/Help.

**Comment by alawvt** [comment]
@pyc1, to which collection in VTechWorks, do you want this added?

**Comment by alawvt** [comment]
Also, the rights metadata is confusing. All the items I have checked, for example, https://dcr.emd.vt.edu/vital/access/manager/Repository/vatech:59295, have:

Rights=Reproduction for publication, exhibition, web display or commercial use is only permissible with the consent of the College of Agriculture, Virginia Tech (see contact link). (imaging@vt.edu).


Access Rights=Public Domain

**Comment by alawvt** [comment]
Please replace underscores "_" in subjects and dc.coverage.spatial with spaces, " " (and any other fields besides file name and id.) The underscores were part of the hyperlinking of subjects and locations in [Discovery Commons](https://dcr.emd.vt.edu/vital/access/manager/Index?site_name=Agricultural%20Engineering).

**Comment by kdweeks** [comment]
The VTechWorks collection for this content is here:
https://vtechworks.lib.vt.edu/handle/10919/87778

**Comment by kdweeks** [comment]
I am working on the the 2nd batch of project 10, and thus far there are no extensions in the "filename" column to denote what type of file in the file folder and should be loaded to VTechWorks.  When there are multiple file types in a batch,  this will need to be done by hand I think.  HMMM.  In the first batch, the actual filename did not match the filenames in the metadata spreadsheet.

**Comment by alawvt** [comment]
@kdweeks, thanks for resolving the filenames in the first batch. Perhaps each item has multiple files with the same name but different extensions. I can't remember off hand whether the other image batches had multiple files per item. I think not, so this may the only one that needs extensions.

**Comment by kdweeks** [comment]
@alawvt The documents batch from AE_documents/AE_publish_load_6-11-14/documents filename list not only didn't have extensions but there were 2 files per item both with different extensions and only a single root name was listed.  Luckily both files per item shared the same root name, and there was exactly one .pdf and one .png per item.  With over 400 files, this could have been a lot worse.  I was able to use BBEdit to prepare the filenames.

**Comment by alawvt** [comment]
@kdweeks, that's great that you were able to generate the filenames.

**Comment by alawvt** [comment]
completed
