### ISSUE TITLE
Add DPLA OAI crosswalk to vtechworks6-dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#556]
Test an OAI crosswalk to collect metadata for submission to the regional Digital Public Library of America (DPLA) service hub. See VTechWorks wiki page, [Digital Public Library of America (DPLA)]( https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/DPLA) for more detail.

**Comment by alawvt** [comment]
Resolved by #559.

**Comment by alawvt** [comment]
Please add add commits https://github.com/VTUL/vtechworks/pull/559/commits/ff9b77e1f3ecac480216fd1dcd936e5789cd07d7 and https://github.com/VTUL/vtechworks/pull/559/commits/3dd3e1adf6043b209b7ec83fd19cc38922d64a0d on  branch [oai_dpla](https://github.com/VTUL/vtechworks/tree/oai_dpla) to vtechworks_6_dev.

**Comment by keithgee** [comment]
@alawvt these commits have been picked into the vt_6_x_dev branch tonight, and also deployed to dspace 6 dev server.

Some notes:
 - Is there anything missing here, or any additional steps to get this to work? The URLs on the Wiki page (when adjusted for the server name) don't work to get metadata - there's an error that says the metadata format is unknown.
- This also doesn't appear to be deployed into production yet (given recent issues). I don't have anything to compare it against.

**Comment by alawvt** [comment]
@keithgee, thank you very much for committing this change. I do see dplava listed in 

`https://vtechworks6-dev.cloud.lib.vt.edu/oai/request?verb=ListMetadataFormats`. 

The records look correct at 

`https://vtechworks6-dev.cloud.lib.vt.edu/oai/request?verb=ListRecords&metadataPrefix=dplava&set=col_10919_10202` (notably they include the `<edm>` elements including thumbnail URL). 

A sample record is at 

`https://vtechworks6-dev.cloud.lib.vt.edu/oai/request?verb=GetRecord&metadataPrefix=dplava&identifier=oai:vtechworks6-dev.lib.vt.edu:10919/10396`. 

I added these examples on vtechworks6-dev to the Wiki. Yes, we have not pushed this to production.
