### ISSUE TITLE
Enable ignore-on-export in dspace/config/modules/bulkedit.cfg

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#563]
As reported in https://jira.duraspace.org/browse/DS-4213, DSpace 6 is no longer setting `ignore-on-export = dc.date.accessioned, dc.date.available,dc.date.updated, dc.description.provenance` by default.
 ```
# Metadata elements to exclude when exporting via the user interfaces, or when using the
# command line version and not using the -a (all) option.
# ignore-on-export = dc.date.accessioned, dc.date.available, \
#                    dc.date.updated, dc.description.provenance
```
Please set this manually.

**Comment by keithgee** [comment]
This is enabled with commit 6d39979fa1a906dbf.

This change was made to the local.cfg file (not in the modules/bulkedit.cfg file) as per the discussion yesterday to keep all VTechWorks configuration changes from the default to a single file, however, we haven't decided on that method yet.

In this commit, in addition to the requested change, the gui-item-limit parameter from the same module was set to 1000, up from its default of 20.

Closing

**Comment by alawvt** [comment]
@keithgee, thank you for changing this. I agree to add it and other config changes to the local.cfg file.
