### ISSUE TITLE
SWORD webapp(s?) configuration issues - DSpace 6

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#566]
@alawvt reported that the SWORD v2 web app was inaccessible on the DSpace 6 test instance of VTechWorks.

The SWORD v2 web app was giving this error message:

> org.swordapp.server.SwordError: Unable to recognise URL as a valid service document: http://vtechworks6-dev.cloud.lib.vt.edu/swordv2/servicedocument 

I believe this was caused by one or all of the following:

1. The host was configured and installed using a different host name before it was opened up to the VTechWorks team for testing under the vtechworks6-dev hostname.
2. Missing changes for VTechWorks specific configuration parameters for SWORD/SWORD v2 modules
3. The deployment is typically handled with our ansible scripts; the scripts were not used in this test deployment because they don't yet work with this version of DSpace.

The SWORD apps perform some checking of request URLs, so the hostname of some requests need to match an expected hostname, and the protocol needs to match specifically http or https.

I made enough changes earlier this morning to hostnames and http/https parameters in local.cfg, sword module cfg, and sword v2 module cfg to allow the swordv2 service document to be accessed on the VTechWorks dspace6 dev server. The hostname in all of these files has been changed to vtechworks6-dev that is currently used for access. HTTPS is being used as the main hostname configuration; certain URLs for the sword and swordv2 web apps must have http instead.

I've not committed these changes, as I'm not sure this fixes everything even on the dev server, and more time is needed to get everything right for production.

Some follow-up is needed in a few weeks when there is more time:

- how much of this issue will be resolved when ansible scripts are updated?
- how much of this issue will be resolved when hosts are accessed only through one hostname, as expected?
- what are the correct (ideal?) settings for host, hostname, and url parameters in dspace.cfg and sword modules for production machines? (This work has likely already been done and documented for our DSpace 5 work - we just need to review it).
- should we make the changes in the separate sword module files (as I've done currently on the dev server) or move them to the local.cfg file. I favor moving them to the local.cfg file so that in the future it's easier to find parameters that we've customized.

**Comment by alawvt** [comment]
Thanks, @keithgee, for working on this. I am now able to access the service document.

**Comment by keithgee** [comment]
I think that most of the answers to the follow-up questions will be discovered as we update Ansible playbooks and complete testing.

**Comment by alawvt** [comment]
This has been resolved in the vtlibans project, https://code.vt.edu/it-services/vtlibans_dspace/issues/106.
