### ISSUE TITLE
Plan configuration files for DSpace 6 implementation

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#567]
@keithgee:

>My suggestion as to the configuration is to make all changes that would have been made to dspace.cfg, the modules configurations, and also build.properties (now removed from DSpace) to local.cfg.DSPACE6DEV. This file gets copied to local.cfg in my install instructions, and overrides all configuration in all other cfg files.

>I've followed this rule, except for the on campus IP ranges. I think my reasons for keeping this in a separate file are that it's a very long parameter, plus it won't change between any VTechWorks systems. These might not be good reasons - it could make more sense to follow the above rule consistently.

>Be aware that configuration parameters that were in DSpace 5 modules have been renamed in DSpace 6 so that the parameter name begins with the module name. For example, the ignore-on-export parameter in the bulkedit module has been renamed to bulkedit.ignore-on-export. 

>What I'm thinking is that when we update the vagrant/ansible deployment process to account for parameter name changes, the removed build.properties file, and whatever other changes we need to make, we might have somewhere (though perhaps not on GitHub because of sensitive information) different versions of local.cfg - local.cfg.DEV, local.cfg.PREPROD, local.cfg.PROD - that the deploy system would copy as appropriate to local.cfg before install. I think this makes sense in that it's more in-line with the DSpace install process and also could simplify the Ansible playbooks, but I've not worked on this and haven't worked with @soumikgh or @zoto724 on this part to see what would make the most sense - this may make less sense from an Ansible-centric perspective.

>Advantages of placing all configuration in local.cfg file:

> - Very easy to find all local configuration changes to DSpace (as long as you understand the rule that local.cfg overrides everything, and that all VTechWorks changes will be in local.cfg).
> - For the above reason, upgrades should be simplified as long as this configuration system remains in place. Look in only one file. No need to diff multiple files or attempt to cherry pick commits that may also affect other files.
> - Potential simplification of deployment process, including updates. In some cases, updates to configuration have required changes to two projects.  I don't think this will be necessary with most changes.

>Disadvantages of placing all configuration in local.cfg file:

>- Loses the advantage of modular organization of configuration files (though the prepended module names help with this slightly)
>- Potentially very confusing if you don't know the rule that local.cfg overrides all other configuration files, and this is where you should look first.

>We can make it work wherever the local customizations are kept, I think, even if they are in multiple files and multiple projects, but this approach makes the most sense to me right now. Feel free to pick another method, but whichever is chosen we should document in this in obvious places and then be consistent.

[DSpace 6 Configuration Reference](https://wiki.duraspace.org/display/DSDOC6x/Configuration+Reference)

**Comment by alawvt** [comment]
@keithgee, I am fine with having all the customizations in the local.cfg file. We will need to have versions of local.cfg for LDE, dev, pprd, and prod. However, I the current version of the common part of the local.cfg file in this GitHub repository so that we can easily track changes to it, much as we do now with dspace.cfg for DSpace 5.

Perhaps, ITS could write a small file for each server, with the additions/changes for each server. When they pull the latest commit, they could merge that file with the common local.cfg. However, I'm not wedded to a particular implementation. I just want one config file that is easily find-able in the repository. For now, how about if we continue to record all config changes in local.cfg.VTDSPACE6DEV and treat it as the common local.cfg file?

**Comment by keithgee** [comment]
@alawvt - yes, this is a good idea. Let's do that.

**Comment by alawvt** [comment]
Per the meeting today, unique values for the servers will be in the libans project.

**Comment by alawvt** [comment]
There are 34 `.cfg` files in DSpace 5:
```
dspace-services/src/main/resources/config/dspace-defaults.cfg
dspace/config/dc2mods.cfg
dspace/config/dstat.cfg
dspace/config/modules/altmetrics.cfg
dspace/config/modules/authentication-cas.cfg
dspace/config/modules/authentication-ip.cfg
dspace/config/modules/authentication-ldap.cfg
dspace/config/modules/authentication-password.cfg
dspace/config/modules/authentication-shibboleth.cfg
dspace/config/modules/authentication-x509.cfg
dspace/config/modules/authentication.cfg
dspace/config/modules/bulkedit.cfg
dspace/config/modules/curate.cfg
dspace/config/modules/discovery.cfg
dspace/config/modules/disseminate-citation.cfg
dspace/config/modules/elastic-search-statistics.cfg
dspace/config/modules/fetchccdata.cfg
dspace/config/modules/google-analytics.cfg
dspace/config/modules/oai.cfg
dspace/config/modules/rdf.cfg
dspace/config/modules/rest.cfg
dspace/config/modules/solr-statistics.cfg
dspace/config/modules/solrauthority.cfg
dspace/config/modules/spring.cfg
dspace/config/modules/submission-curation.cfg
dspace/config/modules/sword-client.cfg
dspace/config/modules/sword-server.cfg
dspace/config/modules/swordv2-server.cfg
dspace/config/modules/translator.cfg
dspace/config/modules/usage-statistics.cfg
dspace/config/modules/versioning.cfg
dspace/config/modules/workflow.cfg
dspace/config/dspace.cfg
dspace/config/modules/clamav.cfg
```

**Comment by alawvt** [comment]
As per our meeting today, I added `local.cfg` to `dspace/config.` However `.gitignore` has
```
# Ignore a local.cfg file in root folder, if it exists
/local.cfg
# Also ignore it under dspace/config
/dspace/config/local.cfg
```

@keithgee, do you think I should remove that from `.gitignore`?

**Comment by keithgee** [comment]
You can do that, but if it were me, I think I'd just use a different name, as I did with local.cfg.VTDSPACE6DEV (which we won't need anymore, by the way). That file would then be copied (and parameterized, if necessary) to local.cfg during installation.

Including local.cfg in .gitignore prevents accidentally checking in a local.cfg file with local modifications, for example during testing with a different customization, or when using a different database url and passwords, which are secrets and shouldn't be in this repository.

Some background here: Initially I was thinking we'd have different versions of the local.cfg files - for LOCAL/DEV/PREPROD/PROD or whatever we needed, and store all of the secret ones in our private GitLab repository, copying whichever we needed to local.cfg.

I think what we've worked out now is we'll store one copy of local.cfg.VTECHWORKS (or whatever you want to call it) that has basically all of our common VTechWorks customizations in it, but then is copied to local.cfg and parameterized by Ansible for hostname and password and whatever else we need depending on where it is being deployed. I'd initially put this as a template file (ansible/roles/deploy/templates/local.cfg.VTECHWORKS.j2) in my experimental branch on the Ansible project because it's parallel to how we'd done things previously, but it sounds like Soumik will be able to modify the project so that we can store the file in our separate GitHub project and still parameterize it as necessary.

That local.cfg.VTECHWORKS.j2 file that's currently in the experimental Ansible branch has some allowances for parameterization:
example:
dspace.hostname = {{ ansible_fqdn }}

Check with Soumik if that's how things will still work when the file is in GitHub. If so, database name/url and password will need to be treated similarly.

Thanks!

**Comment by keithgee** [comment]
It does seem like it might be simpler to just name it local.cfg instead of naming it something else and then copying it. I don't know what's best. Your call, Anne!

**Comment by alawvt** [comment]
I think it would be easiest if the file were named `local.cfg` in this GitHub repository and had the settings needed for the LDE, so that the VM could be built locally with Maven. The vtlibans project would parameterize different settings needed for dev, pprd, and prod.

@keithgee do you have a preference whether we keep `/dspace/config/local.cfg` in `.gitignore` and `git add -f local.cfg` when we want to commit changes to it or whether we remove `/dspace/config/local.cfg` from `.gitignore`?

**Comment by keithgee** [comment]
Anne, it's up to you which of those you prefer.

Note though, that the having a parameterized file doesn't prevent the LDE from being built locally with maven. It would be parameterized with settings in the site secrets file, just like the other systems. It's similar to how the dspace.cfg file is parameterized with our version 5 deployment project. But maybe you have in mind being able to set up an LDE without editing the site secrets file first, saving a step.

Work with Soumik when he's available though though to make sure that he can accommodate whatever works best with your ideas and workflow.

It'll be interesting to see how DSpace works with Docker at OR2019, too - though it might be a bit early to switch to that process and a bit too much at once for us.

**Comment by alawvt** [comment]
Created PR #585 and am testing it.

**Comment by alawvt** [comment]
Resolved in vtlibans issue, https://code.vt.edu/it-services/vtlibans_dspace/issues/111.

**Comment by alawvt** [comment]
Now the dspace-6.x branch in the vtlibans project uses the local.cfg file in the vt_6_x_dev branch in this project.

**Comment by alawvt** [comment]
To clarify, of the 29 config files in DSpace 5,
```
dspace-services/src/main/resources/config/dspace-defaults.cfg
dspace/config/dc2mods.cfg
dspace/config/dstat.cfg
dspace/config/modules/altmetrics.cfg
dspace/config/modules/authentication-cas.cfg
dspace/config/modules/authentication-ip.cfg
dspace/config/modules/authentication-ldap.cfg
dspace/config/modules/authentication-password.cfg
dspace/config/modules/authentication-shibboleth.cfg
dspace/config/modules/authentication-x509.cfg
dspace/config/modules/authentication.cfg
dspace/config/modules/bulkedit.cfg
dspace/config/modules/curate.cfg
dspace/config/modules/discovery.cfg
dspace/config/modules/disseminate-citation.cfg
dspace/config/modules/elastic-search-statistics.cfg
dspace/config/modules/fetchccdata.cfg
dspace/config/modules/google-analytics.cfg
dspace/config/modules/oai.cfg
dspace/config/modules/rdf.cfg
dspace/config/modules/rest.cfg
dspace/config/modules/solr-statistics.cfg
dspace/config/modules/solrauthority.cfg
dspace/config/modules/spring.cfg
dspace/config/modules/submission-curation.cfg
dspace/config/modules/sword-client.cfg
dspace/config/modules/sword-server.cfg
dspace/config/modules/swordv2-server.cfg
dspace/config/modules/translator.cfg
dspace/config/modules/usage-statistics.cfg
dspace/config/modules/versioning.cfg
dspace/config/modules/workflow.cfg
dspace/config/dspace.cfg
dspace/config/modules/clamav.cfg
```
only dspace.cfg file and the dspace/config/modules/*.cfg files will be overwritten by local.cfg? Therefore a file like dstat.cfg will still be changed directly in that file.
