### ISSUE TITLE
Private & Withdrawn Item bitstreams still available via Google

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#57]
Hi all, I sent a lengthy email about this earlier, but withdrawn and/or private DSpace items can indeed be indexed by Google. I learned this the hard way when, in Google, I stumbled upon a link to a bitstream belonging to an item I'd made private in VTW.

The only way I could remove the item bitstream from Google's index was to 1) Delete the bitstream, and 2) Request that Google remove the bitstream's webpage cache. Perhaps I could have changed the bitstream's "read" properties in DSpace, but I didn't know how this would (or wouldn't) affect Google indexing after the fact, so I felt that I just needed to get rid of the bitstream and its cache altogether since, you know, the item should have been private all this time! I may re-upload the bitstream at a later date and change the read policies.

Anyways, it's frustrating that private items aren't really private; I wish I'd known this beforehand. Here are some links to the DSpace JIRA forum that discuss this issue (I've labeled this issue an "enhancement", though it could be considered a bug - but not because of anything on our end):

"Private" Items should include a "noindex" meta tag in the HTML - https://jira.duraspace.org/browse/DS-1980

"Private" Items are incorrectly listed in Google Sitemaps - https://jira.duraspace.org/browse/DS-1977

"Private Items" are misnamed, as permissions/privacy is not really changed- https://jira.duraspace.org/browse/DS-1978

**Comment by alawvt** [comment]
In my experience private items are findable on Google but withdrawn items are not. However items that were previously viewable and moved to withdrawn probably would be viewable unless we ask Google to remove them from their cache.

**Comment by amandafrench** [comment]
Interesting -- and, yes, worrisome. At some point, maybe in a few months when we've made a serious dent in our tech backlog, or maybe even sooner depending on the issue, I'd like us to move more to working on DSpace core, fixing issues that are a problem for us and therefore also for others. This is a good candidate for that.
