### ISSUE TITLE
Test Vtechworks6

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#570]
I have started the testing spreadsheet in Google Drive, `VTechWorks/Testing/DSpace_6.3_Testing`.

**Comment by kdweeks** [comment]
In testing with this spreadsheet, I found the following issue when submitting an item to VTechWorks: 
I was able to add metadata in the two describe tabs (which is weird to me).  Upon file upload I received the following error: Authorization denied for action READ on BITSTREAM:1c2c3bc9-011d-477e-bb22-b6d11b9471e2 by user null, at the following URL https://vtechworks6-dev.cloud.lib.vt.edu/handle/10919/87714/submit/13672a33633111450120248f687d1120762f2750.continue.  I tried to use the "Previous" button, the browser's back button (Chrome 74.0.3729.131), and the "Save & Exit" button.  I got the same error, no escape!

**Comment by keithgee** [comment]
@kdweeks thank you for finding this problem. I believe it may be related to enabling the virus scanner for uploads. So that testing may continue, I've disabled the virus scanner for uploads on the dev system. The virus scanner is still enabled and working from the curation menu.

**Comment by keithgee** [comment]
Virus scanner was enabled with #581

**Comment by keithgee** [comment]
I have tagged this with "waitfordevdeploy". I believe that we are waiting until this is deployed to another system to finish testing.

A DSpace 6 test plan and previous VTechWorks test plans are available on our Google Drive.
