### ISSUE TITLE
Run stats cron job on vtechworks6-dev and check for number of items

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#575]
Run legacy stats cron job on vtechworks6-dev and check for https://github.com/VTUL/vtechworks/issues/319.

**Comment by keithgee** [comment]
#319 is not related to legacy statistics. It's for the solr statistics.

These changes have been incorporated, and the DSpace 6 version of VTechWorks is currently showing 100 items on the statistics-home page.

*Closing

**Comment by alawvt** [comment]
@keithgee, thank you for the correction and incorporating these changes.
