### ISSUE TITLE
Add content types to legacy statistics in vtechworks6-dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#580]
Please add the list of content types for the legacy statistics listed in PR #347 to vtechworks6-dev. It would be good if the legacy stats files were added so we can check how they appear, see https://code.vt.edu/it-services/vtlibans_dspace/wikis/home#legacy-stats-migration.

**Comment by keithgee** [comment]
I've incorporated commit 1f2e6f8e497cd9 into the vt_6_x_dev branch.

This applies changes directly to dstat.cfg, which is an exception to our new policy of making changes to our local.cfg template and not in other configuration files.

At a glance, it appears that this file must be separate - it's not in a modules directory and the names aren't parameterized. And note that the legacy statistics are no longer supported.

**Comment by alawvt** [comment]
Yes, dstat.cfg is not in the modules folder and not included in dspace.cfg, so it needs to be customized separately from local.cfg.

**Comment by keithgee** [comment]
Okay, good to have confirmation. Another quick note on this - Aaron suggested that we turn down the log levels very low to help with performance. These legacy statistics depend on log files, so it's possible that they'll break more when the log levels are turned down.

**Comment by alawvt** [comment]
I would be willing to try reducing the log levels once we have 6 on production and fully tested. We need to check the impact on the stats. I also need the logs to track Elements problems.
