### ISSUE TITLE
Ensure that ClamAV is enabled in vtechworks6-dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#581]
PR #314 adds settings for  dspace/config/modules/clamav.cfg,  dspace/config/modules/curate.cfg, and  dspace/config/modules/submission-curation.cfg. Please ensure that these changes have been added to vtechworks6-dev. Also "Scan for viruses" is not appearing in the System Curation Tasks list and should be enabled.

**Comment by keithgee** [comment]
Partially addressed with commit 314f80ce7100, which adds the custom ClamAV parameters to our Space 6 configuration and enables the virus scan during submission.

Unsure why "Scan for viruses" is not appearing - I'm looking into this.

**Comment by keithgee** [comment]
"Scan for viruses" is appearing in the Systems Curation Tasks list with commit fc13a4535bdbcf56.

**Comment by keithgee** [comment]
Scan during submission is disabled on dev at the moment (but not reverted in commits) due to an issue reported by @kdweeks with new uploads. Scan in curation tasks is still enabled.

**Comment by alawvt** [comment]
@keithgee, I just checked the Scan for Virus curation task on my LDE on the search_filters_facets branch and received, 

`STATUS: Error, RESULT: Unable to connect to virus service - check setup`

On my LDE, /dspace/config/local.cfg has
```

################################
# ClamAV module customization  #
################################
#
# Initial timeout value (in milliseconds) used when the socket is connecting
clamav.socket.timeout = 5000

# Flag indicating whether a scan should stop when the first infected bitstream
# is detected within an item. Normally a complete scan is desired, so default
# value is false. But if items can contain large numbers of bitstreams, the
# display of the results can become unwieldy.
clamav.scan.failfast = true

#---------------------------------------------------------------#
#------------SUBMISSION CURATION CONFIGURATIONS-----------------#
#---------------------------------------------------------------#
# Scan for viruses
# Virus scan during submission is currently not enabled to allow
# for continued DSpace 6 testing.
# Submissions were failing when this was enabled.
# Virus scan as a curation task is still enabled.
#submission-curation.virus-scan = true


#------------------------------------------#
#    curate.cfg module customization       #
#------------------------------------------#
# Friendly names for curation tasks to appear in admin UI
# Also acts as a filter - i.e. tasks not enumerated here can still
# be invoked on cmd line, etc - just not in UI
curate.ui.tasknames = profileformats = Profile Bitstream Formats
curate.ui.tasknames = requiredmetadata = Check for Required Metadata
curate.ui.tasknames = checklinks = Check Links in Metadata
curate.ui.tasknames = vscan = Scan for Viruses
```
so submission is disabled but it seems like the curation task should work.

**Comment by keithgee** [comment]
I've added an Ansible task over in our Dspace 6 version of the vtlibans_dspace project to start the clamav daemon automatically. In my testing, this resolves the curation task issue again. I'm testing a potential fix for the other issue, scanning during initial submission.

**Comment by keithgee** [comment]
The remaining issue has been corrected with commit 6cbbdfd, except I forgot to enable the virus scanner in the configuration file again.

**Comment by alawvt** [comment]
@keithgee, please enable ClamAV in the config so we can test it.

**Comment by keithgee** [comment]
Commit 0d1b112 enables clamAV in the config.
@alawvt, I can leave this issue open if you'd like to verify the fix. It ended up being two simple fixes, but finding things and testing has proven tricky.

**Comment by alawvt** [comment]
@keithgee, thank you very much for your work on this. I will build it now to verify.

**Comment by alawvt** [comment]
Success: the latest build ran both the ClamAV curation task and detected a file with a virus during submission.
