### ISSUE TITLE
Ensure that only logged-in users can request a copy of a restricted item in vtechworks6-dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#583]
As in PR #75, please ensure that only logged-in users can request a copy of a restricted item in vtechworks6-dev.
 
dspace/config/dspace.cfg  
`request.item.type = logged`

**Comment by keithgee** [comment]
Reinstated with commit c4d2b422bf77bbe2, but placed in local.cfg template instead.

However, this is not the way the current production VTechWorks system is configured.

My thought is that we might limit new customizations (even configuration) that aren't currently in production until we've completed the upgrade, just to help get this done, given the current situation. Do you agree?

**Comment by keithgee** [comment]
I got feedback from Gail and @pyc1. Anyone should be allowed to request a copy.  
I have reverted the previous commit with new commit 5433cc5aa42f3aaf770148c370e8.
