### ISSUE TITLE
Load publications from old Special Collections website

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#586]
I would like to propose the inclusion of Curtis W.  Roane’s (professor emeritus of Plant Pathology, Physiology, and Weed Science at VT, 1921-2018) “A History of Plant Pathology in Virginia (1988-1997) for inclusion in VTechWorks. It is another series of pages lost in the recent website transition in Special Collections. The site may be viewed on the “way back “ machine: https://web.archive.org/web/20170907193107/https://spec.lib.vt.edu/archives/ppws/plant.htm

I also have an additional paper biography (27 pp.)  by Dr. Roane, who used to be a frequent visitor to Special Collections, on Roland Jay Stipes, a professor emeritus in Landscape tree pathology. 

Here’s another possibility for VTechworks by Dr. Robert W. Walters and Jane Echols Johnston: https://web.archive.org/web/20180521162556/http://spec.lib.vt.edu/archives/depthistory/aero/AeroHistory.pdf

Let me know if you think it’s appropriate. This was another offering on the COllege and Departmental Histories at Virginia Tech site: https://web.archive.org/web/20180521151343/http://spec.lib.vt.edu/archives/depthistory/

**Comment by gailmmac** [comment]
It all sounds appropriate to me.

Gail McMillan
Director, Scholarly Communication <http://scholar.lib.vt.edu>
Professor, University Libraries
Virginia Tech
orcid.org/0000-0001-8817-3819

**Comment by pyc1** [comment]
These three publications are now in VTechWorks.
