### ISSUE TITLE
Sherpa/Romeo lookup in submission form not working

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#588]
in the submission form, if you choose the content type, Article, then on the second page of the submission form will be a textbox for Journal Title. The Sherpa/Romeo lookup button is below this textbox. When I submit a journal name in the textbox, there are no results and "untranslated," see screenshot. 
<img width="1303" alt="SherpaSubmissionFormError" src="https://user-images.githubusercontent.com/13037168/60130366-16b59200-9765-11e9-9832-e041e854b050.png">

**Comment by alawvt** [comment]
Well, it works this morning--go figure. Yesterday, I tried the Sherpa REST-API from a browser and it worked, so I had assumed that it wasn't the Sherpa REST-API. But I don't know what else it might be.

**Comment by cecross1** [comment]
This happened again today. But this time, after pushing the lookup button, all the metadata that I'd entered into the form disappeared. The submission is still listed as in progress, but all the blanks are empty now.
