### ISSUE TITLE
Configure bitstream storage in config/spring/api/bitstore.xml

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#593]
Configure bitstream storage in config/spring/api/bitstore.xml.

from DSpace 6 dspace.cfg
```
##### Asset Storage (bitstreams / files) ######
# Moved to config/spring/api/bitstore.xml
```
See [Configuring the Bitstream Store](https://wiki.duraspace.org/display/DSDOC6x/Storage+Layer#StorageLayer-ConfiguringtheBitstreamStore)

**Comment by alawvt** [comment]
In dspace.cfg in vtechworks prod on 5:
```
##### File Storage ######

# Asset (bitstream) store number 0 (zero)
assetstore.dir = /dspace/assetstore

# Specify extra asset stores like this, counting from 1 upwards:
assetstore.dir.1 = /dspace/assetstore1
# assetstore.dir.2 = /third/assetstore

# Specify the number of the store to use for new bitstreams with this property
# The default is 0 (zero) which corresponds to the 'assetstore.dir' above
assetstore.incoming = 0
```

**Comment by alawvt** [comment]
Currently, assetstore for LDE and prod are `assetstore` and pprd and dev are `assetstore1`.

**Comment by alawvt** [comment]
[Add a variable in site_secrets.yml for assetstore number to overwrite in local.cfg](https://code.vt.edu/it-services/vtlibans_dspace/issues/118) adds the variable, assetstore_dir to site_secrets.yml.

**Comment by alawvt** [comment]
Note that DSpace 5 uses the variable, `assetstore.incoming` to determine which assetstore is used. In DSpace 6, this variable has been moved to `dspace/config/spring/api.bitstore.xml`. However, in this file, it is assigned the value of `assetstore.dir` in `dspace.cfg`, which we overwrite in `local.cfg`.

**Comment by alawvt** [comment]
Resolved with PR #604.

This will need to be tested on dev or pprd to make sure that it calls assetstore1 properly. Continued in #605.

**Comment by alawvt** [comment]
I think we need to change `config/spring/api/bitstore.xml` to 
```
<bean name="org.dspace.storage.bitstore.BitstreamStorageService" class="org.dspace.storage.bitstore.BitstreamStorageServiceImpl">
        <property name="incoming" value="{{ assetstore_incoming }}"/>
        <property name="stores">
            <map>
		    <entry key="0" value-ref="localStore"/>
                    <entry key="1" value-ref="localStore1"/>
            </map>
        </property>
    </bean>

    <bean name="localStore" class="org.dspace.storage.bitstore.DSBitStoreService" scope="singleton">
	    <property name="baseDir" value="${dspace.dir}/assetstore"/>
    </bean>
    <bean name="localStore1" class="org.dspace.storage.bitstore.DSBitStoreService" scope="singleton">
	    <property name="baseDir" value="${dspace.dir}/assetstore1"/>
    </bean>
```
and remove from `local.cfg`
```
# assetstore.dir, look at DSPACE/config/spring/api/bitstore.xml for more options
# default is ${dspace.dir}/assetstore, uncomment and modify if you need to use a different path
#assetstore.dir = ${dspace.dir}/assetstore
assetstore.dir = ${dspace.dir}/{{ assetstore_dir }}
```
and add the corresponding change to vtlibans.

**Comment by alawvt** [comment]
It doesn't seem possible to add the Ansible variable to `config/spring/api/bitstore.xml` because it is an xml file and the braces aren't allowed. Therefore I have hardcoded "incoming" to 0.
```
<bean name="org.dspace.storage.bitstore.BitstreamStorageService" class="org.dspace.storage.bitstore.BitstreamStorageServiceImpl">
        <property name="incoming" value="0"/>
        <property name="stores">
            <map>
		    <entry key="0" value-ref="localStore"/>
                    <entry key="1" value-ref="localStore1"/>
            </map>
        </property>
    </bean>

    <bean name="localStore" class="org.dspace.storage.bitstore.DSBitStoreService" scope="singleton">
	    <property name="baseDir" value="${assetstore.dir}"/>
    </bean>
    <bean name="localStore1" class="org.dspace.storage.bitstore.DSBitStoreService" scope="singleton">
	    <property name="baseDir" value="${assetstore.dir}1"/>
```
We will have to overwrite `<property name="incoming" value="0"/>` in vtlibans.

I removed assetstore from `example_site_secrets.yml`.

**Comment by alawvt** [comment]
I have added changes in branch configure_bitstream_xml, with PR #622.

**Comment by keithgee** [comment]
There's a new branch in the ansible project, git push configure_bitstore_settings, that works with the configure_bitstream_xml branch in GitHub (which I have modified slightly).

**Comment by keithgee** [comment]
Forgot to push the latest vtlibans_dspace changes. They'll be up shortly.

Edit: they're up.

**Comment by keithgee** [comment]
Code has been tested and merged.
**Closing
