### ISSUE TITLE
SWORD and SWORDv2 Bad URLs

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#606]
When I try `http://192.168.60.4/swordv2/servicedocument` in the browser, I get the error,
```
<sword:error xmlns:sword="http://purl.org/net/sword/terms/" href="http://www.dspace.org/ns/sword/2.0/errors/BadUrl">
<atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title>
<atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2019-07-19T13:56:48Z</atom:updated>
<atom:generator xmlns:atom="http://www.w3.org/2005/Atom" uri="http://www.dspace.org/ns/sword/2.0/" version="2.0">vtechworks@vt.edu</atom:generator>
<sword:treatment>Processing failed</sword:treatment>
<atom:summary xmlns:atom="http://www.w3.org/2005/Atom">
Unable to recognise URL as a valid service document: http://localhost:8080/swordv2/servicedocument
</atom:summary>
<sword:verboseDescription>
org.swordapp.server.SwordError: Unable to recognise URL as a valid service document: http://localhost:8080/swordv2/servicedocument at org.dspace.sword2.SwordUrlManager.extractDSpaceObject(SwordUrlManager.java:323) at 
```
I am wondering if this is due to the nginx config, since it is adding the port 8080 to the URL.

I am using the branch `organize_local_cfg`.

There is a corresponding issue, https://code.vt.edu/it-services/vtlibans_dspace/issues/119, in the vtlibans project.

I get a very similar error for SWORD.

**Comment by keithgee** [comment]
@alawvt, as per your diagnosis the problem was resolved by adjusting the nginx configuration.

A change was made to our separate ansible project.
`proxy_set_header Host $host;`
was added to the nginx configuration to pass the original hostname along through nginx to Tomcat.

**Comment by keithgee** [comment]
I've merged the code in the other project and closed the associated issue; I'll close this issue as well.

*** Closing

**Comment by alawvt** [comment]
@keithgee, thank you so much for figuring out this issue.
