### ISSUE TITLE
Check that error message has been customized to hide Java stacktrace.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#611]
Check that the Java stacktrace is hidden on the error page.

xmlui/src/main/webapp/exception2dri.xslt # used to customize error page, e1039be. dspace-xmlui/src/main/webapp/exception2dri.xslt does exist in DSpace 6. 

xmlui/src/main/webapp/exception2html.xslt # used to customize error page, e1039be. dspace-xmlui/src/main/webapp/exception2html.xslt does exist in DSpace 6.

These should hide the Java stacktrace when an error is produced. 

@keithgee, do you have any ideas how to test this consistently. If I use a bad URL, I just get a 404 error.

**Comment by keithgee** [comment]
This customization was left out on purpose; we had agreed that it would be helpful during testing to have the full error message quickly available. We'd also discussed whether we should add this customization back at all; the original motivation was during work to add Single Sign On to VTechWorks; that project was ultimately cancelled.

@alawvt, do you think this should be added back in? On a separate question, do you think that now is the time to add it? We still have some significant testing to do.

A quick way to test this is on your LDE with a testing database loaded in, but without the copies of the files in the asset store. Just click on a file in an (already submitted) item like you're going to download it. You should get the error.

**Comment by keithgee** [comment]
I've marked this with "wont fix" for now - though that's subject to change.

**Comment by alawvt** [comment]
@keithgee, I had forgotten about leaving this customization off during testing. I agree that it would be helpful for testing. Do we want to re-enable it once we're through testing? I recall that ITS wanted to hide the stacktrace for security.

**Comment by keithgee** [comment]
If it's a security issue, perhaps we should include it. I think a good time to put it back in (and hide the stack trace) might be just before the pre-prod installation.

**Comment by alawvt** [comment]
This was required for Shibboleth integration, which we are no longer implementing.
