### ISSUE TITLE
Investigate change in Handles for item-level versioning

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#615]
The default strategy to create new handles for versioned Items has changed. If you have Item Level Versioning enabled and you have versioned Items in your DSpace installation, you may want to change the configuration to continue using the mechanism to create handles as it was in DSpace 4 and 5. You can find more information here: [Item Level Versioning#IdentifierServiceOverride](https://wiki.duraspace.org/display/DSDOC6x/Item+Level+Versioning#ItemLevelVersioning-IdentifierServiceOverride).

**Comment by alawvt** [comment]
In DSpace 4 and 5, the most recent version always has the Handle initially issued for the item, e.g., 10919/12345. Older versions have `handle.versionnumber`, e.g. oldest=10919/12345.1, next oldest=10919/12345.2, ... newest=10919/12345.

In DSpace 6, versioned DOIs are possible. Later versions will have the same DOI with `.versionnumber` added, e.g DOI.1, DOI.2. This only occurss if DOIs are enabled and DataCite is used. To match the numbering of versioned DOIs, the default method for numbering handles has been reversed. The first version will have the original Handle. Succeeding versions will have `handle.version number`, e.g., oldest=10919/12345, next oldest=12345.2, etc., newest=12345.3.

We have the option of using either the new version Handle numbering system or using the system in VTechWorks 5. If we do want to use the new versioning numbering system, we could investigate if reassigning handles for earlier items with versions is possible or desirable. My sense is that we should go with the new handle numbering system. As long as we are making all versions of an item visible, I think the benefit of being able to cite a specific version outweighs the convenience of a constant Handle. @pyc1, what do you think?

**Comment by gailmmac** [comment]
Anne, I'll take your good advice.

Best, Gail

Gail McMillan
Director, Scholarly Communication <http://scholar.lib.vt.edu>
Professor, University Libraries
Virginia Tech
orcid.org/0000-0001-8817-3819

**Comment by alawvt** [comment]
I created #626 because we need to enable item-level versioning. I enabled that aspect in `dspace/config/xmlui.xconf` and built it in my LDE. 

Existing item http://192.168.60.4/handle/10919/50543 appeared with the list of previous versions 10919/50543.3, 10919/50543.2, and 10919/50543.1, as expected.

I created a version of another existing item, 10919/86637, and it was assigned Handle 10919/86637.2. That new version has metadata 

dc.identifier.uri=http://hdl.handle.net/10919/86637.2

as expected with the new versioning numbering system for handles.

Then I created another version of 10919/50543 which was assigned Handle 10919/50543.5.
That new version has metadata

dc.identifier.uri=http://hdl.handle.net/10919/50543.5

Giving the new version a decimal place larger the existing versions seems like a reasonable system, as shown in the screenshot,
<img width="1296" alt="ItemVersionDSpace6" src="https://user-images.githubusercontent.com/13037168/63382295-6761f980-c368-11e9-967a-954f672ee5ff.png">

**Comment by alawvt** [comment]
We have decided to go with the new default version Handle numbering system in DSpace 6 and have updated {Versioning in VTechWorks wiki page](https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/version).

**Comment by kdweeks** [comment]
This versioning system seems to sort with the latest version first!  That's
pretty sweet!

Kimberli Weeks
kdweeks@vt.edu
w. (540) 231-2674 c. 540-835-9136
Technical Director,
Scholarly Communications
University Libraries, Virginia Tech
http://scholar.lib.vt.edu
