### ISSUE TITLE
Error in video submission form

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#630]
In both DSpace 5 and 6, a video submission has errors in the metadata. The file upload seems ok. Specifically, I created an item of type, Video recording. That brought up a second page of the submission form with video-specific metadata. I added  "interviewee: Henry Kissenger." 

The Review Submission step listed
```
Interviewee(s): kissinger, Henry
Interviewee(s): kissinger, Henry
Interviewee(s): kissinger, Henry
Interviewer(s): kissinger, Henry
Interviewer(s): kissinger, Henry
Interviewer(s): kissinger, Henry
Contributor - Other: kissinger, Henry
Contributor - Other: kissinger, Henry
Contributor - Other: kissinger, Henry
```
Yikes.

When I clicked on "Correct one of these item" it takes me back to the 2nd page of the submission form where "kissinger, Henry" is listed 3 times for Interviewee, 3 times for Interviewer, and 3 times for Contributor - Other.

I didn't change anything and went ahead to the Review Submission step where it now listed "kissinger, Henry" 9 times for Interviewee, 9 times for Interviewer, and 9 times for Contributor - Other.

Oy.

So just for amusement, I clicked "Correct one of these" and sure enough the name was now listed 9 times for each field in the 2nd page of the submission form. 

Again, I didn't click anything there, just proceed to the Review Submission step where the name was listed 27 times for each field.

The final submission lists dc.contributor=kissinger, Henry 27 times.

??!!

**Comment by pyc1** [comment]
Known issue, see backlog line 1711 and 1703.  One alternative is not to allow users to upload videos, for a variety of reasons, and instead have them email us.

**Comment by alawvt** [comment]
Thanks, @pyc1. I believ the problem is that we can't map more than one form field to the same metadata field. In this case, Interviewer, Interviewee, and others are all mapped to dc.contributor. I think we can rework multiple video submission form issues into one issue.

**Comment by alawvt** [comment]
Continues Issue #495.

**Comment by alawvt** [comment]
Continued in #654.
