### ISSUE TITLE
ERROR org.apache.pdfbox.filter.FlateFilter @ FlateFilter: stop reading corrupt stream due to a DataFormatException

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#633]
Noted in logs 

`ERROR org.apache.pdfbox.filter.FlateFilter @ FlateFilter: stop reading corrupt stream due to a DataFormatException` 

in /dspace/log/dspace.log.2019-09-04.

**Comment by maddelar** [comment]
how did you guys fix this error?
