### ISSUE TITLE
Revise content type list for submission form

### ISSUE THREAD

**Issue by pyc1** [VTUL/vtechworks#639]
Revised content type list for the web submission form:

Article
Article - Refereed
Audio
Book
Book chapter
Conference proceeding
Dissertation
Image
Learning object
Master's project
Periodical
Poster
Presentation
Report
Thesis
Video
Other

Also note that the caption help text will need editing as well.

**Comment by alawvt** [comment]
Thanks, @pyc1, for the list. 

The current instructions are, "Select the type(s) of content you are depositing. To select more than one value in the list, you may have to hold down the "CTRL" or "Shift" or "COMMAND" key. Examples: Article, Learning Object, Video Recording and Presentation."

Instead we will show, "Select the type(s) of content you are depositing. To select more than one value in the list, you may have to hold down the "CTRL" or "Shift" or "COMMAND" key. Examples: Article, Learning object, Video, and Presentation."

Make content type a required field.

**Comment by alawvt** [comment]
Update the list of item types in `dspace/config/input-forms.xml` `<value-pairs value-pairs-name="common_types" dc-term="type">` as listed in https://docs.google.com/spreadsheets/d/1-Zrt2iiMWRpFpwYIPmfcfmrISBHShbfvdwrLPtrknr4/edit?usp=sharing "value-pairs" tab.

Make content type required for all forms.

Update the instructions as noted above.

**Comment by alawvt** [comment]
Resolved with PR #658.

**Comment by alawvt** [comment]
@pyc1, @kdweeks has implemented your content type list, as listed above, https://github.com/VTUL/vtechworks/issues/639#issue-494753668. But you mentioned the possibility of removing Video and Audio. Do you want them in the list? If not, what do you want for the instructions, currently, 
> Select the type(s) of content you are depositing. To select more than one value in the list, you may have to hold down the "CTRL" or "Shift" or "COMMAND" key. Examples: Article, Learning Object, Video Recording and Presentation.

**Comment by pyc1** [comment]
What do others think?  Audio may not be much of an issue, but we have an extensive process developed for video.  Formats and file sizes can cause problems.  My thought was to have users contact us to have those content types uploaded.  So the message would be:

"Select the type(s) of content you are depositing. To select more than one value in the list, you may have to hold down the "CTRL" or "Shift" or "COMMAND" key. Examples: Article, Learning object, and Presentation."  NOTE: To submit audio and video files, please contact vtechworks@vt.edu."

**Comment by alawvt** [comment]
I think those instructions would be good for video. I could go either way on audio. @keithgee, have we been doing anything special with audio? We can't make a thumbnail of them and they don't play in DSpace, as far as I know. Maybe we should include them in the list and just leave off video.

**Comment by pyc1** [comment]
OK, we discussed this at standup today and decided to leave Audio and Video as content types, in part due to the fact that faculty can upload these types from Elements and we didn't want a process that diverged from that too much, and because there are very few video uploads anyway.  We will have to do the processing after submission.  So the instructions should be:

"Select the type(s) of content you are depositing. To select more than one value in the list, you may have to hold down the "CTRL" or "Shift" or "COMMAND" key. Examples: Article, Learning object, Video, and Presentation."

**Comment by alawvt** [comment]
I added commit 67443e70e833a657aa07d060f0eab2882994a860 to make dc.type required for the default submission form (not just the OMALS form) and to update the dc.type submission instructions to Video from Video recording.

**Comment by alawvt** [comment]
resolved
