### ISSUE TITLE
"dspacedevvm.local.vt.edu.properties" is missing in "vt_5_x_dev" branch

### ISSUE THREAD

**Issue by AmberPoo1** [VTUL/vtechworks#64]
Hi @keithgee, @alawvt, @amandafrench , I found "dspacedevvm.local.vt.edu.properties" is missing in "vt_5_x_dev" branch now (which is supposed to be in root folder), which may cause the dspace build failed.

**Comment by keithgee** [comment]
@amberpoo1,thanks. right now we're keeping that file in the vtlibans_dspace project on git.it.vt.edu. You have to copy it manually from that project (it's in the templates folder) over to the dspace source code.

This may have been done because of passwords that are stored in the file.

**Comment by AmberPoo1** [comment]
@keithgee, thanks
