### ISSUE TITLE
Browse follow-up searches not working properly

### ISSUE THREAD

**Issue by pyc1** [VTUL/vtechworks#640]
Deborah Simpkins' group is doing repeated author searches from our author browse page, and sometimes a second search retrieves the "Browsing by Issue Date" page.  For example, if you go to https://vtechworks.lib.vt.edu/browse?type=author and enter a search, everything works fine.  But if you enter a new name into the search box from this results page, you get the issue date page instead of author browse results.  

For example, go to https://vtechworks.lib.vt.edu/browse?type=author and enter "brown, j".  You get the proper browse result.  But go back to the search box and enter "white, r" and the error occurs.  Perhaps the first search is not being cleared properly?

**Comment by keithgee** [comment]
I can duplicate this issue in VTechWorks, as well as on demo.dspace.org.

**Comment by pyc1** [comment]
Thanks Keith.  Should we enter an issue on the DSpace project?

**Comment by pyc1** [comment]
Deborah sent an update that the same thing happens for the subject browse, and I confirmed.  I also confirmed this happens in a title browse.  So author, title, and subject browses fail upon a follow-up search.  Issue date also fails on follow-up search, but stays on the same results page.

**Comment by keithgee** [comment]
I'm wondering if this item in the DSpace Jira might be the same issue. There's a potential fix:
https://jira.duraspace.org/browse/DS-3996 with PR, https://github.com/DSpace/DSpace/pull/2191/files.

**Comment by alawvt** [comment]
@pyc1, thank you very much for reporting this issue. @keithgee, thank you for discovering this issue and pull request in the DSpace project. This does seem like the same issue. If you would like to test this PR, that would be great. Otherwise, I will test it when I return.

**Comment by alawvt** [comment]
Resolved with PR #645 and branch, DS-3996_PR_2191_STARTS_WITH.

**Comment by alawvt** [comment]
Will be deployed as a[ hot fix](https://github.com/VTUL/vtechworks/wiki/08.-Fixing-urgent-problems-on-production-(hotfixes)) in #646.

**Comment by alawvt** [comment]
Completed.
