### ISSUE TITLE
Editing abstract not working properly

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#641]
When editing an abstract to replace a bad character, changes are not displaying correctly. When you hit "return" or "update" and go back to the item record, the abstract looks the same. But if you select "edit this item" and return to the editing screen, the revised abstract appears in the text box for dc.description.abstract. Then if you hit "return" or "update" a second time, the changes appear correctly. Here's an example abstract that was corrected:  [http://hdl.handle.net/10919/93743](http://hdl.handle.net/10919/93743). I'll try clearing my cache to see if this makes a difference, but I just thought someone should know.

**Comment by keithgee** [comment]
@cecross1 , I'm not able to reproduce this problem. Is it still happening this morning?

I edited an abstract, clicked update, and then clicked return. The edited abstract showed immediately.  It looks like the example item that you showed me is now displaying the corrected abstract, too.

Let me know if I should do something different to reproduce this, and if this is still happening or the system has somehow healed itself.

**Comment by pyc1** [comment]
I had this problem the other morning, but then it was fine the rest of the day, and the record updated fine.  I'm updating metadata fine today.  Maybe the system just gets slow at times?

**Comment by cecross1** [comment]
Still experiencing this today. As a test, I tried to edit the abstract for this item: [http://hdl.handle.net/10919/82185](http://hdl.handle.net/10919/82185). I edited the abstract, clicked update, then clicked return. After that, the original abstract shows up in the simple item record, but if you go to "edit this item" and go to the item metadata, the new abstract shows up under dc.description.abstract. 

ETA: I exited out of the item metadata screen without hitting update or return, but that pushed the changes through. Not sure why they aren't going through the first time, unless the system is just slow this morning, like @pyc1 says.

**Comment by keithgee** [comment]
I've just now stopped the process that was updating the statistics records; let me know if that helps.

It sounds more like there might be something happening with caching, though. When we switched to DSpace 6 we also switched to a new type of web server; I'm really not sure what it could be yet.

**Comment by keithgee** [comment]
@cecross1 @pyc1 It certainly does seem much faster when that batch statistics converter isn't running!

**Comment by pyc1** [comment]
It does seem a bit faster, thanks

**Comment by cecross1** [comment]
It does seem faster. I had to change the date on an item, and it went through the first time. Thanks, @keithgee!

**Comment by keithgee** [comment]
I'll close this issue for now because the problem may have been related to running the solr stats updater during the day. I haven't heard any more reports of the problem after I started running the process during the night only. Please reopen if the same issue occurs.

*** Closing

**Comment by alawvt** [comment]
@keithgee, thank you very much for handling this issue and adjusting the SOLR stats processor schedule.
