### ISSUE TITLE
Video playback broken

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#642]
The video playback is not working correctly in VTechWorks. Playback is slow to start, and in some cases the whole file must download before playback starts.

Initial investigations show that NGINX is sending a response header that indicates that byte range requests are not allowed. Byte range requests are necessary for the VTechWorks implementation of video to work properly.

This issue may need to be corrected in the vtlibans_dspace project.

**Comment by soumikgh** [comment]
I think setting `proxy_force_ranges on;` will fix this. Can I get a URL containing a video to test this?

Ref: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_force_ranges

**Comment by keithgee** [comment]
Thanks, @soumikgh. Here's one example with a video:

https://vtechworks.lib.vt.edu/handle/10919/70894

**Comment by alawvt** [comment]
I'm having more problems with mp4 files not downloading properly.  Webm works, but mp4 does not: https://vtechworks.lib.vt.edu/handle/10919/95301. Download and playing of mp4 works fine in Chrome and Safari. - @pyc1

**Comment by keithgee** [comment]
Playback looks to be working as I test this now. Perhaps its more of an issue when VTechWorks is experiencing heavy usage?

Also, I noticed that this item has the issue that Philip mentioned earlier where the mp4 files are much larger than the webm files. In this case the .mp4 file is nearly nine times as large. We can re-encode this particular file; it may have the lower quality that we're used to after the encoding.

**Comment by pyc1** [comment]
Webm works for this item, but if you download the mp4 in Firefox you get an error message.  Safari and Chrome seem to be OK.  This is affecting several of our recent video uploads.
<img width="387" alt="Screen Shot 2019-11-11 at 3 01 49 PM" src="https://user-images.githubusercontent.com/3442101/68617106-78686580-0494-11ea-9ebb-a978abf83c3b.png">

**Comment by pyc1** [comment]
For the file size issue, let's wait to see if Liz can export mov files and then I will process them again :(

**Comment by keithgee** [comment]
I just wanted to update this with a reminder that I've been asked to hold off on doing video work until ATS (the preservations and digital library group) can meet with VTechWorks team to find out how to make video processing easier and less problematic.
