### ISSUE TITLE
MP4 processing- combine and optimize commands

### ISSUE THREAD

**Issue by pyc1** [VTUL/vtechworks#651]
We are getting more video files submitted as mp4, sometimes a few at a time.  However, we currently have a collection of commands to perform different functions, many of which cannot be run in batch: https://code.vt.edu/digital-research-services/event_capture/.  

We may want to optimize the order in which these are run as well, since it may be best to derive a webm file before we compress an mp4 and derive thumbnail images.  In short, it would be nice to have one command for mp4 files that does all of these functions and also works in batch mode.

**Comment by alawvt** [comment]
Moved to https://code.vt.edu/digital-research-services/event_capture/issues/2.
