### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by pyc1** [VTUL/vtechworks#652]
Hi Kimberli, here are the changes for the homepage.

1.  Replace the first paragraph with:
VTechWorks provides global access to Virginia Tech scholarship.  VTechWorks includes journal articles, books, theses, dissertations, conference papers, slide presentations, technical reports, working papers, administrative documents, videos, images, and more by faculty, students, and staff.  Write [vtechworks@vt.edu](mailto:vtechworks@vt.edu) to get help adding your content to VTechWorks.  Read an [article about VTechWorks](https://vtnews.vt.edu/articles/2019/08/univlib-VTechWorks.html) or visit the Open@VT blog to learn about current VTechWorks activities.

2. Replace the 3rd paragraph about EFARs/Elements with:
Faculty can deposit items to VTechWorks from Elements (EFARs).  Visit the Provost's [Elements page](http://provost.vt.edu/faculty_affairs/efars.html) to learn more and to log in to Elements.

3.  Replace the 4th paragraph with: 
Want to see historical data on VTechWorks usage and content?  See our spreadsheet of [VTechWorks Stats](https://docs.google.com/spreadsheets/d/1mlezt-iN0rPwnWYJtop82s8_eM3J7-hjzbgjmw88GIc/edit#gid=1362694264) and a [map of global usage](https://guides.lib.vt.edu/vtw/usage).

The 2nd paragraph about VTechData can stay as-is.  Let me know if you have any questions.  Thanks- Philip

**Comment by alawvt** [comment]
dspace/config/news-xmlui.xml

**Comment by kdweeks** [comment]
@pyc1 @alawvt I believe I have the homepage updated correctly on my remote branch 'edit_homepage.'  I have requested that it be reviewed and merged. 

This issue references the pull request #656.

**Comment by kdweeks** [comment]
I fixed at typo "ELEments" in the home page.

**Comment by alawvt** [comment]
I added commit 8a56c3c7f7c282eb44800e44d526423857914ea8, to update the link for the 2019-2020 sheet of the statistics workbook.
