### ISSUE TITLE
Write REST query to get all the file names for all the items in a collection

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#653]
In preparation for determining which BTDs need OCRing, write a script to use [REST](https://vtechworks.lib.vt.edu/rest/) queries to obtain all the file names for all the items in a collection. See and add to the documentation in https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api, which describes DSpace 5. The program would probably use the queries:

- GET /collections/{collectionId}/items - Return all items of the specified collection.
- GET /items/{item id}/bitstreams - Return bitstreams of the specified item.

**Comment by kdweeks** [comment]
@alawvt Here are some very rough initial notes:

--------------------------------
REST API Web-Interface Report Tool:
https://vtechworks.lib.vt.edu/rest/static/reports/query.html

------
I have no idea how 90144 is associated with this item - but these 2 queries work to show the same item in json.
```
curl -H "Accept: application/json" https://vtechworks-dev.cloud.lib.vt.edu/rest/items/90144
```
```
curl -H "Accept: application/json" https://vtechworks-dev.cloud.lib.vt.edu/rest/items/6f501795-29e7-4974-8982-d9c9a4941846
```
------
Shows all collections and expand by one or more of the listed variables or use all
```
curl -H "Accept: application/json" http://vtechworks-dev.cloud.lib.vt.edu/rest/collections/{collectionID}[?expand={items,parentCommunityList,license,logo,all}]
```
-------

This works great for a search if you know a specific value of the metadata field, but you cannot use wildcards or with the "contain" value as in the REST query web-interface tool

```
curl -k -4 -H "accept: application/json" -H "Content-Type: application/json" -X POST "https://demo.dspace.org/rest/items/find-by-metadata-field" -d '{"key": "dc.title","value": "Test Webpage","language": "en_US"}'
```
Here is an example with vtechworks-dev:
```
curl -k -4 -H "accept: application/json" -H "Content-Type: application/json" -X POST "https://vtechworks-dev.cloud.lib.vt.edu/rest/items/find-by-metadata-field" -d '{"key": "dc.subject.lcc","value": "LD5655.V855 1993.S624"}'
```
-------------------
-------------------
Tests from existing documentation

--- works
```
curl -H "Accept: application/json" https://vtechworks-dev.cloud.lib.vt.edu/rest/items/90144
```
--- works
```
curl -H "Content-Type: application/json" -H "Accept: application/json" https://vtechworks-dev.cloud.lib.vt.edu/rest/test
```
--- doesn't work for me
```
curl -H "Content-Type: application/json" --data '{"email":"kdweeks@vt.edu", "password":"password_here"}' https://vtechworks-dev.cloud.lib.vt.edu/rest/login
```
--- can't test I could never log in so never got a token
```
curl -H "Content-Type: application/json" -H "Accept: application/json" -H "rest-dspace-token: f7396ab6-1b8f-482e-bb55-5fc8628ee5bb" https://vtechworks-dev.cloud.lib.vt.edu/rest/status
```
--- did not test - no token
```
curl -k -4 -H "rest-dspace-token: f7396ab6-1b8f-482e-bb55-5fc8628ee5bb"   -H "accept: application/json" -H "Content-Type: application/json" -X POST "https://vtechworks6-dev.cloud.lib.vt.edu/rest/communities" -d '{"name":"CREATED BY JSON 2",  "copyrightText":"CREATED BY JSON 2",  "introductoryText":"CREATED BY JSON 2",  "shortDescription":"CREATED BY JSON 2",  "shortDescription":"CREATED BY JSON 2",  "sidebarText":"CREATED BY JSON 2"}'
```
-------------------
-------------------

New Login in DSpace 6 - Note special characters in the email or password need to encoded in HTML - Nice tool to do this: https://www.w3schools.com/tags/ref_urlencode.asp
```
curl -v -X POST --data "email=kdweeks@vt.edu&password=encoded_password_here" https://vtechworks-dev.cloud.lib.vt.edu/rest/login
```

This returns a Session cookie idea - To test your status use the following with your session ID:
```
curl -v --cookie "JSESSIONID=5D0D05EE7046DE728D769080EBFE7E88" https://vtechworks-dev.cloud.lib.vt.edu/rest/status
```
-------------------
-------------------
Example Queries for General Collections

Shows the first 100 communities in VTechWorks (first 100 is shown by default)
```
curl -k -4 -H "Accept: application/json" https://vtechworks.lib.vt.edu/rest/communities?expand=all
```
Shows the first 100 collections in VTechWorks (specified with `offset` and `limit`)
```
curl -k -4 -H "Accept: application/json" https://vtechworks.lib.vt.edu/rest/collections?offset=0\&limit=100
```
Shows the second 100 collections in VTechWorks
```
curl -k -4 -H "Accept: application/json" https://vtechworks.lib.vt.edu/rest/collections?offset=100\&limit=100
```
NOTE: To use this in a browser you must encode special characters
https://vtechworks.lib.vt.edu/rest/collections?offset=0%5C%26limit=100

-------------------
-------------------
Example Queries for Specific Collections

Show the first 100 items (default) of a specific collection

Curl Template:
```
curl -k -4 -H "Accept: application/xml" http://localhost:8080/rest/collections/{collectionID}/items[?expand={metadata,parentCollection,parentcollectionList,parentCommunityList,bitstreams,all}]
 ```
XML Curl Example:
--- crashes in XML, pretty format
```
curl -k -4 -H "Accept: application/xml" https://vtechworks.lib.vt.edu/rest/collections/2aaadfa0-df04-421b-8779-c6944eb18db0/items?expand=all | xmllint --format
``` 
JSON Curl Example:
Works for JSON for 100 items at a time w/ no offsets sent to a local json file
```
curl -k -4 -H "Accept: application/json" https://vtechworks.lib.vt.edu/rest/collections/2aaadfa0-df04-421b-8779-c6944eb18db0/items?expand=all > ~/Documents/VTechWorks/VTW_REST/diss_curl.json
```
------ 
Use Handle to get UUID from browser

Template:
```
https://localhost:8080/rest/handle/{handle-prefix}/{handle-suffix} 
```
Example to obtain UUID for the ETD Dissertations collection
```
https://vtechworks.lib.vt.edu/rest/handle/10919/11041
```
------ 
Works in browser to get full records for the first 100 items in given collection

Template:
```
https://vtechworks.lib.vt.edu/rest/collections/{collectionID}/items?expand=all
```
Example of the dissertation collection
```
https://vtechworks.lib.vt.edu/rest/collections/2aaadfa0-df04-421b-8779-c6944eb18db0/items?expand=all
```
Variation of above, but only returns all the items basic info and bitstream info
```
https://vtechworks.lib.vt.edu/rest/collections/2aaadfa0-df04-421b-8779-c6944eb18db0/items?expand=bitstreams?offset=0%5C%26limit=1000
```
--------
Single Item Bitstream retrieval

This may be the best scripting model to flatten out the XML or JSON files and test for a .txt file. Use the handle of a single item and get bitstreams in XML format in the browser 

Example using the item's handle:
```
https://vtechworks.lib.vt.edu/rest/handle/10919/77910?expand=bitstreams
```
Example using the item's UUID:
```
https://vtechworks.lib.vt.edu/rest/items/47402755-b16c-4eed-b2b0-8f568e0ec45f?expand=bitstreams
```
-------------------
-------------------
All items in a collection with their UUID's can be downloaded via command line with the dspace metadata-export tool.
--------     
To export all metadata from DSpace via command line (this does not include bitstreams)
Template: 
`[dspace]/bin/dspace metadata-export -f name_of_file.csv -i 1023/24`

```
cd dspace/bin/  
./dspace metadata-export -a -f /tmp/dissertations.csv -i 10919/11041
10919/11041
```
from local terminal:
```
scp  -P 2030 kdweeks@rain.lib.vt.edu:/tmp/dissertations.csv  ~/Documents/VTechWorks/VTW_REST/
```

**Comment by alawvt** [comment]
Note that the URL for dev is https://vtechworks-dev.cloud.lib.vt.edu, not https://vtechworks6-dev.cloud.lib.vt.edu. (https://vtechworks6-dev.cloud.lib.vt.edu was a temporary URL when we were running both DSpace5 and DSpace6.)

It seems like the REST-API is able to retrieve an item using the old Item ID, not just the UUID. For example, `curl -H "Accept: application/json" https://vtechworks-dev.cloud.lib.vt.edu/rest/items/92235` retrieves a known item with that old ID. `curl -H "Accept: application/json" https://vtechworks-dev.cloud.lib.vt.edu/rest/items/db2d618d-5961-4a49-9d64-f84251f576fa
` retrieves the same item.

@kdweeks, good job so far. Please add these to the Wiki page as you feel more confident about them.

**Comment by kdweeks** [comment]
The script `exercise_rest.py` is deprecated for DSpace 6

In trying to update the script, I may I found exactly what we need to move forward with the BTD OCRing project. Perhaps this should be a different issue.
[https://github.com/MITLibraries/dspace-api-python-scripts](https://github.com/MITLibraries/dspace-api-python-scripts)

[exportSelectedRecordMetadataToCSV.py](https://github.com/MITLibraries/dspace-api-python-scripts/blob/master/exportSelectedRecordMetadataToCSV.py)
Based a CSV of item handles, extracts all metadata (except 'dc.description.provenance' values) from the selected items to a CSV file.

[getHandlesAndBitstreamsFromCollection.py](https://github.com/MITLibraries/dspace-api-python-scripts/blob/master/getHandlesAndBitstreamsFromCollection.py)
Based on user input, extracts all the handles and bitstreams associated with the items in the specified collection to a CSV file.

Updated the login information for DSpace 6 for LDE, VTechWorks Dev and PProd in the documentation.

Added new DSpac 6 information in the documentation here:  [https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api](https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api)

**Comment by alawvt** [comment]
completed, thanks @kdweeks. Continued in #679.
