### ISSUE TITLE
Fix submission form so conference metadata is not lost

### ISSUE THREAD

**Issue by pyc1** [VTUL/vtechworks#654]
When a user submits an item through the web interface and adds conference metadata, that information is lost.  Several library faculty have submitted presentations from conferences and I have to contact them to retrieve that information.

**Comment by pyc1** [comment]
Conference metadata should be in the field dc.relation.ispartof

**Comment by alawvt** [comment]
The error may be caused by the video submission field, "episode title," also being mapped to this field. My understanding is that only only one submission field can be mapped to a schema field. We will need to test this.

**Comment by pyc1** [comment]
Users uploading video is pretty problematic so I'd be in favor of eliminating video as a content type with a note to email us.

**Comment by alawvt** [comment]
Continues #630.

**Comment by alawvt** [comment]
Resolved by #672.
