### ISSUE TITLE
In the OMALS submission form, update list of concentrations

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#657]
In the [OMALS](https://vtechworks.lib.vt.edu/handle/10919/51287) submission form, update the list of concentrations in `dspace/config/input-forms.xml` `<value-pairs value-pairs-name="omals_disciplines"
			dc-term="thesis_degree_discipline">` as listed in https://docs.google.com/spreadsheets/d/1-Zrt2iiMWRpFpwYIPmfcfmrISBHShbfvdwrLPtrknr4/edit?usp=sharing "value-pairs" tab.
____________
I have a student trying to submit to VTechWorks and is stating that the Applied Nutrition and Physical Activity concentration is not available as a choice.  Can you confirm for me that all six concentrations are listed as options to choose when they submit:

- Applied Nutrition and Physical Activity
- Education
- Environmental Science  
- Food Safety and Biosecurity
- Leadership Studies
- Plant Science and Pest Management

 
Thanks!
Jennifer Jones

See earlier PR #122

**Comment by kdweeks** [comment]
@alawvt @pyc1 I have made the changes to the OMALS submission form.  I have attached a screenshot of the "Disciplines" and "Items Type" sections of the form.  Please review them and if approved, I will create a merge request.

<img width="968" alt="OMALS_Disciplines" src="https://user-images.githubusercontent.com/473202/69986255-0622f800-150b-11ea-9b49-b9626139558f.png">

<img width="968" alt="OMALS_Items1" src="https://user-images.githubusercontent.com/473202/69986340-23f05d00-150b-11ea-839e-a85eab4d2160.png">

<img width="968" alt="OMALS_Items2" src="https://user-images.githubusercontent.com/473202/69986348-2b176b00-150b-11ea-985f-fff0c1de32a8.png">

<img width="968" alt="OMALS_Items3" src="https://user-images.githubusercontent.com/473202/69986367-38345a00-150b-11ea-866b-775b8927df2c.png">

**Comment by alawvt** [comment]
@kdweeks, thank you for working on this. It would be better if you created the pull request with these screenshots now, so that we can review the commits, test, etc. more easily.

**Comment by kdweeks** [comment]
This issue is resolved by #658

**Comment by kdweeks** [comment]
I have updated the OMALS submission form to:
- Change the dc.type form field to be required.
- Change the dc.type value from "Learning Object" to "Learning object."
- Remove the discontinued values from the discipline field.
