### ISSUE TITLE
Request-a-copy error message "file too big"

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#668]
The file LaTeXsource files.zip (12.97Mb) in http://hdl.handle.net/10919/93253 is restricted to campus only. When Anita approves sending a copy with the request-a-copy, the response is the error message, "file too big," see attached, ![error](https://user-images.githubusercontent.com/13037168/70945193-a3f5e700-2022-11ea-9b3a-8788e5342fcd.png).

In comparison, the source file for the previous volume, http://hdl.handle.net/10919/84164, is 53.00Mb and she has been able to send that via the request-a-copy. She uploaded a smaller restricted test file to http://hdl.handle.net/10919/93253 and was able to send that via request-a-copy. I removed the space in the file name, so it is now LaTeXsourcefiles.zip. That had no effect on this problem.

Other possible testing ideas: create a new item with this file (on dev?) and try requesting it.

**Comment by alawvt** [comment]
I created a test item with this file, https://vtechworks-dev.cloud.lib.vt.edu/bitstream/handle/10919/94145/LaTeXsourcefiles.zip?sequence=1&isAllowed=n, and requested it from both my VT Gmail account and a Hotmail account . Both had the error, "552 5.3.4 Error: message file too big." 

I loaded the source file from Electromagnetics v1, https://vtechworks-dev.cloud.lib.vt.edu/bitstream/handle/10919/94145/LaTeX%20sourcefiles_v1.zip?sequence=4&isAllowed=n, and requested it from this test item. It also gave the same error. 

Then I requested that file from the original item, https://vtechworks.lib.vt.edu/bitstream/handle/10919/84164/LaTeX%20sourcefiles.zip?sequence=16&isAllowed=y. It also gave the same error.

**Comment by alawvt** [comment]
It sounds like this is an error coming from the recepient's email server, for example, https://stackoverflow.com/questions/9396624/error-message-file-too-big-is-the-limit-on-outgoing-or-receiving-end. @soumikgh, do you know of any limit with the mail servers that would be causing this?

**Comment by alawvt** [comment]
I uploaded and requested a 12 Mb pdf, https://vtechworks-dev.cloud.lib.vt.edu/bitstream/handle/10919/94145/LD5655.V856_1942.S842.pdf?sequence=5&isAllowed=n, and got the same error.

I uploaded and requested a 5 Mb pdf, https://vtechworks-dev.cloud.lib.vt.edu/bitstream/handle/10919/94145/LD5655.V856_1949.T943.pdf?sequence=6&isAllowed=n, and got the same error.

I uploaded and requested a 3.9 Mb pdf, https://vtechworks-dev.cloud.lib.vt.edu/bitstream/handle/10919/94145/Freudenberger_Catanzaro_KC_D_2019.pdf?sequence=8&isAllowed=n, and got the same error.

I uploaded and requested the 2.65 Mb pdf, https://vtechworks-dev.cloud.lib.vt.edu/bitstream/handle/10919/94145/ElectromagneticsVol2.pdf?sequence=7&isAllowed=n and was able to send and receive this file. We were also able to send and receive this file in the original item, https://vtechworks.lib.vt.edu/handle/10919/93253.

I uploaded and requested the 2.0 Mb pdf, https://vtechworks-dev.cloud.lib.vt.edu/bitstream/handle/10919/94145/Qiao_Z_D_2018.pdf?sequence=9&isAllowed=n and was able to send and receive this file. 

So it seems like the cut off for this error is somewhere between 2.65 and 3.9 Mb.

**Comment by soumikgh** [comment]
Can you show me how to replicate that? I'm pretty sure we don't have restrictions when it comes to outgoing email, but I'm going to poke around and double-check.

**Comment by alawvt** [comment]
Replicating this involves submitting an item and then restricting the file to the Administrators group. I could show you how to edit an item to add a file and/or restrict the file to a particular group. It would be easier in person.

**Comment by soumikgh** [comment]
The Postfix `message_size_limit` variable had to be adjusted in `/etc/postfix/main.cf`. I have set it to 100 MB on dev and prod.

```
--- main.cf.back	2019-12-18 10:37:34.149967532 -0500
+++ main.cf	2019-12-18 10:37:54.665088309 -0500
@@ -43,3 +43,5 @@
 recipient_delimiter = +
 inet_interfaces = all
 inet_protocols = all
+# Set on 20191218
+message_size_limit = 102400000

```

**Comment by alawvt** [comment]
@soumikgh, thank you very much for resolving this issue. 

A message up to 100 MB can now be sent via request-a-copy. Note that if **all** restricted files are requested, the mail server will attempt to send them all in one message, so the total of all restricted files must be under 100 MB. (I added this note to the VTechWorks wiki.)

**Comment by alawvt** [comment]
A user reported getting the "too big file" error message for a file that is 54 MB. The item is http://hdl.handle.net/10919/84164 and it was requested Thu, Dec 19, 2019 at 12:18 AM. The recipient had a non-VT Gmail account. We are able to send the same file to a VT Gmail account. So we may still see these error messages due to limitations that we can't control on the recipients email account.
