### ISSUE TITLE
Test Zucchini changes on vtechworks

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#678]
@soumikgh, please deploy the commit, https://github.com/VTUL/vtechworks/commit/2ccb5bacda06236a230607500a19df5743735028, on branch [vt_6_dev_deploy](https://github.com/VTUL/vtechworks/commits/vt_6_x_dev_deploy) to vtechworks-dev.

**Comment by alawvt** [comment]
zucchini changes were deployed to dev on 2020-01-02.

**Comment by alawvt** [comment]
zucchini changes on LDE and vtechworks-dev have passed. 

zucchini changes were deployed to pprd on 2020-01-07.

**Comment by alawvt** [comment]
@soumikgh will deploy the latest commit, ec0e208, on branch, https://github.com/VTUL/vtechworks/commits/vt_6_x_prod_deploy, to vtechworks.lib.vt.edu on Monday January 13, at approximately 7 am.

**Comment by kdweeks** [comment]
Completed testing on pprd for the vt_6_x_pprd_deploy instance at:
https://vtechworks-pprd.cloud.lib.vt.edu/.  

Test results are available here:
https://docs.google.com/spreadsheets/d/1RbTB46ssFdKvc7C1jEP5vTn9vG9jOcwy7AcNNQdyi5k/edit#gid=1712830785  and  https://docs.google.com/spreadsheets/d/1RbTB46ssFdKvc7C1jEP5vTn9vG9jOcwy7AcNNQdyi5k/edit#gid=1459195818

**Comment by kdweeks** [comment]
Created a test plan for Zhcchihi changes that is available here:
https://docs.google.com/spreadsheets/d/1RbTB46ssFdKvc7C1jEP5vTn9vG9jOcwy7AcNNQdyi5k/edit#gid=158771184

**Comment by alawvt** [comment]
Zucchini has been deployed to prod and has passed the basic functionality tests.

**Comment by kdweeks** [comment]
Completed zucchini testing on VTechWorks production server.
