### ISSUE TITLE
Use MIT REST libraries to get files for collections

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#679]
Continues #653.

In preparation for determining which BTDs need OCRing, use the [MIT REST libraries](https://github.com/MITLibraries/dspace-api-python-scripts) to obtain all the file names for all the items in a collection. See and add to the documentation in https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api. The program would probably use the queries:

    GET /collections/{collectionId}/items - Return all items of the specified collection.
    GET /items/{item id}/bitstreams - Return bitstreams of the specified item.

**Comment by kdweeks** [comment]
Cloned MIT Libraries DSpace API files from: https://github.com/MITLibraries/dspace-api-python-scripts.  Make scripts executable `chmod a+x *.py`  

Configured `secrets.py` file with the server and personal login information.

**Comment by kdweeks** [comment]
After much troubleshooting, successfully ran the `getHandlesAndBitstreamsFromCollection.py` script (uses only GET commands to gather metadata and bitstream information from VTechWorks).  This script failed after being disconnected from the VTechWorks server (This script ran ~2 hrs.).

Revised the script to gather only BTD's with BUNDLE.bitstreams=TEXT files.  I ran this (~3 hrs to run).  The results were 5511 BTD files. 

Revised the script to gather only BTD's without BUNDLE.bitstreams=TEXT files.  I ran this (~3 hrs to run).  The results were 5511 BTD files.

After researching the results of both scripts, I found that ALL of the BTDs in the VTechworks Dissertation collection have BUNDLE.bitstreams=TEXT files.  This voids the programmatic, base requirements of this project.

**Comment by kdweeks** [comment]
Revised the `getHandlesAndBitstreamsFromCollection.py` to also get bitstream file size information to discover if the BUNDLE.bitstreams=TEXT file sizes may be zero, or small.   This script also ran and returned the file sizes in bytes successfully.

**Comment by kdweeks** [comment]
Created a local repository, at https://code.vt.edu/digital-research-services/dspace-api-python-scripts,  and cloned the MIT repository https://github.com/MITLibraries/dspace-api-python-scripts.  I did not add any of the new files that I modified for our local VTechWorks repository because of the surprise that all BTDs in the VTechWorks production server somehow contain BUNDLE.bitstreams=TEXT files.  I was unable to test the script modifications that seemed to work.

**Comment by kdweeks** [comment]
Mapped several known OCR'd BTDs, known non-OCR'd BTDs, and some ETD's in a smaller test collection at:  https://vtechworks.lib.vt.edu/handle/10919/91907.  This should help us make script changes and tests much faster than using the larger [Dissertation](https://vtechworks.lib.vt.edu/handle/10919/11041) or [Theses](https://vtechworks.lib.vt.edu/handle/10919/9291) collections.

Attached is the results from running `getBtdsHandlesBitstreamsSize.py` on the [Library Test](https://vtechworks.lib.vt.edu/handle/10919/91907) collection.


[10919-91907handlesAndBitstreams.xlsx](https://github.com/VTUL/vtechworks/files/4257363/10919-91907handlesAndBitstreams.xlsx)

**Comment by kdweeks** [comment]
Continue in local repository in issue [Use MIT REST libraries to get files for collections](https://code.vt.edu/digital-research-services/dspace-api-python-scripts/issues/1).
