### ISSUE TITLE
Publisher information is concatenated in search results

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#68]
Hi all, I apologize if this has been identified earlier, but I've noticed that the publisher names for several items in the collection I'm working with (http://vtechworks.lib.vt.edu/handle/10919/50816) are incorrectly strung together in the search results (see screenshot below). The publisher names are correctly separated and parsed in the actual metadata record - the issue is the display of those names in the search results. Thanks so much.

![publisher_metadata](https://cloud.githubusercontent.com/assets/5408616/10681909/af846f64-78fc-11e5-8c4e-2005fe1df5cb.jpg)

**Comment by alawvt** [comment]
@AmberPoo1, did the HTML display change do anything to the publisher field in list view?

**Comment by amandafrench** [comment]
This is probably due to the lack of a space or '''&nbsp;''' in some file: am adding this to the current sprint, @AmberPoo1, since it should be a very fast fix. Will add to product backlog too.

**Comment by AmberPoo1** [comment]
@alawvt , @amandafrench ,yes, I think so. Adding something like ";" between multiple publishers will solve this problem.

**Comment by AmberPoo1** [comment]
@alawvt , display of multiple publishers still has problem. Redundant comma in browse view. Mulple publishers are is concatenated in search view, I reopened this issue and will update the pull request later.

Browse view:
![screen shot 2015-12-22 at 1 18 15 pm](https://cloud.githubusercontent.com/assets/13734326/11962530/7de8a88a-a8ae-11e5-8748-b499d750c40a.png)


Search view:
![screen shot 2015-12-22 at 1 17 18 pm](https://cloud.githubusercontent.com/assets/13734326/11962519/659392ae-a8ae-11e5-94cf-145c0fd52e20.png)

**Comment by alawvt** [comment]
@AmberPoo1, thank you for testing this. The items referenced in the original comment, http://vtechworks.lib.vt.edu/handle/10919/50816, all look good. Let's wait a day or so and see if indexing helps the display of this new item you created.
