### ISSUE TITLE
Create a test plan for Zucchini sprint

### ISSUE THREAD

**Issue by kdweeks** [VTUL/vtechworks#681]
Broad instructions for testing - 
[https://github.com/VTUL/vtechworks/wiki/06.-Testing](https://github.com/VTUL/vtechworks/wiki/06.-Testing)

Google Drive VTW Testing -
[https://drive.google.com/drive/folders/0B0VhWgQOPYz8UkowTjg0TkxLQXc](https://drive.google.com/drive/folders/0B0VhWgQOPYz8UkowTjg0TkxLQXc)

**Comment by kdweeks** [comment]
I created a test plan from the existing test plan and all the new commits here: 
https://docs.google.com/spreadsheets/d/1RbTB46ssFdKvc7C1jEP5vTn9vG9jOcwy7AcNNQdyi5k/edit#gid=1753423825

I tried to use vagrant to provision the `vt_6_x_dev_deploy`  branch.  The build failed b/c the `vt_6_x_dev` has not been merged into the `vt_6_x_dev_deploy`  branch.  Watch https://github.com/VTUL/vtechworks/issues/678.

**Comment by alawvt** [comment]
@kdweeks, it looks likes it has been merged in https://github.com/VTUL/vtechworks/commits/vt_6_x_dev_deploy. Did you check out that branch and pull?

**Comment by kdweeks** [comment]
@alawvt Maybe I did something wrong.  I'll double-check.

**Comment by kdweeks** [comment]
Completed LDE, DEV and PPROD test plans.

**Comment by alawvt** [comment]
Thank you, @kdweeks, nice job.
