### ISSUE TITLE
Metadata changes not saved during submission approval process

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#686]
The approver for collection CS5604 notes, "It appears that though I edit the metadata, and do save and exit, the edits are not retained.  This has been going on for several weeks, and just occurred again a few minutes ago, when I edited the Abstract and Notes fields for the submission." I gave up and approved the submission with the minor errors still present that I had tried to fix, since they were small matters, but hope that this bug can be corrected before I have to re-review other soon-to-be-pending submissions.

**Comment by alawvt** [comment]
Please see if you can recreate this issue, and document it.

**Comment by kdweeks** [comment]
I added myself to the following groups in the collection https://vtechworks.lib.vt.edu/handle/10919/19081:

COLLECTION_142_ADMIN
COLLECTION_142_SUBMIT
COLLECTION_142_WORKFLOW_STEP_2

to try to recreate the issue of not being able to save edits in the _Abstract_ and _Notes_ fields.

**Comment by kdweeks** [comment]
This item was rejected by Ed Fox and resubmitted by students.  I was able to edit this, changes were saved: https://vtechworks.lib.vt.edu/handle/10919/96310

This item was rejected by Ed Fox and resubmitted by students.  I was able to edit this, changes were saved: https://vtechworks.lib.vt.edu/handle/10919/96437

I thought a final test would be to submit a new item and try to edit it. Before starting, I added myself to all three workflow groups, but now, I'm not able to add that item to my task list.  Uggh!  @alawvt What's up with that? Help :)  Perhaps, Dr. Fox will try to make edits and we'll have an even more realistic test.  The items title is:
Test item for metadata edit in collection CS5604

**Comment by kdweeks** [comment]
I must have not properly saved adding myself the 3 workgroups.   @alawvt deleted the first attempted item I added and could not edit.

**Comment by kdweeks** [comment]
Testing from the submitted item, editing metadata stage:  Metadata saved in the editing stage.  Approved item.  Moved to the stage of editing item metadata after approval - edits were saved. Tried to delete item.  I was unauthorized to delete that item; yet it appears to be deleted.

**Comment by kdweeks** [comment]
I was able to able to edit the metadata in the submission phase, after the rejection phase, during the approval phase, and after the approval phase.  I was unable to recreate this issue.

<img width="851" alt="TestMetadataEdit1" src="https://user-images.githubusercontent.com/473202/73677584-9228db80-4684-11ea-8ec8-6e50b9867daa.png">
<img width="851" alt="TestMetadataEdit2" src="https://user-images.githubusercontent.com/473202/73677591-9654f900-4684-11ea-8317-787ffc18cd04.png">

**Comment by alawvt** [comment]
@kdweeks, thank you for working on this. This will be a baseline for any future reports of this behavior.
