### ISSUE TITLE
Branded_Preview bundle for 4/16 images?

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#691]
The 4/16 collection has items with the bundle, Branded_Preview, for example, 
https://vtechworks.lib.vt.edu/handle/10919/17609. The image is intermediate in size between the thumbnail and the original. @keithgee, do you have any memory of this [Branded Preview JPEG media-filter](https://wiki.lyrasis.org/display/DSDOC6x/Mediafilters+for+Transforming+DSpace+Content#MediafiltersforTransformingDSpaceContent-AvailableMediaFilters) or its use in VTechWorks? It is not currently enabled.

**Comment by keithgee** [comment]
I believe that this was enabled and used for the 4/16 collection, and then disabled immediately afterward.

**Comment by alawvt** [comment]
@keithgee, thank you for this information.

**Comment by kdweeks** [comment]
Yes, thanks @keithgee!  This is great to know.  I don't see why it should be enabled now.
