### ISSUE TITLE
Video playback not working on dev or pprd

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#693]
The video item, http://hdl.handle.net/10919/18426, plays correctly on production, including the close captioning. The same item on dev, https://vtechworks-dev.cloud.lib.vt.edu/handle/10919/18426, and pprd, https://vtechworks-pprd.cloud.lib.vt.edu/handle/10919/18426, gives the error, "no video with supported format and MIME type found."

**Comment by keithgee** [comment]
Just a note for whoever takes the 4Help ticket and looks into this:
It appears that none of the bitstream assets - videos, thumbnails, PDF files, etc are loading on the dev or pprd systems.

**Comment by alawvt** [comment]
Thanks, @keithgee, for looking at this. This would also explain #690.

**Comment by keithgee** [comment]
> This would also explain #690.

Oh, yeah. The thing about the thumbnails being regenerated could have been a complete red herring, and the entire assetstore just hasn't been online on dev or pprd this whole time!

**Comment by alawvt** [comment]
We haven't used dev and pprd much since installing 6. We've been very focused on content projects on prod.

**Comment by alawvt** [comment]
@soumikgh, thank you for fixing this by adding the correct symlink to the new location for assetstore.
