### ISSUE TITLE
Author names not saved in submission form

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#696]
A faculty member submitted two new items to the Advanced Research Computing collection, and reported that author names were not saved after being entered into the submission form. Links to the items are below (names were later added manually):

- <http://hdl.handle.net/10919/97511>
- <http://hdl.handle.net/10919/97510>

I created a test submission in preprod (http://hdl.handle.net/10919/94148), but I was unable to replicate the issue.

**Comment by alawvt** [comment]
@cecross1, thank you for handling, attempting to recreate, and documenting this issue.
