### ISSUE TITLE
13 items in ETD collection appear to be missing files

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#697]
The first 13 items in https://vtechworks.lib.vt.edu/handle/10919/5534/discover appear to be missing bitstreams.

No Thumbnail [100%x100]
VT ETD LaTex Template 
Lattimer, Alan (2016-10-17)
ok- .doc file

No Thumbnail [100%x100]
Title Page Template When Committee Member Disapproves ETD 
Unknown author (2016-10-17)
ok- .doc file

No Thumbnail [100%x100]
Ecology and Morphology of Early Animals: An Analysis of the Problematic Genus Sphenothallus from the Lower Cambrian Shuijingtuo and Niutitang Formations in South China 
Nakagaki, Michael Masao (Virginia Tech, 2009-08-19)
ok- .log file

No Thumbnail [100%x100]
Mapping and Characterization of Phytophthora sojae and Soybean Mosaic Virus Resistance in Soybean 
Tucker, Dominic Michael (Virginia Tech, 2009-04-27)
ok - known missing file

No Thumbnail [100%x100]
Developing and Testing a Combustor Simulator For Investigating High Pressure Turbine Aerodynamics and Heat Transfer 
Barringer, Michael David (Virginia Tech, 2006-07-20)
ok - known missing file

No Thumbnail [100%x100]
The influence of land use on the quality of seston in southern Appalachian stream ecosystems 
Wojculewski, Christy Ann (Virginia Tech, 2006-05-12)
ok - known missing file

No Thumbnail [100%x100]
Implementation of Third Order Plate Theory for use in Existing Finite Element Software 
Portier, Sarah (Virginia Tech, 2006-05-12)
ok - known missing file

No Thumbnail [100%x100]
Magnetic Induction for In-situ Healing of Polymeric Material 
Owen, Christopher Cooper (Virginia Tech, 2006-05-19)
ok - known missing file

No Thumbnail [100%x100]
Test of Light Speed Constancy With Light Age Using an Active Fiber-Based Mach-Zehnder Interferometer 
Dong, Bo (Virginia Tech, 2006-05-10)
ok - known missing file

No Thumbnail [100%x100]
Let's All Go to the Movies 
Ressler, Christopher Michael (Virginia Tech, 2006-05-10)
ok - known missing file

No Thumbnail [100%x100]
Hybrid Active Power Filter with Output Impedance Control 
Schmit, Andrew Paul (Virginia Tech, 2006-05-24)
ok - known missing file

No Thumbnail [100%x100]
Influence of Isolate, Cultivar, and Heat Stress on Virulence of Rhizoctonia zeae on Tall Fescue 
McCall, David Scott (Virginia Tech, 2006-05-11)
ok - known missing file

No Thumbnail [100%x100]
Durable Sandwich Structure Joining Technology for NASA's Ares V Launch Vehicle 
Lundgren, Eric Charles (Virginia Tech, 2010-02-05)
ok - known missing file

**Comment by alawvt** [comment]
It turns out 10 of 13 of these were ETDs with known missing files. The other 3 were items with file that don't generate thumbnails. It is interesting that sorted by relevance, the first 13 Discovery search results display 10 of the 22 ETDs with known missing files out of a collection of nearly 34,000.

**Comment by pyc1** [comment]
The DSpace default seems to place items without files at the top of a results list.  I just discovered this while adding PDFs to imported metadata.  The one item without a file got moved to the top.  Then when I added the file, the order changed again.  Useful for administrators, not so much for users.

**Comment by alawvt** [comment]
@pyc1, thank you for observation. I agree.
