### ISSUE TITLE
Request-a-copy file never received

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#698]
A patron requested the file, LaTeXsource files.zip (12.97Mb), in http://hdl.handle.net/10919/93253 via the Request-a-copy form. The e-person granted permission but the patron did not receive the file. They repeated the process without success. Today, I also use the form but did not receive the file in an email, as usual.

Since we are all working remotely, we might want to check IP related settings for email. See also issue #668 about the same file.

**Comment by alawvt** [comment]
Test 2: I anonymously requested the file and the e-person declined the request. I received the email notification that the request had been declined. So basic email functionality seems ok.

**Comment by soumikgh** [comment]
Can we test it like we did on #668? If you trigger the email and note the time down, I can look in logs for that time and see if it's Postfix or the MTA which might be causing it.

**Comment by alawvt** [comment]
@soumikgh, thank you for reviewing this issue. I have created a test item, http://hdl.handle.net/10919/97857, with the same file so I can both request and respond to the request.

At 13:27, I requested this file. As far as I can tell, these request emails have been working correctly.

At 13:28, I replied to this request which should send the file in an email to the recipient.

At 13:29, I received the reply with the file.

Hmm, I will try this again not logged into the VPN.

At 13:31, I requested this file.

At 13:32, I replied to this request which should send the file in an email to the recipient.

At 13:32, I received the reply with the file.

Hmm. I will ask the e-person of the original item to respond to another request and note the time, which I will report here.

**Comment by alawvt** [comment]
@soumikgh,

I requested the file from the original item, http://hdl.handle.net/10919/93253.  
At 13:50, the eperson replied to the request.  
I received the file.  

I requested all the files from the original item, http://hdl.handle.net/10919/93253.  
At 13:55, the eperson replied to the request.  
I did not receive the files.  

All the files are 5.352 + 5.747 + .391 + 12.97 + 8.19 + 5.562 = 38.2 MB. Perhaps this is past the limit for email. We didn't get the "file too big" error that we got in the previous issue.

**Comment by soumikgh** [comment]
@sindtd has kindly taken over this issue from me.

**Comment by alawvt** [comment]
![Request-a-copy-form](https://user-images.githubusercontent.com/13037168/87473943-49406000-c5f0-11ea-8637-dc9728c73e4b.png)
@soumikgh and @sindtd, thank you for working on this issue. I am going to close it with the assumption that the cause was a file size limitation of the email client. I will recommend that users use the "request a single file" rather than "request all files" option.
