### ISSUE TITLE
Metadata not saved in OMALS submission form

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#701]
A student attempted to submit an item to the Online Master of Agricultural and Life Sciences collection. They reported that when they entered author names, committee members, and keywords, the page refreshed and the metadata was deleted. I created a test submission on preprod, but was unable to replicate the issue.

A faculty member reported a similar issue earlier this spring: <https://github.com/VTUL/vtechworks/issues/696>

**Comment by alawvt** [comment]
It was human error and not a problem with the system. After adding the names, the user checked the boxes, which deletes them.
