### ISSUE TITLE
Decide if any collections should not be harvested by DCG

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#712]
Extends #710 
Decide if any collections should not be harvested by OCLC DCG for Discovery.

**Comment by gailmmac** [comment]
Why not harvest everything in VTechWorks?

**Comment by alawvt** [comment]
That's easy: we are unanimous on harvesting all collections.

**Comment by alawvt** [comment]
Consider creating a record blocking list to not harvest dc.type=abstract or dc.type=citation (perhaps for certain collections like SANREM).

**Comment by alawvt** [comment]
We have just learned that matching that DCG uses to prevent duplicate records from being harvested, treats the same item mapped to two collections as different records. 

One way to minimize duplicate records is to not harvest collections where everything is mapped. Candidates are:

- VTechWorks Administration community including All Faculty Deposits.
- VTTI ETDs
- Feiertag ETDs
- MDPI
- Biomed Central
- De Gruyter
- Hindawi
- Open Access Subvention Fund
- Strategic Growth and Destination Areas? - ~80 are only in one collection, so we'll need to harvest these.

@cecross1 or @pyc1, would you comment on these collections or list other collections where everything is mapped?

Another strategy would be to add an administrative field that notes the mapping of an item, but that would add quite a bit of extra work.

**Comment by cecross1** [comment]
@alawvt @pyc1 I agree with this list. Nothing else comes to mind at the moment.

**Comment by kdweeks** [comment]
@alawvt  The only thing that comes to mind offhand are Administrative and Test collections.

**Comment by alawvt** [comment]
OUr strategy for mapping collections in DCG is to map each top-level community, except the VTechWorks Archive collection, which contains the SWORD collections and VTechWorks Administration community. To exclude the mapped ETD collections, we can block items based on dc.types, thesis and dissertation, from their corresponding top-level communities. This will allow us to avoid having to map all the individual collections in those two top-level communities.
