### ISSUE TITLE
Update links in Wikipedia to VTechWorks items

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#714]
Use the technique in article and video, [Wikipedia: assessing and maintaining links to your repository](https://www.atmire.com/articles/detail/wikipedia-assessing-and-maintaining-links-to-your-repository) to find links in English Wikipedia to items in VTechWorks and update the links from HTTP to HTTPS. Ignore items listed as User: or Talk:

- [x] Search pattern: [`http://vtechworks.lib.vt.edu`](https://en.wikipedia.org/w/index.php?target=http%3A%2F%2Fvtechworks.lib.vt.edu&title=Special%3ALinkSearch)
Search results: 11 items
9 were updated

- [x] Search pattern: [`https://vtechworks.lib.vt.edu`](https://en.wikipedia.org/w/index.php?title=Special:LinkSearch&limit=500&offset=0&target=https%3A%2F%2Fvtechworks.lib.vt.edu)
Search results: 224 items
none were updated.

- [ ] Search pattern: [`http://hdl.handle.net/10919`](https://en.wikipedia.org/w/index.php?title=Special:LinkSearch&limit=500&offset=0&target=http%3A%2F%2Fhdl.handle.net/10919)
Search results: 90 items
 none were updated.

- [ ] Search pattern: [`https://hdl.handle.net/10919`](https://en.wikipedia.org/w/index.php?title=Special:LinkSearch&limit=500&offset=0&target=https%3A%2F%2Fhdl.handle.net/10919)
Search results: 84 items (most duplicates from above)
none were updated.

Search for items from ETD-db and update those links to VTechWorks

- [x] Search pattern: [`https://scholar.lib.vt.edu/theses/`](https://en.wikipedia.org/w/index.php?target=https%3A%2F%2Fscholar.lib.vt.edu%2Ftheses%2F&title=Special%3ALinkSearch)
Search results: 1 item
1 was updated

- [ ] Search pattern: [`http://scholar.lib.vt.edu/theses/`](https://en.wikipedia.org/w/index.php?title=Special:LinkSearch&limit=500&offset=0&target=http%3A%2F%2Fscholar.lib.vt.edu%2Ftheses%2F)
Search results: 170 items

**Comment by mello99** [comment]
Hi all, I finished this project; can't quite find a way to close this issue (or add myself as an assignee). Thanks, feel free to close the issue. Best, Melissa

**Comment by alawvt** [comment]
Thanks. This appears complete.
