### ISSUE TITLE
Improve SWORD crosswalk

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#720]
- [ ] Review ACM sample mets.xml file and fields from it to this list. Note the rights statement.

It looks like BioMed Central is still using sword-mets "SWAP Metadata" including eprints terms (xmlns:epdcx="http://purl.org/eprint/epdcx/2006-11-16/"). MDPI and Hindawi also use this packaging. A typical header is,

`<mets ID="sort-mets_mets" OBJID="sword-mets" LABEL="DSpace SWORD Item" PROFILE="DSpace METS SIP Profile 1.0" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:epdcx="http://purl.org/eprint/epdcx/2006-11-16/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.loc.gov/METS/">`

The DSpace crosswalk for this is defined in [dspace/dspace/config/crosswalks/sword-swap-ingest.xsl](https://github.com/VTUL/vtechworks/blob/vt_6_x_dev/dspace/config/crosswalks/sword-swap-ingest.xsl). This crosswalk is not mapping 

- subject, <epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/subject">
- EISSN, <epdcx:statement epdcx:propertyURI="http://purl.org/eprint/terms/JournalEISSN">
- publisher, <epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/publisher">
- journal title, <epdcx:statement epdcx:propertyURI="http://purl.org/eprint/terms/JournalName">

These could also be mapped:

- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/terms/accessRights/" epdcx:vesURI="http://purl.org/eprint/terms/AccessRights" epdcx:valueURI="http://purl.org/eprint/accessRights/OpenAccess" />
- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/identifier"><epdcx:valueString epdcx:sesURI="http://purl.org/dc/terms/URI">http://dx.doi.org/10.1155/2021/2154857</epdcx:valueString>
- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/terms/license"><epdcx:valueString>http://creativecommons.org/licenses/by/4.0/</epdcx:valueString></epdcx:statement>  
- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/type" epdcx:vesURI="http://purl.org/eprint/terms/Type" epdcx:valueURI="http://purl.org/eprint/entityType/ScholarlyWork" />
- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/identifier">
<epdcx:valueString>https://doi.org/10.3390/robotics10040109</epdcx:valueString>
</epdcx:statement>
- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/terms/idendifier/doi">
<epdcx:valueString>10.3390/robotics10040109</epdcx:valueString>
</epdcx:statement>
- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/terms/dcmitype">
<epdcx:valueString></epdcx:valueString>
</epdcx:statement>
- <epdcx:statement epdcx:propertyURI="http://purl.org/dc/terms/format/mimetype">
<epdcx:valueString>application/pdf</epdcx:valueString>
</epdcx:statement>

It could also be corrected to map <epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/identifier"><epdcx:valueString epdcx:sesURI="http://purl.org/dc/terms/URI"> to dc.identifier.doi instead of dc.identifier.uri, although this might map non-DOIs. Investigate other SWORD collections to see what mappings they use and if their mappings can be improved.

[SWAP Profle, formerly Eprints profile](http://www.ukoln.ac.uk/repositories/digirep/index/Eprints_Application_Profile)

**Comment by alawvt** [comment]
@pyc1, it seems like we could improve SWORD metadata mapping with just this one crosswalk. If there are metadata fields that we want to add for all submissions, we might be able add them, as well. You could list the changes you have been making to SWORD submissions.

**Comment by pyc1** [comment]
Fields we could add to all SWORD submissions:

dc.format.mimetype[en]       application/pdf
dc.rights[en]                         Creative Commons Attribution 4.0 International
dc.rights.uri[en]                    http://creativecommons.org/licenses/by/4.0/
dc.language.iso[en]              en
dc.type[en]                            Article - Refereed
dc.type.dcmitype[en]           Text

BioMed Central/SpringerOpen notes:

-middle initials are missing the period
-en language code comes in as dc.language.rfc3066
-DOI comes in as dc.identifier.uri

MDPI notes:

-middle initials have 2 spaces before
-DOI comes in as dc.identifier

Hindawi notes:

-DOI comes in as dc.identifier; also add https and delete "dx."

**Comment by alawvt** [comment]
map DOI correctly from both dc.identifier.url and dc.identifier.doi.

**Comment by pyc1** [comment]
I think you mean dc.identifier.uri and dc.identifier.  I'm not sure that we get any that go correctly into dc.identifier.doi.

**Comment by alawvt** [comment]
One publisher is also sending us `<epdcx:statement epdcx:propertyURI="http://purl.org/dc/terms/idendifier/doi">
epdcx:valueString10.3390/robotics10040109</epdcx:valueString>
</epdcx:statement>`.

**Comment by alawvt** [comment]
Tom Gibons from ACM notes that only some of their materials have Creative Commons licenses, so we might not be able to add that for all.

**Comment by alawvt** [comment]
When I referred to dc.title, that is the destination field for the title. The BiomedCentral sample attached, art_4959256494595851995.zip, was deposited in VTechWorks at https://vtechworks.lib.vt.edu/handle/10919/78663?show=full. 

The mets.xml file references the epdcx (ePrints Dublin Core) metadata schema

`xmlns:epdcx="http://purl.org/eprint/epdcx/2006-11-16/"`

which defines this field.

The mets.xml file is processed by [sword-swap-ingest.xsl](https://github.com/VTUL/vtechworks/blob/vt_6_x_dev/dspace/config/crosswalks/sword-swap-ingest.xsl) which also references

`xmlns:epdcx="http://purl.org/eprint/epdcx/2006-11-16/"`

All the fields will need to be sent in the form of the BioMedCentral example file. I suggest just adding one field to it and making sure that works first, perhaps
```
<epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/creator">
<epdcx:valueString>Pancotto, Theresa E</epdcx:valueString>
</epdcx:statement>
```
