### ISSUE TITLE
Add logos for Rights Statements

### ISSUE THREAD

**Issue by pyc1** [VTUL/vtechworks#729]
Add logos for rights statements in the same way that we have Creative Commons license logos: https://rightsstatements.org/en/documentation/usage_guidelines.html.  On this page our preference is for option #1, a linked logo with license text next to it (coming from the dc.rights field).

**Comment by alawvt** [comment]
It is necessary for dc.rights.uri URLs for Creative Commons licenses to be HTTP and not HTTPS for the license logos to display correctly, see #730. Try to determine if this would be the case for RightsStatements.org logos, as well.

**Comment by alawvt** [comment]
The instructions in [Displaying the rights Statements](https://rightsstatements.org/en/documentation/usage_guidelines.html) are to link to the HTTPS form of the RightsStatement.

From the discussion in [DS_2604 Creative Commons license assignment silently fails in JSPUI](https://jira.lyrasis.org/browse/DS-26040, it sounds like the HTTPS URL problem with the CC logo is due to redirection by the Creative Commons API. 

Since we won't be using that CC API for RightsStatements.org, I think we should proceed with using HTTPS for dc.rights.uri values for RightsStatements.

**Comment by alawvt** [comment]
Hmm, the plot thickens. After all that, I started to update our documentation and found that `https://rightsstatements.org/vocab/InC-EDU/1.0/` gives an error whereas, `https://rightsstatements.org/vocab/InC-EDU/1.0/` redirects to `https://rightsstatements.org/page/InC-EDU/1.0/?language=en`. Therefore, I think we better use HTTP. However, I will write to RightsStatement.org about this issue.

**Comment by alawvt** [comment]
I have just asked for clarification

>Rights Statements.org,

>We plan to add RightsStatement.org statements to most items in our DSpace repository. I would like to check on the implementation. In the FAQ question, "Why are there different versions of the URIs of the statements?," https://rightsstatements.org/en/documentation/faq.html, you use HTTP URLs exclusively. And rights statement pages, such as https://rightsstatements.org/page/InC/1.0/?language=en, also disply HTTP for the assoicated URL. However in "Guidelines for applying the rights statements," https://rightsstatements.org/en/documentation/usage_guidelines.html, you use HTTPS in the examples of "Displaying the rights statements." Would you please clarify which form we should use in our dc.rights.uri field?

**Comment by alawvt** [comment]
Reply for rightsstatements.org

>Thanks for reaching out. These are non-trivial matters indeed, and we had to articulate our message several times already.
It will be easy for me to answer, though, as you have already identified all the pieces of the message!

>The HTTP URIs are the canonical ones, to be used in the data. For use in viewers, HTTPS one would be appropriate. Note that the HTTP ones redirect to the HTTPS ones in any case for regular requests, so a viewer won't be really impacted and will end up anyway on the HTTPS URL if you give it the HTTP one as input.

Based on this reply, I think it would be best if we use HTTP in the values for dc.rights.uri.

**Comment by alawvt** [comment]
Digital Georgetown is a DSpace repository that has implemented the RightsStatements.org logos, ex. https://repository.library.georgetown.edu/handle/10822/1060124

```
a.gucopyright.InC {
    background: url("/static/images/rights/InC.dark.svg") no-repeat;
        background-size: auto;
}
```
