### ISSUE TITLE
Check display of CC0 1.0 Universal Public Domain Dedication and Public Domain Mark 1.0 logos

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#731]
Check display of CC0 1.0 Universal Public Domain Dedication and  Public Domain Mark 1.0 logos.

dc.rights: Creative Commons CC0 1.0 Universal Public Domain Dedication
dc.rights.uri: http://creativecommons.org/publicdomain/zero/1.0/

dc.rights: Creative Commons Public Domain Mark 1.0
dc.rights.uri: http://creativecommons.org/publicdomain/mark/1.0/

**Comment by alawvt** [comment]
<img width="710" alt="CC_1_0_Dedication_HTTP" src="https://user-images.githubusercontent.com/13037168/94151440-6abb9480-fe48-11ea-9ef4-ea5dbe8acb48.png">
<img width="551" alt="CC_1_0_Mark_HTTP" src="https://user-images.githubusercontent.com/13037168/94151732-bd954c00-fe48-11ea-9d67-944955b22e7f.png">

**Comment by pyc1** [comment]
FYI I deleted the parens (CC0 1.0) from the statement in the wiki to make it consistent with the others
