### ISSUE TITLE
Patron can't select collection even though she's in the submitters' group 

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#742]
A. M. requested submission privileges to the [Institute Publications collection](https://vtechworks.lib.vt.edu/handle/10919/82127) in ICTAS, so I added her to the submitters' group. Later, she told me that when she signs in to her VTechWorks account and tries to start a new submission, she doesn't have any collections to choose from in the drop down list. I double checked the submitters' group for this collection, and confirmed that she was still in it. I also checked with her to make sure she was signing in with the correct email address (she is). I am not sure what could be causing this. Suggestions welcome.

**Comment by alawvt** [comment]
This was caused by duplicate epersons for this email address. I have removed the duplicate and contacted the patron.

**Comment by cecross1** [comment]
Thanks for catching that! I'm glad it was an easy fix.

**Comment by alawvt** [comment]
Yes, I searched epersons by first name and found the duplicate.

**Comment by alawvt** [comment]
I reported this issue in [DS-4568 Possible to create multiple epersons with the same email address](https://jira.lyrasis.org/browse/DS-4568).

**Comment by cecross1** [comment]
@alawvt Thanks for reporting this.
