### ISSUE TITLE
Change the link to VTechData on the home page

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#751]
The link remains the same, https://data.lib.vt.edu/. Change label from "VTechData" to "Virginia Tech Data Repository."

**Comment by alawvt** [comment]
resolved with #817.

**Comment by pyc1** [comment]
Change the first sentence on the page to:

VTechWorks provides global access to Virginia Tech scholarship, and is the repository for the university's [open access policy](https://guides.lib.vt.edu/oapolicy/).
