### ISSUE TITLE
Update VT brand colors

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#768]
Update VT brand colors

[VT Brand Guidelines 2019-10-29](https://brand.vt.edu/content/dam/brand_vt_edu/downloads/FINAL%20Brand%20Guidelines%2010.29.19.pdf)
```
CHICAGO MAROON: #861F41
BURNT ORANGE (WEB): #C64600
```

**Comment by alawvt** [comment]
first commit: update values for Chicago Maroon and Burnt Orange; links are the current non-VT brand color. Normally, with the list of communities, there would many more links on the home page.

<img width="1023" alt="UpdateVT_brannd_colors_1" src="https://user-images.githubusercontent.com/13037168/130681576-84c15ee0-3659-480f-ba70-9c67be2e559a.png">

**Comment by alawvt** [comment]
later commits: To match VT News, https://vtx.vt.edu/:

- updated $chicago-maroon and $burnt-orange to latest standards
- changed <a> links to burnt-orange and underlined, so they would accessible, since they don't have sufficient color contrast with the surrounding text
- changed <a> links in xmlu-news from bold to not bold and underline

<img width="1110" alt="UpdateVT_brannd_colors_5" src="https://user-images.githubusercontent.com/13037168/130989721-0777cffc-3a59-4287-b1f9-9160a15261e2.png">
The result is brighter.

**Comment by alawvt** [comment]
3rd commit: cadet-blue for links looked ok but had insufficient color contrast to surrounding text.
4th commit: a better shade of burnt orange (web) for links
<img width="1023" alt="UpdateVT_brannd_colors_4" src="https://user-images.githubusercontent.com/13037168/130687054-c796ab3b-d6ae-4c81-bcb5-d2a2e66fce27.png">
@pyc1, what do you think of this?

**Comment by pyc1** [comment]
I'm having a hard time seeing the changes, other than the orange horizontal line at the top (I like the brighter orange that we currently have).  I can't see how the link color is different, sorry.

**Comment by alawvt** [comment]
Resolved by #770.

**Comment by alawvt** [comment]
I looked at the theme.  I think one issue is that the maroon got lighter and the orange got darker and they aren't that far apart anymore.  It's difficult to distinguish the horizontal orange line at the top - at a glance it looks maroon too.  Maybe we could use the new maroon and the old orange?  I also don't care for the links turning light blue.  Does that help accessibility, or is the underline enough?  The links do stand out more now which is a good thing I guess. - @pyc1

**Comment by alawvt** [comment]
I agree that the new maroon and orange aren't far apart. We could go back to a browner orange for the links like we have on production now. I don't think the new orange changed the horizontal bar. I don't know if the blue for link hovering is necessary for accessibility, it is what the VT New had. Here is a screenshot of another orange shade,
<img width="1023" alt="UpdateVT_brannd_colors_4" src="https://user-images.githubusercontent.com/13037168/131543044-b67d1191-8568-4932-a881-c36a1fa5b680.png">
This is more reddish that the brown text we have now but not as bright as the straight theme. Do you have a preference for the current link color on production (first screenshot) or this?
