### ISSUE TITLE
Enable Sherpa/Romeo lookup in submission process

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#77]
See https://wiki.duraspace.org/display/DSDOC5x/Configuration+Reference#ConfigurationReference-ConfiguringtheSherpa/RoMEOPublishersPolicyDatabaseIntegration for instructions

**Comment by AmberPoo1** [comment]
Hi @amandafrench, @alawvt , Sherpa/Romeo is enabled by default in dspace 5, but it relys on the correct ISSN of we input during submission. For example, for publisher "Nature"(Journal), ISSN should be "0028-0836". Now not all of the articles in our repository have valid ISSN information.

These are two examples running in my local machine:
1. The submitting item's publisher is "American Journal of Enology and Viticulture", ISSN is "0002-9254":
![screen shot 2015-11-05 at 4 39 53 pm](https://cloud.githubusercontent.com/assets/13734326/10982608/2f2d1c4a-83dc-11e5-85f7-589952a1d8af.png)

2. The submitting item's publisher is "Nature", ISSN is "0028-0836":
![screen shot 2015-11-05 at 4 46 13 pm](https://cloud.githubusercontent.com/assets/13734326/10982718/d4e5a86e-83dc-11e5-8150-fd126eaeecf0.png)

For reference:
We can look up ISSN of Journals in: http://www.sherpa.ac.uk/romeo/search.php
See https://wiki.duraspace.org/display/DSDOC5x/Configuration+Reference#ConfigurationReference-ConfiguringtheSherpa/RoMEOPublishersPolicyDatabaseIntegration for more information

**Comment by AmberPoo1** [comment]
@amandafrench ,@alawvt, I have applied for an Sherpa/Romeo API key, it's free and can raise the usage limit (There is a limit of 500 calls/day for unregistred user).

**Comment by amandafrench** [comment]
Thanks for this, @AmberPoo1! This will be good information for @alawvt and @mello99 to have if they upload things through the browser submission form, and good for me to have as I see about simplifying and clarifying the submit form. I'll close this issue.

**Comment by alawvt** [comment]
@AmberPoo1, please apply for another API key and mail it to me. I will coordinate to have it installed. Thanks.

**Comment by amandafrench** [comment]
Have applied for new API key, but I haven't gotten the confirmation email yet. Hoping it didn't get blocked; it's not in spam.

**Comment by amandafrench** [comment]
I did get the new API key, yay! I forwarded it to @alawvt and @AmberPoo1. Assigning to @alawvt for implementation.

**Comment by alawvt** [comment]
I submitted a TeamDynamix request for this and @kayiwa responded by adding the key to dspace.cfg on vtechworks.lib.vt.edu. I reverted the original commit.
