### ISSUE TITLE
Add off-campus sign-in link

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#78]
Probably best to add it to the navigation bar under the Help page, but could be implemented in any number of ways. Make sure it shows up on all Simple Item and Full Item views, in particular. See http://www.lib.vt.edu/help/extended/extproxy.html for link / button. If necessary, you can consult with @alawvt if necessary to confirm the best method of implementation.

**Comment by alawvt** [comment]
On vtechworks.dev.vt.edu, clicking on the link for for Off Campus Sign, produces this message,

```
To allow https://vtechworks.dev.lib.vt.edu/ to be used in a starting point URL, 
your EZproxy administrator must first authorize the hostname of this URL in the config.txt file.

Within this database's section of config.txt, either the following line must be added:

    Host https://vtechworks.dev.lib.vt.edu

or, alternatively, a RedirectSafe for this host or domain may be appropriate.

After editing config.txt, the EZproxy server must be restarted to make changes take effect.
```
Noting this in case EZproxy needs configuring for vetchworks.lib.vt.edu, vtechworks.dev.lib.vt.edu, or vtechworkspprd.lib.vt.edu.

**Comment by kayiwa** [comment]
I've passed this on to Aaron to set up. Will update this when it is done.

**Comment by kayiwa** [comment]
Please test this now.

**Comment by alawvt** [comment]
Thank you. It seems to work from on-campus. We'll have to wait until it is installed on production to test it from off campus.
