### ISSUE TITLE
Research how to import content from Symplectic Elements

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#79]
This commercial system (see http://symplectic.co.uk/products/elements/ ) is in the process of being implemented at Virginia Tech. There is a test system at http://ed.lib.vt.edu. I will set up a meeting with the developer of that system and will see about getting us access to it. See also presentation at http://researchcommons.waikato.ac.nz/handle/10289/9339 

Ideally, what we want is for content and metadata added to Elements to be automatically ingested into DSpace. There will also be issues with duplicate content and with making sure that DSpace gets only full-text content and not metadata-only records.

**Comment by AmberPoo1** [comment]
We will revisit this issue in spring.
