### ISSUE TITLE
Add additional disciplines to OMALS submission form

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#807]
Please add disciplines:

- Agribusiness
- Applied Animal Behavior and Welfare

to the OMALS submission form

**Comment by kdweeks** [comment]
I didn't know this issue was open.  This issue is continued by [#183](https://github.com/VTUL/vtechworks/blob/vt_6_x_dev/dspace/config/input-forms.xml) in code.vt.edu (local code base).
