### ISSUE TITLE
Write DSpace 7 bug and feature request tickets to match DSpace 6.3 XMLUI functionality

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#811]

**Comment by alawvt** [comment]
- [Search Facet: Increase the number of options displayed with each "Show more" click #8429](https://github.com/DSpace/DSpace/issues/8429) - ok, is configurable
- [In facets, vertically align checkbox with first word of option #1711 ](https://github.com/DSpace/dspace-angular/issues/1711) - resolved
- [Add breadcrumb navigation (option) #1784](https://github.com/DSpace/dspace-angular/issues/1784) - resolved
- [Allow for more than one item type in the Submission Form #1802](https://github.com/DSpace/dspace-angular/issues/1802) - resolved
- [Add thumbnail to Search list view #1744](https://github.com/DSpace/dspace-angular/issues/1744) - resolved in 7.4
- [Add thumbnail to Browse #1745](https://github.com/DSpace/dspace-angular/issues/1745) -resolved in 7.4
- [ Edit Item > Authorizations > Policy Group change does not appear #1753 ](https://github.com/DSpace/dspace-angular/issues/1753) - resolved in 7.4
- [Make the number of communities in the Browse by Community page configurable #1750](https://github.com/DSpace/dspace-angular/issues/1750) - resolved in 7.4
- [Make number of communities on the home page configurable #1749](https://github.com/DSpace/dspace-angular/issues/1749) - resolved in 7.4
- [Preserve line breaks in metadata #1762](https://github.com/DSpace/dspace-angular/issues/1762)  - resolved in 7.4
- [Display line breaks in metadata #1763](https://github.com/DSpace/dspace-angular/issues/1763)  - resolved in 7.4
- ["Recently Added Items" doesn't exist on homepage & community pages #667](https://github.com/DSpace/dspace-angular/issues/667) - resolved in 7.4
___________________________
- [Display all the fields for a Metadata Schema in one page and include IDs #1766 ](https://github.com/DSpace/dspace-angular/issues/1766) - resolved in 7.5
___________________________
- [ Facet search box should search all words, not just first word, in options #1712 ](https://github.com/DSpace/dspace-angular/issues/1712)
- [ In Advanced Search, list collections alphabetically #8408 ](https://github.com/DSpace/DSpace/issues/8408)
- [In Submission Form, list collections alphabetically #8412 ](https://github.com/DSpace/DSpace/issues/8412)
- [In Date facet, start date option should adjust with slider #8418 ](https://github.com/DSpace/DSpace/issues/8418)
- [Process page: Separate Output File links #8425](https://github.com/DSpace/DSpace/issues/8425)
- [ Display Search Facets on all Home, Community, and Collection pages #8426 ](https://github.com/DSpace/DSpace/issues/8426)
-  [Make Browse results searches and/or add "All" to Search Facet options #8427 ](https://github.com/DSpace/DSpace/issues/8427)
- [Support Search Facet customizations per Community or Collection #8428 ](https://github.com/DSpace/DSpace/issues/8428)
- [Provide an Advanced Search page with Boolean options #8431](https://github.com/DSpace/DSpace/issues/8431)
- [Document the Media Viewer #1746](https://github.com/DSpace/dspace-angular/issues/1746)
- [Edit Item: Remove Zero Width Spaces in field names so they can be copied #1754](https://github.com/DSpace/dspace-angular/issues/1754)
- [Display more than 5 e-people or groups per page #1764](https://github.com/DSpace/dspace-angular/issues/1764)
- [Display all bitstream formats on one page and include IDs. #1767](https://github.com/DSpace/dspace-angular/issues/1767)
- [Summary of requests to configure the number of items in various lists #1772](https://github.com/DSpace/dspace-angular/issues/17720)
- [Make the number of bitstreams on the Item pages configurable #1774](https://github.com/DSpace/dspace-angular/issues/1774)
- [Include the collection of the submitted item in Workflow view #1782](https://github.com/DSpace/dspace-angular/issues/1782)
- [Add option to display Item counts for Communities and Collections #1787](https://github.com/DSpace/dspace-angular/issues/1787)
- [Use full community and collection names in breadcrumb navigation #1794](https://github.com/DSpace/dspace-angular/issues/1794)
- [Error replying to request a copy #1806](https://github.com/DSpace/dspace-angular/issues/1806)
- [Shorten the Edit resource policy description textbox and add a Group dropdown field #1807](https://github.com/DSpace/dspace-angular/issues/1807)
- [Disable Swedish Research Subject Categories by default in submission form #1817](https://github.com/DSpace/dspace-angular/issues/1817)

**Comment by alawvt** [comment]
## DSpace 6 XMLUI vs DSpace 7 comparison
### Will need to test locally
- Video playback: @keithgee, I created an item on DSpace 7 Demo and uploaded .mp4, .vtt, and .png files to the item. When I clicked on each file in Item View, it downloaded the file but did not display it. Tim confirmed that the media players are disabled on Demo. We will need to test this on our test server.
- we'll need to test IIIF player locally
- Media-filter
- customizing submission form
- item level customization of submission form
- check item submission per item type, does it play with multiple item types?
- Creative Commons step in submission form (disabled by default)
- Handle redirection (DSpace 7 only uses local URLs like https://demo7.dspace.org/handle/10673/9084.)

### Test on DSpace 7 Demo and DSpace 6 XMLU Demo
- Simple Item View and Full Item View seems fine
- Statistics: 
    - DSpace 6 XMLUI "View Usage Statistics" in DSpace 7 "Statistics" in header. Same content: Total visits and views. "View Search Statistics" and "View Workflow Statistics" missing, not critical. 
    - Legacy stats are missing.  
- Metadata registry: functionality is equivalent
- Import Metadata: functionality is equivalent, although I think it was patterned on JSPUI, producing a file for both the preview and real upload that includes the changes and  handles of the created or changed items. This could be useful for recording uploads.
- SWORD v1 and v2 both yielded service documents
- REST-API seems ok
- OAI-PMH comparable to DSpace 6
- Want to browse collections and other browse? with fewer clicks
    - home page has 5 communities, click next page shows 5 more
    - collection browse page has 20 communities, clicks add 20 communities
- No recent items on home page; Is that configurable?
- The item page URL now has the UUID instead of handle, e.g. https://demo7.dspace.org/items/32192b5b-6edb-41f5-aaa3-cbc39a172394 for  https://demo7.dspace.org/handle/10673/8854
- Edit Item: 
    - Edit metadata: DS6 has dropdown box of all possible values; DS7 no dropdown, you have to type but then has suggested auto-completes. Can copy metadata field to new value but error because of zero width spaces. (Need repetition for adding ETD advisors, etc.)
    - Authorizations - when you change group, it doesn't initially appears on policies page.
    - Item mapping - can map from both Edit Item and Edit Collection pages so better than DSpace 6 XMLUI
    - Bitstreams - ordering bitstreams is drag and drop which is much better than DSpace 6 XMLUI endless clicks.
- Check HTML support for abstracts, etc. - both DSpace 6 and 7 Demo do not display new lines nor render the HTML tag `<p>`. DSpace 7 does not preserve line breaks in metadata. - showstopper - don't want to lose abstract formatting
- Administrative search - very nice
- Curate:  Works; The curation task seems to run without error but https://github.com/DSpace/dspace-angular/issues/1322 describes the lack of results output.
- Processes New: needs to know command line switches, etc.
Control panel in DSpace includes SystemWide Alerts, Current Activity; compare to Health
- Health - Status and Info cover most of DSpace 6 XMLUI Control Panel - Java Information and Configuration
- - can't (yet) upload a zip from the front end but still can from the command line
- Added our support for [Create "System Wide Alerts" feature for Angular UI #1537](https://github.com/DSpace/dspace-angular/issues/1537) 
- Added our support for [Display full hierarchy of chosen collection (during submission/workflow) #1340](https://github.com/DSpace/dspace-angular/issues/1340)
- check logos for CC license; not enabled on DSpace 7 Demo, so need to test later, see https://wiki.lyrasis.org/display/DSDOC7x/Configuration+Reference#ConfigurationReference-ConfiguringCreativeCommonsLicense
- can one select more than one item type in submission? - no
- submission form uses onebox instead of name input-type for author name
- subscribe to a collection, https://wiki.lyrasis.org/display/DSDOC7x/Functional+Overview#FunctionalOverview-Subscriptions - not yet implemented
- email address no longer in provenance field?
- test request a copy

## Notes
When one registers for an account they submit an email address. They have to click on the verification email, then agree to the End User Agreement, which we will have to write.

## Possible feature requests
- Rights.org statements

We will need to consider how we will display videos in DSpace 7 and what files they support/need. Test: upload a short mp4 with captions to https://demo7.dspace.org/ and see if the video and captions play.

check RSS and ATOM feeds.

**Comment by alawvt** [comment]
Make a list of lists per https://github.com/DSpace/dspace-angular/issues/1764#issuecomment-1215161906.

**Comment by alawvt** [comment]
Done, at least for now.

**Comment by keithgee** [comment]
Continued in #819 

Another local only issue - if we are going to remove Nginx, (and I do think having fewer components is a good idea), we'll need some guidance from the sysadmins on how to handle forwarding from old, deleted urls of duplicate items to the remaining item, which is now handled with nginx. From previous gitlab issues and projects:

https://code.vt.edu/it-services/vtlibans_dspace/-/issues/159
https://code.vt.edu/it-services/vtw-handle-redirects

Can traefik handle this directly? Do we need a different file format and a different process, or can we use the same?

**Comment by alawvt** [comment]
Continued in #820.
