### ISSUE TITLE
Upgrade to DSpace 6.4

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#818]
Upgrade to DSpace 6.4

[DSpace 6.4 Release Status](https://wiki.lyrasis.org/display/DSPACE/DSpace+6.4+Release+Status)

**Comment by alawvt** [comment]
I am attempting to follow the instructions in [Upgrading VTechWorks for DSpace point releases](https://github.com/VTUL/vtechworks/wiki/Upgrading-VTechWorks-for-DSpace-point-releases). I pulled the [dspace-6.4 tag](https://github.com/DSpace/DSpace/blob/dspace-6.4/.gitignore), on the dspace-6_x branch. For some reason it removed the local.cfg file, so I added it back to the branch, [add_6_4_changes](https://github.com/VTUL/vtechworks/blob/add_6_4_changes). When I run vagrant with [add_6_4_changes](https://github.com/VTUL/vtechworks/blob/add_6_4_changes), it fails in the "build it with maven task," with copious warnings. @keithgee, if you could, would you try running this branch? Thanks.

**Comment by alawvt** [comment]
I tried it again with new branch [add_6_4_changes_2](https://github.com/VTUL/vtechworks/blob/add_6_4_changes_2). This time I have a shot at getting the conflicts resolved. I'm building it now.

Alas, it has failed at the build it with maven step. The attached output looks similar to that from branch add_6_4_changes. -- A sure-fire cure for insomnia.
[untitled text 3.txt](https://github.com/VTUL/vtechworks/files/9718676/untitled.text.3.txt)

**Comment by keithgee** [comment]
>  -- A sure-fire cure for insomnia. 

I think it's going to give me nightmares.

**Comment by kdweeks** [comment]
+1

Kimberli Weeks
***@***.***
w. (540) 231-2674 c. 540-835-9136
Technical Director,
Scholarly Communication <http://scholar.lib.vt.edu>
University Libraries, Virginia Tech

**Comment by alawvt** [comment]
One conflict was the version of node.js. I chose the later version so that should be investigated as a source of problems.

**Comment by keithgee** [comment]
We're on version 7.6 as of 2024.
