### ISSUE TITLE
Figure out alternative to Nginx for forwarding duplicate Handles

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#819]
Another local only issue - if we are going to remove Nginx, (and I do think having fewer components is a good idea), we'll need some guidance from the sysadmins on how to handle forwarding from old, deleted urls of duplicate items to the remaining item, which is now handled with nginx. From previous gitlab issues and projects:

https://code.vt.edu/it-services/vtlibans_dspace/-/issues/159
https://code.vt.edu/it-services/vtw-handle-redirects

Can traefik handle this directly? Do we need a different file format and a different process, or can we use the same?

**Comment by soumikgh** [comment]
Traefik can handle this directly, but it'll be hard to automatically merge changes to the redirect URL to it like how we do it for Nginx right now.

We can still probably come up with an acceptable system where we manually verify and push changes from a repository once a month into the Traefik config.

**Comment by alawvt** [comment]
Thank you for this information, @soumikgh.

**Comment by pyc1** [comment]
@keithgilbertson can this issue be closed?

**Comment by keithgilbertson** [comment]
Yes. Thank you.

From: Philip Young ***@***.***>
Date: Tuesday, July 30, 2024 at 9:05 AM
To: VTUL/vtechworks ***@***.***>
Cc: Gilbertson, Keith ***@***.***>, Mention ***@***.***>
Subject: Re: [VTUL/vtechworks] Figure out alternative to Nginx for forwarding duplicate Handles (Issue #819)

@keithgilbertson<https://github.com/keithgilbertson> can this issue be closed?
