### ISSUE TITLE
Handle server is down

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#822]
Symptoms match [ DSpace (5/6?) handle server doesn't start after JDK 8 update #8557 ](https://github.com/DSpace/DSpace/issues/8557)

**Comment by keithgee** [comment]
Systems administrators have pinned Java to a previous version as a temporary fix.

**Comment by alanorth** [comment]
There's a patched Handle server JAR for DSpace 6.x now BTW:

https://github.com/DSpace/DSpace/issues/8557#issuecomment-1595340249

**Comment by keithgee** [comment]
Resolved with our upgrade to DSpace 7.
