### ISSUE TITLE
Deploy Kelp changes to dev.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#823]
Please deploy Kelp changes to dev.

Release notes for Kelp may be a bit sparse as some of the details are lost to memory: https://github.com/VTUL/vtechworks/releases/tag/untagged-8293de6c83689263b222

The beginning of a test plan is in [DSpace_6.3_202221110_Kelp_Testing](https://docs.google.com/spreadsheets/d/1BI8kYlegakPm01oW-LGNq6q6VrGvxhFfvRccB8__8J4/edit?usp=sharing)

**Comment by keithgee** [comment]
These changes were deployed to dev a couple of weeks ago and we currently testing and resolving minor issues.
