### ISSUE TITLE
Figure out why "|||" is appearing in the department facet for ETDs. 

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#83]
The department facet for the ETD community and collections, e. g., https://vtechworks.lib.vt.edu/handle/10919/5534, lists many with the value, "|||." If you click on the facet, no search results appear. I downloaded all the metadata for the dissertation collection and did not find any "|"s in the dc.contributor.department[] and dc.contributor.department[en_US] and thesis.degree.discipline fields (nor in any other fields).

**Comment by keithgee** [comment]
@alawvt I couldn't figure out how to see this issue 🦄

**Comment by alawvt** [comment]
If you go to this collection and view the right department facet, you should be able to see it.

**Comment by alawvt** [comment]
The search, https://vtechworks.lib.vt.edu/handle/10919/11041/discover?filtertype_0=advisor&filtertype_1=dateIssued&filtertype_2=dateIssued&filter_relational_operator_1=equals&filtertype_3=department&filter_relational_operator_0=equals&filter_2=[2010+TO+2015]&filter_relational_operator_3=equals&filter_1=2014&filter_relational_operator_2=equals&filter_0=Brandon%2C+Thomas+L&filter_3=Civil+Engineering&filtertype=subject&filter_relational_operator=equals&filter=clays yields one item, https://vtechworks.lib.vt.edu/handle/10919/56631?show=full, which has the department facet=|||. In full item view, it displays thesis.degree.discipline but the field is blank. In comparison, http://vtechworks.lib.vt.edu/handle/10919/30070?show=full does not display the thesis.degree.discipline field at all. So I think this issue is caused by thesis.degree.discipline existing but being blank.  
To test this, https://vtechworks.lib.vt.edu/handle/10919/56955 is another item that had department facet=|||. I deleted the thesis.degree.discipline field for this item. It still shows in the department facet=||| for the search, https://vtechworks.lib.vt.edu/handle/10919/11041/discover?filtertype_0=advisor&filtertype_1=dateIssued&filtertype_2=dateIssued&filter_relational_operator_1=equals&filtertype_3=department&filter_relational_operator_0=equals&filter_2=[2010+TO+2015]&filter_relational_operator_3=equals&filter_1=2014&filter_relational_operator_2=equals&filter_0=Brandon%2C+Thomas+L&filter_3=Civil+Engineering. I will check tomorrow to see if it is still in the count of items with |||.

**Comment by alawvt** [comment]
https://vtechworks.lib.vt.edu/handle/10919/43536?show=full has dc.contributor.advisor="", so it is appearing in committee chair facet=|||. It looks like these records were all migrated from ETD-db. It seems like it took in blank fields.

I am thinking about how to fix this. Usually with the batch metadata tool, when we want to get rid of a value in a field, we just load that field as blank. I'm not sure what to do in this case when it really is blank. (How blank does it need to be?!)

**Comment by alawvt** [comment]
I think the investigative part of this issue is complete. I have added a task in the Metadata backlog to remove these offending fields.

**Comment by alawvt** [comment]
Test removing blank field using the web batch metadata uploading tool:

Item: https://vtechworks.lib.vt.edu/handle/10919/56631
Empty field: dc.degree.discipline[en_US]

export metadata for item.
save a csv with only id and empty thesis.degree.discipline[en_US]
```
id,thesis.degree.discipline[en_US]
66799,
```
upload csv with web batch metadata tool.
result
```
Notice

No changes were detected
```
This method does not appear to work.
