### ISSUE TITLE
Fix HTML in ALL the fields (Subject, Title)

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#84]
See for instance http://vtechworks.lib.vt.edu/handle/10919/46509?show=full

Frankly I'd rather strip the HTML tags out, but I think we need to coordinate with the grad school for that and/or add some HTML stripping functions to our ETD ingest scripts. If you come across non-ETD items that have HTML in the data, @alawvt and @mello99, could you add them here in the comments? I feel like it's mostly ETDs that have this issue, but feel free to prove me wrong.

**Comment by alawvt** [comment]
This is from ETD-db. You can tell by the "dc.identifier.sourceurl=http://scholar.lib.vt.edu/theses/available/etd-72698-12353/" and the date: pre-2012. I don't think the current Grad School ETDs have HTML. ETD-db data also has \r and \n in it, which may have been translated from <p> when they were imported to VTechWorks. BTW, "&szlig-95-Cysteinyl" should be β-95-Cysteinyl."

**Comment by AmberPoo1** [comment]
I noticed a misuse of "&amp;" in http://vtechworks.lib.vt.edu/handle/10919/46509?show=full , "&amp;" should only be used when writing URLs in HTML, in other common cases, "&" should be used. For example, "&szlig". One solution is transferring these tags using some api in our code.

**Comment by alawvt** [comment]
In DLA, we routinely used many HTML entities in HTML, not just in URLs. It was necessary before browsers supported UTF-8. I am sure you will see plenty of them in HTML imported from DLA.
