### ISSUE TITLE
Item count for VCE collection /5523 doesn't update after items deleted

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#85]
Do we have a cron job to reindex VTechWorks? If so, how often or when does it run? Same question for itemcounter. Thanks.

**Comment by kayiwa** [comment]
once a day for 

```
/dspace/bin/dspace index-discovery
```

nothing on 

```
/dspace/bin/dspace itemcounter
```

**Comment by alawvt** [comment]
Thanks, @kayiwa.  

@keithgee, is itemcounter something we need to run regularly? We have noticed that collection item counts don't seem to be changing. For instance, @mello99 deleted 47 items from the VCE collection, https://vtechworks.lib.vt.edu/handle/10919/5523, last week but the item count has not changed.

**Comment by kayiwa** [comment]
FWIW I ran and I've run 

```
/dspace/bin/dspace itemcounter
```

multiple times since your request. If this hasn't made a difference (I suspect not given how quickly it completes) the fix lies elsewhere.

**Comment by alawvt** [comment]
@kayiwa, thank you for trying that. You are correct, the item count of the VCE collection has not changed.

**Comment by alawvt** [comment]
@keithgee, do you have any ideas?

**Comment by alawvt** [comment]
Here are some notes about itemcount from two old Redmine issues,  

https://redmine.lib.vt.edu/issues/216

"Updated by Keith Gilbertson over 1 year ago
    Due date set to 2014-02-07  
    Status changed from New to Resolved  
   
Comment Edit

Collection strengths do update automatically, in a sense, but not immediately after items are loaded. Due to the design of DSpace, and for performance reasons, an external program, "itemcounter" must run on the server to update the collection strengths.

The collection strength updater was set to run every day at 3AM. I've now set it to run every hour from 7AM - 8PM. This should cause collection strengths to update every hour during the day, instead of once per day at night. If there are performance problems, this will need to be adjusted to run less often again."

https://redmine.lib.vt.edu/issues/201

"Updated by Chris McCarty over 1 year ago

    Status changed from New to Resolved

Comment Edit

Both the collection and community count for that label are found using solr queries. Similar to http://redmine.lib.vt.edu/issues/216, the $dspace update-discovery-index command has to be run every time you want to update solr. However, this command had not been running on a schedule, but has now been set up to run at the same frequency as the itemcounter script from the related issue."

**Comment by keithgee** [comment]
@mello99, do you remember what day you deleted the items?

**Comment by keithgee** [comment]
@mello99 and @alawvt, I also didn't actually go through and count every item, but that VCE collection does go up to 3052 in the results pages:
http://vtechworks.lib.vt.edu/handle/10919/5523/recent-submissions?offset=3040

What items were deleted, specifically? And when? This will help to track things down.

**Comment by mello99** [comment]
https://drive.google.com/open?id=0B7IH56M-y5-ldGxUOXBZa3hZVVE

Above is the list of removed duplicates. They were deleted approximately 5 days ago.

**Comment by alawvt** [comment]
I seems like DSpace has it's own peculiar way of counting. For recent submissions, it's supposed to show 20 items per page. However  it actually can show less:
http://vtechworks.lib.vt.edu/handle/10919/5523/recent-submissions? "Now showing items 1-19 of 3052" (Where is item 20?)
http://vtechworks.lib.vt.edu/handle/10919/5523/recent-submissions?offset=20 "Now showing items 21-39 of 3052"  (Where is item 40?)
http://vtechworks.lib.vt.edu/handle/10919/5523/recent-submissions?offset=40 "Now showing items 41-60 of 3052"
So it seems like it not always has the full number of items per page.

This also seems to happen in the discovery interface, http://vtechworks.lib.vt.edu/handle/10919/5548/discover. If I select 100 results per page, page one says "Now showing items 1-96 of 3052" and there are 96 items on that page  --hmm.

**Comment by amandafrench** [comment]
This issue has metastasized into several issues: I think the pagination issues @alawvt mentions above are different from the item counts in the VCE collection. I also think the 3007 items in metadata download vs. 3052 in item count is a separate issue; that might have to do with mapped items. I'll put those two in the backlog for investigation. I'm also going to rename this issue so that it's more specifically about solving the problem of why the item count doesn't update. 

I think this might be an issue with deletion, by the way: item counts on dev at least do seem to be updating properly when items are added, but not when they are deleted. 

This is a fairly small bug, by the way, so feel free to say 'wontfix' for now and close it, @keithgee. We'll keep track. Might also be an issue in DSpace generally.

**Comment by keithgee** [comment]
It's a good thing this isn't an accounting application, because it isn't a' countin' right.

**Comment by amandafrench** [comment]
Like

**Comment by keithgee** [comment]
I found that the items that @mello99 had deleted still had documents in the solr index. I deleted these solr documents, and now the item count in the collection is at 3006. This also fixed some of the pagination issues.

Thank you @mello99 for providing the spreadsheet of deleted items. This was useful for fixing the problem. Please keep an eye out to see if this happens again; I'm not sure why the items weren't removed from the solr index when you deleted them, so it may reappear.

Closing.
