### ISSUE TITLE
Create smaller .sql file for local machines so that indexing doesn't fail / take so long

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#89]
@alawvt, can you write up some guidelines for @keithgee on how many items from each collection / community this should have and any other specs that are important? Do all communities / collections need to have some items, for instance? 

Will assign this to you for now: assign it back to Keith when you've written it up.

**Comment by alawvt** [comment]
@keithgee and I had discussed this on Wednesday and considered using two test sql files: one with the complete community/collection structure but with far fewer items in the large collections and a second that has many few items but content to test full text indexing. I think we could wait a bit on the second file. 

Here are the specs that I suggest for the first file:

A full copy of the present sql file but reduce each of the following collections to only 200 items:
Doctoral Dissertations: 10919/11041
Masters Theses: 10919/9291
Publications (VCE): 10919/5548
Computer Science Technical Reports: 10919/19372
April 16, 2007, Condolence Archives: 10919/11385
VT News: 10919/19073

This will reduce the file by approximately 34,000 items.

**Comment by keithgee** [comment]
I've placed ewer_items_database_dump.sql.gz on our folder in Google Drive.
It's *approximately* to @alawvt specifications.
Closing.
