### ISSUE TITLE
VTechWorks University text on recent submissions page 

### ISSUE THREAD

**Issue by keithgee** [VTUL/vtechworks#90]
http://vtechworks.lib.vt.edu/recent-submissions

That page says "VTechWorks University"

**Comment by alawvt** [comment]
This was one of the differences in dspace.cfg. I thought it has been corrected when the handle was corrected.

**Comment by keithgee** [comment]
I've manually edited dspace.cfg and opened a TeamDynamix request to restart Tomcat on VTechWorks.

**Comment by keithgee** [comment]
Aaron has restarted Tomcat after the edit, and this has resolved the issue.
This is something to watch for - it may occur again after deployment.
Closing.

**Comment by amandafrench** [comment]
Thanks for this, @keithgee!
