### ISSUE TITLE
Empty bars/pipes in the "dc.contributor.author" field (Rare Books Collection)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#98]
Hi all, the problem that Anne was having with the ETDs and the double bars/pipes has infected the [Rare Books collection] (http://vtechworks.lib.vt.edu/handle/10919/5518)! The empty "dc.contributor.author" fields appear as pipes, which is a pain in the neck (see picture below). I know the fields are currently empty, and although they were originally empty, DSpace assigned a unique identifier to these empty/null values (which I removed). Although it's against cataloging conventions, I'd be comfortable with adding "Unknown" as a dummy value for items with no authors just to get around this mess (Anne - if you've found a workaround for this, let me know). Thanks all.

![screen shot 2015-11-11 at 5 10 02 pm](https://cloud.githubusercontent.com/assets/5408616/11104493/13742128-8897-11e5-9c5b-31d7b412b901.png)

**Comment by keithgee** [comment]
Thanks for finding this, @mello99. I've cleaned it up by removing all empty contributor.author fields in the database (18 of them, though it sounds like you had already deleted the ones in this particular collection) and then started a new build of the solr search index.

It's gone, at least from this collection.
Closing.

**Comment by alawvt** [comment]
@keithgee, thank you for fixing this. I'd like to talk about how we might do this for the rest of the repository, since there are hundreds of these empty fields in the ETD collections, alone. So far, it seems like they are items that were in the initial import into VTechWorks back in 2011.

**Comment by amandafrench** [comment]
I asked for shell access for @AmberPoo1, so when (if) she has that she can begin making some of these type of changes. 

It does sound like one browser-based workaround is to export the metadata from the collection, delete the empty fields, and then reupload the metadata, so that's an option.

**Comment by alawvt** [comment]
The browser could work for many changes but this particular issue will probably have to be fixed directly in SQL. We could size up the situation off line, though with a recent database dump from @keithgee.
